### ISSUE TITLE
Force numeric when col_types specifies it

### ISSUE THREAD

**Issue by brianboonstra** [tidyverse/readxl#106]
Currently we have

```
      case CELL_TEXT:
        Rcpp::warning("Expecting numeric in [%i, %i] got `%s`",
          i + 1, j + 1, (char*) cell.str);
        REAL(col)[i] = NA_REAL;
```

which fails to populate a cell with numeric data even when the user has specified a given column to be numeric.  This feature request is to parse to a numeric type in such cases.

Example:  

  u <- "https://www.spdrs.com/site-content/xls/XBI_All_Holdings.xls?fund=XBI&docname=All+Holdings&onyx_code1=1286&onyx_code2=1718"
  outfile <- tempfile(paste0(etf, administrator,"_Holdings"), fileext=".xls")
  xls.holdings <- curl::curl_download(u, outfile)
  holdings <- readxl::read_excel(outfile, skip=3, 
                                 col_types=c("text","text","numeric","text","numeric"))

**Comment by hadley** [comment]
How exactly do you want text converted into numbers?

**Comment by brianboonstra** [comment]
Fair question....In the example above, we get a set of warnings that look like this:
```
> warnings()[c(1,50)]
Warning messages:
    1: In xls_cols(path, sheet, col_names = col_names, col_types = col_types,  ... :
      Expecting numeric in [1, 3] got `2.020645`
    2: In xls_cols(path, sheet, col_names = col_names, col_types = col_types,  ... :
      Expecting numeric in [25, 5] got `228266.000`
```

so at least in cases like this, it would be reasonable to use `atof()`.  I would suggest that when the user has asked for a numeric column, each entry, when TEXT, try to apply a conversion and return `NA` if and only if numeric conversion fails.
