### ISSUE TITLE
Hang while reading a xls

### ISSUE THREAD

**Issue by renkun-ken** [tidyverse/readxl#113]
I download [this xls](http://www.csindex.com.cn/sseportal/ps/zhs/hqjt/csi/000300closeweight.xls) and read it with the latest version of `readxl`, `read_excel` will hang forever.

```
library(readxl)
file <- tempfile(fileext = ".xls")
download.file("http://www.csindex.com.cn/sseportal/ps/zhs/hqjt/csi/000300closeweight.xls", file, quiet = TRUE)
df <- read_excel(file, sheet = 1)
```

I converted the file to xlsx manually and it works.

**Comment by imanuelcostigan** [comment]
I have a different "problem" when reading an XLS file that I didn't create. I can read the file in fine. However, it prints the following out to console (even if I assign output from `read_excel` to a variable):

```
> var <- read_excel(fn, "sheetname")
DEFINEDNAME: 00 00 00 0d 0b 00 00 00 00 00 00 00 00 00 00 43 6f 6e 74 72 69 62 75 74 69 6f 6e 73 3b 01 00 00 00 fc 00 00 00 2f 00 
DEFINEDNAME: 00 00 00 0c 0b 00 00 00 00 00 00 00 00 00 00 50 61 72 74 69 63 69 70 61 6e 74 73 3b 02 00 00 00 1f 00 00 00 00 00 
DEFINEDNAME: 00 00 00 07 0b 00 00 00 00 00 00 00 00 00 00 52 65 73 75 6c 74 73 3b 00 00 00 00 fc 00 00 00 18 00 
```

The `DEFINEDNAME` text and what looks like raw output is exactly as it prints to console.

I don't have this issue when reading in an XLS file I create using Office 2010 32-bit v14.0.6129.5000

**Comment by imanuelcostigan** [comment]
I should note:

1. That although I see the raw output above, when I `View()` the data set, the data is represented correctly. 
2. That when I save the same file as an xlsx file, I don't have these printing issues.

**Comment by jennybc** [comment]
@imanuelcostigan Your problem is #82, which just got fixed. I'm deleting your comments to reduce confusion.

**Comment by hadley** [comment]
This file now works for me, so I'm going to assume it's been fixed by something else. The column names contain non-ASCII characters so #125 is also likely to be involved.
