### ISSUE TITLE
feature request: align all read_*  decompression and download behavior with read_delim()?

### ISSUE THREAD

**Issue by ajdamico** [tidyverse/readxl#115]
hi, i'm curious if this behavior from `?read_delim` can/should be extended to `readr` and perhaps even the functions inside `haven`?  thanks hadley

`Files ending in .gz, .bz2, .xz, or .zip will be automatically uncompressed. Files starting with http://, https://, ftp://, or ftps:// will be automatically downloaded.`

**Comment by jennybc** [comment]
Related to #192 ("input via rawConnection"). #183 ("URL support?"), and #93 ("Read file directly from memory").

**Comment by jennybc** [comment]
Covered by #278.
