### ISSUE TITLE
possible issue with reading some big xlsx file

### ISSUE THREAD

**Issue by dracodoc** [tidyverse/readxl#122]
I tried to analyze NFIRS fire incident data from here:
https://www.fema.gov/media-library/assets/documents/34093

> require(readxl)
> Loading required package: readxl
> basic_2007 = read_excel("data/NFIRS/2007/2007basicincident.xlsx")

readxl keep using all the RAM (12G) in reading the 190M 2007 Fire Basic Incident Data, I stopped it after 5 minutes.

Is this normal?

I'm using R 3.2.2 and the newest version RStudio.

**Comment by audiolion** [comment]
I think there are some issues with readxl and large data sets, on 8GB of RAM I am having trouble with over 700,000 records/70mb file across 23 attributes (cols). Probably why readxl is so blazing fast as compared to other libraries, but you can also use github.com/awalker89/openxlsx for larger sets, it is not as fast but it can handle larger files without chewing through all your RAM

**Comment by baderstine** [comment]
I am experiencing a similar issue. 

read_excel(...) input XLSX file has the maximum number of rows (1,048,...) and 48 columns (350MB)
![read_excel load](https://cloud.githubusercontent.com/assets/2738299/20077309/e2190af4-a509-11e6-8a63-63d625e8d722.PNG)

I have 16GB of RAM and it uses it all up pretty quick such that the machine becomes unresponsive and unusable for a few minutes until enough RAM is freed to continue using the machine.  Took over 15 minutes and having a tough time trying to kill RStudio so I can start over with a different package.

read.xlsx() function from the 'openxlsx' package was able to load the dataset faster and without using up all of the available RAM.

**Comment by jennybc** [comment]
readxl appears to work reasonably well for a wide range of spreadsheets and available RAM, but you've obviously found some uncomfortably large sheets. There have been some recent changes in the development version that *might* improve performance, although that was not an actual goal. Please try the dev version or the next CRAN release to check. In any case, we have no immediate plans to tackle this explicitly.
