### ISSUE TITLE
numeric not recognized

### ISSUE THREAD

**Issue by phahn57** [tidyverse/readxl#132]
I import a xlsx file. Dim( 162,22). German colon "350,4"  are correctly changed to dot "350.4.
There are many N.A in the excel sheet. I then changed N.A to -1 and excluded rows and columns thereafter. 
Rstudio List view gives num and class of remaining columns gives "numeric"
When I try to fit a gbm.fit i get an error:
Column ... is not of type numeric,ordered or factor. class() says, it is
Cannot understand how to solve this. Searched more than three hours for a solution.

Thanks Peter

**Comment by jennybc** [comment]
## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Preferably stripped down to the minimal size and complexity to demonstrate your point. And, obviously, stripped of any sensitive data.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained. *Currently GitHub-only, but going to CRAN soon.*
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide the xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.
