### ISSUE TITLE
Error: std::bad_alloc

### ISSUE THREAD

**Issue by nortonle** [tidyverse/readxl#150]
I am not sure if this is my laptop problems or the package problem. The problem occurs when I am reading 9 excel files, each file contain data in sheet number 2, each sheet contains exactly 65.000 records. After reading one file, the file will be rbind to the previous one. 

Here is the code
client_2 <- do.call(rbind, lapply(filenames, read_excel, col_names = T, sheet = 2))

Currently, I am using R 3.2.2 on Windows 7 32bit, 4GB RAM. This is my workplace laptop so I can upgrade to 64bit of Windows. 

Would you please tell me if this is my laptop problem or the package problem?

**Comment by audiolion** [comment]
I have recently gotten this issue too, win 7 R 3.2.3, 64 bit and 8gb ram. I believe it comes from reading too many rows, I think there is a point where readxl somehow can't allocate enough space in memory or whatever structure holding the data is too large to read it all in. I am going to do some testing and figure out if I can pinpoint the bottleneck in the code.

**Comment by vladdsm** [comment]
Same for me. Now reading files containing 52k rows has got an issue. Closing and re-opening Rstudio solves the problem

**Comment by jennybc** [comment]
readxl appears to work reasonably well for a wide range of spreadsheets and available RAM, but you've obviously found some uncomfortably large sheets / problems. @nortonle I note that 4GB RAM is not very much these days 😁.

There have been some recent changes in the development version that *might* improve performance, although that was not an actual goal. Please try the dev version or the next CRAN release to check. In any case, we have no immediate plans to tackle this explicitly.

**Comment by MidhunT** [comment]
I get the same error with the latest version 1.0.0 of the package when I try `read_excel(path = x, sheet = y, col_names = T)` and when I try by downgrading the package with the same code it is ignoring one of the column. I have few timestamp columns so when I try by adding `col_types = c(rep("text"), 4)` it throwing me an error saying `Error in xls_cols(path, sheet, col_names = col_names, col_types = col_types,  : 
  col_names and col_types must have the same length` When I clearly have only 4 columns. 
I'm using 16gb machine and i7 processor, I guess RAM size should not be an issue here.
