### ISSUE TITLE
Dates and time are not correctly converted

### ISSUE THREAD

**Issue by jcpsantiago** [tidyverse/readxl#160]
My excel file has a lot of cols with time in the format (20:42) and dates (YYYY-MM-DD) but these are being imported as: 0,83333 and 42422. 

how I'm doing it:

```
# which file should be imported?
workbook <- "rawdata.xlsx"

# don't use the first sheet because it's a readme
noReadme <- "README"
sheets <- excel_sheets(workbook) %>% setdiff(noReadme)

# create a list with all the dataframes
l <- lapply(sheets, function(v) read_excel(workbook, sheet = v))

# name all elements of the list with the correct name
names(l) <- sheets 

# extract all dataframes from the list
list2env(l, envir = .GlobalEnv)
```

I was also wondering if it's possible to import strings as factor

**Comment by jcpsantiago** [comment]
I "fixed" it by saving all time cols in excel as text (a very annoying affair, but for that there's only excel to blame).

No idea on how to use strings as factors though

**Comment by methodds** [comment]
I have the same problem and manually entering column types did not help. Any way to fix this without changing data types in the Excel source?

**Comment by jennybc** [comment]
For (re)conversion of character data, use `readr::type_convert()` in the Hadleyverse or `type.convert()` from base R (`utils`, actually).

**Comment by njburgoyne** [comment]
I have issues associated with numeric values (in a custom accountancy format) that end up being converted to dates. The original values can be returned by subtracting the excel origin. Not sure if this helps.

**Comment by jennybc** [comment]
@jcpsantiago @methodds can either of you provide a minimal sheet and reprex?

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Preferably stripped down to the minimal size and complexity to demonstrate your point. And, obviously, stripped of any sensitive data.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained. *Currently GitHub-only, but going to CRAN soon.*
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide the xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by jennybc** [comment]
Closing because it's been 6 weeks since requested an example sheet + reprex.
