### ISSUE TITLE
Unexpected error specifying col names/types in a file with a blank column

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/readxl#169]
I've got an excel file with, say 10 columns.

The first column is blank, and `read_excel` intelligently does away with this column, so that

```
data <- read_excel("file.xls")
ncol(data)
```

is 9, not 10.

It seems natural, then, that I should supply 9 column names to `col_names`, but this is an error, since the processing of column names & types is done before the column disappears. 

I guess this is closely related to #81.

**Comment by jennybc** [comment]
Yes agree this is covered by #81.
