### ISSUE TITLE
segmentation fault with large Excel files

### ISSUE THREAD

**Issue by DasHammett** [tidyverse/readxl#171]
Hi, 

Whenever I try to open an Excel file (both xls or xlsx) bigger than around 10MB, R crashes. Please see below the segfault output from R:

```
 fread: wanted 1 got 0 loc=2199023254016

 *** caught segfault ***
address 0x36e3000, cause 'memory not mapped'

Traceback:
 1: .Call("readxl_xls_col_names", PACKAGE = "readxl", path, i, nskip)
 2: xls_col_names(path, sheet, nskip = skip)
 3: read_xls(path, sheet, col_names, col_types, na, skip)
 4: read_excel("/home/hammett/src/R Scripts/Case_Detail.xls")
```

For Excel files smaller than those 10MB, read_excel is working as expected.

Output from sessionInfo()

```
R version 3.2.5 (2016-04-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Gentoo/Linux

locale:
 [1] LC_CTYPE=es_ES.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] graphics  grDevices utils     datasets  stats     methods   base     

other attached packages:
[1] dplyr_0.4.3   magrittr_1.5  ggplot2_2.1.0

loaded via a namespace (and not attached):
 [1] colorspace_1.2-6 scales_0.4.0     R6_2.1.2         assertthat_0.1  
 [5] plyr_1.8.3       parallel_3.2.5   tools_3.2.5      DBI_0.3.1       
 [9] gtable_0.2.0     Rcpp_0.12.4      grid_3.2.5       munsell_0.4.3   
```

Thank you

**Comment by jennybc** [comment]
Can you provide an example of a file that triggers this problem? Perhaps by finding one we can all download from internet?

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Preferably stripped down to the minimal size and complexity to demonstrate your point. And, obviously, stripped of any sensitive data.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained. *Currently GitHub-only, but going to CRAN soon.*
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide the xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by jennybc** [comment]
readxl appears to work reasonably well for a wide range of spreadsheets and available RAM, but you've obviously found some uncomfortably large sheets. There have been some recent changes in the development version that *might* improve performance, although that was not an actual goal. Please try the dev version or the next CRAN release to check. In any case, we have no immediate plans to tackle this explicitly.
