### ISSUE TITLE
Converting line breaks in Excel cells

### ISSUE THREAD

**Issue by gabucsc** [tidyverse/readxl#179]
read_excel converts line breaks in Excel cells with the `\r\n` Windows convention.
When printing results, the `\r` causes a non correct location of the cursor in the R Console.
e.g. with the code

```
> cat("this example \r\n continues on the next line")
this example 
 continues on the next line> 
> 
>
>          |
```

the cursor remains placed after `continuous` instead after `>`.
To return to the correct position one has to use Ctrl+L + Enter  or a repeated sequence of Esc.
Using only `\n` the location is correct.

```
> cat("this example \n continues on the next line")
this example 
 continues on the next line> 
> 
> 
> |
```

**Comment by jennybc** [comment]
## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Preferably stripped down to the minimal size and complexity to demonstrate your point. And, obviously, stripped of any sensitive data.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained. *Currently GitHub-only, but going to CRAN soon.*
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide the xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by gabucsc** [comment]
Found the problem on Windows platforms. It is only a graphical issue regarding the vertical line of the input cursor. All code works fine.
Checked also on Debian and it is all ok.

[readxl.pdf](https://github.com/hadley/readxl/files/701756/readxl.pdf) contains a complete description of the encountered graphical issue.

In order to reproduce the problem you can use this mock file [studentcomplex.xlsx](https://github.com/hadley/readxl/files/701736/studentcomplex.xlsx) with the following code 

``` r
library(readxl)                                                                                                   
student <- read_excel("studentcomplex.xlsx", 1)                                                                   
student                                                                                                           
#>   Last Name  First Name         Username      Answer Income
#> 1     Brown        Mary    brown.3556975         Yes  24402
#> 2  Dempster       Jose' dempster.3512323 no\r\nnever  27572
#> 3 Mac Laren   Catherine maclaren.3573397   Yes; once  77270
#> 4   O'Brian John Joseph   obrian.3563863  yes, twice  37216
#> 5     Smith       Diane    smith.3550378          no  48517
student$Answer                                                                                                    
#> [1] "Yes"         "no\r\nnever" "Yes; once"   "yes, twice"  "no"
#the line break in the category expressed by Dempster (see cell D3, in the xlsx file) has been recoded with \r\n
cat(student$Answer)                                                                                               
#> Yes no
#> never Yes; once yes, twice no
student[2, ]                                                                                                      
#>   Last Name First Name         Username      Answer Income
#> 2  Dempster      Jose' dempster.3512323 no\r\nnever  27572
                                                                                                                  
                                                                                                                  
                                                                                                                  
student[2, 4] <- "no\nnever"                                                                                     
cat(student$Answer)                                                                                               
#> Yes no
#> never Yes; once yes, twice no
```

<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info --------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.3.2 (2016-10-31)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language ENGLISH                     
#>  collate  Italian_Italy.1252          
#>  tz       Europe/Berlin               
#>  date     2017-01-12
#> Packages ------------------------------------------------------------------
#>  package   * version date       source        
#>  backports   1.0.4   2016-10-24 CRAN (R 3.3.2)
#>  devtools    1.12.0  2016-06-24 CRAN (R 3.3.2)
#>  digest      0.6.11  2017-01-03 CRAN (R 3.3.2)
#>  evaluate    0.10    2016-10-11 CRAN (R 3.3.2)
#>  htmltools   0.3.5   2016-03-21 CRAN (R 3.3.2)
#>  knitr       1.15.1  2016-11-22 CRAN (R 3.3.2)
#>  magrittr    1.5     2014-11-22 CRAN (R 3.3.2)
#>  memoise     1.0.0   2016-01-29 CRAN (R 3.3.2)
#>  Rcpp        0.12.8  2016-11-17 CRAN (R 3.3.2)
#>  readxl    * 0.1.1   2016-03-28 CRAN (R 3.3.2)
#>  rmarkdown   1.3     2016-12-21 CRAN (R 3.3.2)
#>  rprojroot   1.1     2016-10-29 CRAN (R 3.3.2)
#>  stringi     1.1.2   2016-10-01 CRAN (R 3.3.2)
#>  stringr     1.1.0   2016-08-19 CRAN (R 3.3.2)
#>  withr       1.0.2   2016-06-20 CRAN (R 3.3.2)
#>  yaml        2.1.14  2016-11-12 CRAN (R 3.3.2)
```

</details>

**Comment by jennybc** [comment]
Thanks, this will help!

**Comment by gabucsc** [comment]
Hi Jenny,

thank you very much to try solving the problem;

it is not an important error, but its fix surely avoids possible questions by 
students when importing that mock,

with best regards,

Gabriele


On 12 Jan 2017 at 7:37, Jennifer (Jenny) Bryan wrote:

> 
> Thanks, this will help!
> -
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.




Dipartimento di Scienze statistiche
Universit� Cattolica del Sacro Cuore
Largo A. Gemelli, 1
20123   Milano
http://docenti.unicatt.it/ita/Gabriele_Cantaluppi
http://docenti.unicatt.it/eng/Gabriele_Cantaluppi
tel +39 0272342492
fax +39 0272343064

**Comment by hadley** [comment]
This seems like a bug on RGui for windows, not readxl.
