### ISSUE TITLE
URL support?

### ISSUE THREAD

**Issue by Ironholds** [tidyverse/readxl#183]
Readr (oh, readr, how I love you) supports, amongst other things, identifying that a file argument is actually a URL and treating it appropriately. Any chance readxl could get support for the same?

**Comment by benmarwick** [comment]
Would #77 fix this?

**Comment by vojtechhuser** [comment]
the URL testing file is broken. I tried it on https://evs.nci.nih.gov/ftp1/CDISC/SDTM/SDTM%20Terminology.xls and it fails

**Comment by Ironholds** [comment]
Yeah, it doesn't look integrated

**Comment by jennybc** [comment]
Covered by #278.

**Comment by igordot** [comment]
Curiously, `rio::import` which supposedly uses `readxl::read_excel` for Excel can actually read from a URL. Sure, it's an extra layer, but it seems to work.

**Comment by jennybc** [comment]
Yeah, rio has an all-purpose `remote_to_local()` function. We've discussed doing similar to give readxl a working solution. The RStudio readxl helper does same.

https://github.com/leeper/rio/blob/0d1fcf929882d88abc01243af48e621f65768793/R/remote_to_local.R#L1
