### ISSUE TITLE
problem reading formula values

### ISSUE THREAD

**Issue by alanpaulkwan** [tidyverse/readxl#186]
[readxl_example.xlsx](https://github.com/hadley/readxl/files/332860/readxl_example.xlsx)

The problem with the above file is that if you read in a formula, the formula evaluates to 0. At the very least, the formula should evaluate to the formula. For example, the ideal behavior might be the first column reads as text... "=DATE(2015,1,1)".

An alternative would be to evaluate the formula or use the preloaded value, but I assume the first might be a pain in the behind and the second might lead to unpredictable behavior. 

``` r, echo=FALSE

read_excel("readxl_example.xlsx")

```

**Comment by jennybc** [comment]
> The problem with the above file is that if you read in a formula, the formula evaluates to 0

I don't see that. Can you provide a reprex showing exactly what happens for you?

``` r
library(readxl)
read_excel("iss/readxl_example.xlsx")
#>        hello hadley     thanks in advance
#> 1 2015-01-01      5 "1/1/2015"  5      10
#> 2 2015-01-01      5 "1/1/2015"  5      10
#> 3 2015-01-01      5 "1/1/2015"  5      10
#> 4 2015-01-01      5 "1/1/2015"  5      10
#> 5 2015-01-01      5 "1/1/2015"  5      10
#> 6 2015-01-01      5 "1/1/2015"  5      10
#> 7 2015-01-01      5 "1/1/2015"  5      10
#> 8 2015-01-01      5 "1/1/2015"  5      10
#> 9 2015-01-01      5 "1/1/2015"  5      10
```

**Comment by jennybc** [comment]
## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.
