### ISSUE TITLE
input via rawConnection

### ISSUE THREAD

**Issue by harveyl888** [tidyverse/readxl#192]
Is it possible to read an excel file which is stored as a raw vector?
I have excel files stored in a mongodb database (gridfs) and retrieve them via a search.  I can grab the file content as a binary rawConnection.  For data stored in csv format the following code will read in rawData using the read_csv function from the readr library:

```
print(rawData[1:20])
[1] 4e 61 6d 65 2c 31 20 5b 70 6f 73 5d 2c 32 20 5b 70 6f 73 5d

f <- rawConnection(rawData, 'r+b')
myContents <- readr::read_csv(x)
```

is it possible to do something similar using the readxl library for an xlsx file?
Thanks!

**Comment by jennybc** [comment]
Covered by #278.
