### ISSUE TITLE
Better documentation of col_types = "blank"

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/readxl#193]
It's not clear what's being done when `col_types = "blank"`, and this is only given passing mention in `?read_excel`.

See [this](http://stackoverflow.com/questions/38404366/removing-all-columns-with-a-name-on-the-fly) SO question -- for example, is the data in each `"blank"` column read into memory before being discarded?

**Comment by jennybc** [comment]
Covered by #260 now.
