### ISSUE TITLE
Consider adding warning when .xls file reads in exactly 65,535 rows

### ISSUE THREAD

**Issue by jon-mellon** [tidyverse/readxl#209]
Just a possible feature request to consider including a warning when the .xls file you've read in is at exactly the excel row limit of 65535 rows (which often indicates that you don't have complete data).

**Comment by jennybc** [comment]
This is a good idea that we will keep in mind when we upgrade to a more comprehensive "problems" approach for reporting on problematic imports. Therefore closing but linking to #307 for the future. Thanks.
