### ISSUE TITLE
feature request: trim whitespace on read

### ISSUE THREAD

**Issue by gitJMDR** [tidyverse/readxl#211]
It'd be great to have an option like strip.white=TRUE, or strip_white=BOTH to automatically remove leading or trailing whitespace on import.

**Comment by svenhalvorson** [comment]
I think this is very important as well especially in light of how dplyr takes in column names. If you import a data set with spaces in the column names, you have to rename them to use select(), arrange(), ect.

**Comment by jennybc** [comment]
@svenhalvorson Even if leading and trailing whitespace is trimmed, this won't touch embedded whitespace. You can deal with such column names like so:

``` r
suppressPackageStartupMessages(library(tidyverse))
(df <- tibble(`with space` = 1:2))
#> # A tibble: 2 × 1
#>   `with space`
#>          <int>
#> 1            1
#> 2            2
df %>% 
  rename(no_space = `with space`)
#> # A tibble: 2 × 1
#>   no_space
#>      <int>
#> 1        1
#> 2        2
```

**Comment by hadley** [comment]
Alternatively you could just do: `purrr::modify_if(df, is.character, trimws)` (assuming you have the dev version of purrr, which will be released soon)

**Comment by jennybc** [comment]
Why it's needed:

  1. It *is* handy.
  1. readr does it and readxl wants to grow up to be readr, but for spreadsheets.
  1. The `modify_if()` workaround doesn't address column names. Sure, something similar could be done on the names. But that gets back to point 1.

Why it's not needed:

  * Col type guessing is different in readxl vs readr: it's based on cell types declared in the xls[x] file, not on the data. So whitespace trimming isn't nearly as high stakes. Post import modification of character cols, e.g. `modify_if()`, is viable.
