### ISSUE TITLE
Adopt guess_max a la readr

### ISSUE THREAD

**Issue by jennybc** [tidyverse/readxl#223]
Propose `read_excel()` follow readr and gain a `guess_max` parameter with similar default behaviour:

> guess_max   Maximum number of records to use for guessing column types.
> ... n_max = Inf, guess_max = min(1000, n_max), ...

Do you approve in principle @hadley?

Would subsume issues #206 #131 , PRs #138 #143

**Comment by hadley** [comment]
👍

**Comment by tklebel** [comment]
@jennybc is there a way I could update PR #138 in order to implement this, or are you planning on reworking readxl internals considerably, which would make the PR obsolete?

**Comment by jennybc** [comment]
I haven't gotten that far, I'm just triaging issues. I think there will be several changes to make ingest more consistent with rest of tidyverse, most especially with readr. If there are easy ways to update #138 that seem likely to be what's needed, that would be great and I'll try to use it.

**Comment by jennybc** [comment]
Good example of workbook with 3 columns that are assumed to be numeric but then are, in fact, not.

``` r
library(readxl)

theURL <- "https://github.com/tts/villisika/raw/master/SpeciesObservations.xlsx"
tf <- tempfile(fileext = ".xlsx")
download.file(theURL, tf)
data_se <- read_excel(tf, sheet = "SLW Data")
#> Warning in read_xlsx_(path, sheet, col_names = col_names, col_types =
#> col_types, : [123, 70]: expecting numeric: got 'Skyddad vik vid lerig
#> älvstrand'
#> Warning in read_xlsx_(path, sheet, col_names = col_names, col_types =
#> col_types, : [139, 103]: expecting numeric: got 'Tomtskådning Dyudden'
#> Warning in read_xlsx_(path, sheet, col_names = col_names, col_types =
#> col_types, : [139, 104]: expecting numeric: got 'Arter noterade från
#> tomten Gäddeholm 2:59 på Dyuddens sydspets, med adress Gäddeholm 73, 725 97
#> Västerås. Startade 29 oktober 2006, dagen efter inflyttning. '
#> Warning in read_xlsx_(path, sheet, col_names = col_names, col_types =
#> MORE OF THE SAME ... LOTS MORE

## which columns are the problematic ones?
cellranger::num_to_letter(c(70, 103, 104))
#> [1] "BR" "CY" "CZ"
```

**Comment by tomsing1** [comment]
Apologies if this was covered elsewhere already, but perhaps `read_excel` could also gain the `n_max` argument used by `readr::read_csv`? 

I find it often useful to read a particularly difficult worksheet in chunks, e.g. by combining `readr::read_csv`'s `n_max` and `skip` arguments.

**Comment by jennybc** [comment]
@tomsing1 I was wondering if/when someone would request that! Can you open a new issue for that please?

**Comment by tomsing1** [comment]
Done! The new issue is #281
