### ISSUE TITLE
write_excel(): write a data frame to xlsx

### ISSUE THREAD

**Issue by slfan2013** [tidyverse/readxl#231]
Hi guys, I wonder if there is a `readxl::write_excel` coming up in the future?

I love the `readxl::read_excel` very much because it is really fast and is independent of Java. 

For some reasons, I cannot use `xlsx::write.xlsx2`, which is also fast but requires Java. But `xlsx::write.xlsx` is really slow. It would be super nice if there will be a `write_excel` in `readxl`.  And any suggestion of fast writing excel is absolutely welcomed. Thanks!

**Comment by jennybc** [comment]
@hadley and I were just discussing this. Perhaps readxl will gain the ability to write xlsx, but with a very specific scope. Data yes, formatting no, for example. But first the existing bugs and feature requests have to be sorted out.

**Comment by slfan2013** [comment]
That's great to hear!  

Do you guys have an approximate estimation of when this cool function launches?

**Comment by stla** [comment]
Hello @slfan2013. You can use [WriteXLS](https://cran.r-project.org/web/packages/WriteXLS/index.html) (requiring `perl`) if you are in a hurry.

**Comment by slfan2013** [comment]
Hi @stla , thanks!

**Comment by jennybc** [comment]
In the here and now, there's also openxlsx for writing. It was used to create the example xlsx and xls that ship with readxl. See the bottom of the readxl README: <https://github.com/hadley/readxl#readme>.

**Comment by slfan2013** [comment]
@jennybc Thanks! I am now using `openxlsx`, which is faster than `xlsx`, while waiting for `write_excel`.

**Comment by jeroen** [comment]
A new package `writexl` is on CRAN now. Version 0.1 is very simple but it includes a powerful library so we can easily add more complex formatting and objects.

**Comment by jennybc** [comment]
Terribly exciting, @jeroen! 🎉 Yes I will gladly use writexl to provide this functionality here.

**Comment by slfan2013** [comment]
Thanks, @jeroen 
I love using your tools.

**Comment by slfan2013** [comment]
Hi @jeroen , if it's possible to have a feature of saving data at different sheets in the same excel?

Sorry, I don't know where I should ask this question so I post it here.

**Comment by cderv** [comment]
Hi @slfan2013, `writexl` repo is at this url: https://github.com/ropensci/writexl

You could open issue about feature request there.

**Comment by ZedLeb** [comment]
Great timing @jeroen I just wanted to make a transition between R, Excel and Power BI that bit smoother and this works great!  Many thanks.
