### ISSUE TITLE
Feature Request: Read in all columns as the same type

### ISSUE THREAD

**Issue by ahoho** [tidyverse/readxl#249]
When reading in a set of multiple Excel files (e.g., in an `lapply` before calling `dplyr::bind_rows`), the number of columns in each file may not be known in advance, meaning that a `col_types` vector can't be specified. As a result, it would be helpful to force a common format for all columns as they are read in.

**Comment by jennybc** [comment]
Duplicate of #198, especially https://github.com/tidyverse/readxl/issues/198#issuecomment-277499197.
