### ISSUE TITLE
replace user-facing "blank" column type with "skip"

### ISSUE THREAD

**Issue by jennybc** [tidyverse/readxl#260]
Internally keep using `CELL_BLANK` for cells with no content (?) or that match one of the `NA` strings.

Externally the `"blank"` column type should be replaced with something that more clearly says "skip this column".

As per #193, consider that users may want more detail, i.e. whether cells in a skipped column are even read.

**Comment by MichaelChirico** [comment]
thanks for all the excellent work recently @jennybc!
