### ISSUE TITLE
Dates in Excel's internal format

### ISSUE THREAD

**Issue by pitakakariki** [tidyverse/readxl#266]
I have a column which has dates in Excel's internal format. The Excel file comes from someone's reporting software, so I can't just format the column in Excel (unless I want to do it every time I get an update).

◢ |Date
-|-
1|39448
2|39449
3|39450

[date_test.xlsx](https://github.com/tidyverse/readxl/files/772728/date_test.xlsx)

These should map to the first, second, and third of January 2008.

```{r}
> as.Date(read_excel("../notes/date_test.xlsx")$Date, origin="1899-12-30")
[1] "2008-01-01" "2008-01-02" "2008-01-03"
```

But if I tell `read_excel` that it's a date: 

     z <- read_excel("../notes/date_test.xlsx", col_types="date")

```{r}
Warning messages:
1: In read_xlsx_(path, sheet, col_names = col_names, col_types = col_types,  :
  [2, 1]: expecting date: got '39448'
2: In read_xlsx_(path, sheet, col_names = col_names, col_types = col_types,  :
  [3, 1]: expecting date: got '39449'
3: In read_xlsx_(path, sheet, col_names = col_names, col_types = col_types,  :
  [4, 1]: expecting date: got '39450'
```

```{r}
> z
  Date
1 <NA>
2 <NA>
3 <NA>
```

**Comment by jennybc** [comment]
> I have a column which has dates in Excel's internal format.

So this isn't quite true. Generally, a date cell in xlsx will carry a date style, which these cells do not. They are just integers and it is a choice to interpret them as dates. But I suppose we can interpret numbers as dates, when explicitly directed to do so via `col_types = "date"`.
