### ISSUE TITLE
‘readx’ issue <chr>

### ISSUE THREAD

**Issue by LeuteMatthias** [tidyverse/readxl#267]
I have a problem with the ‘readxl’ package. I need to re-install the package every time when I quit an R session. Unfortunately, loading the package from the library leads to a failure in correctly reading in my data -> screenshots + data file in link below. Apparently many cells are filled with <chr>. I hope this is not a mistake from my side but I cannot figure out why it works correctly after re-installation.

2 Screenshots and a file are provided in the following link:
https://drive.google.com/drive/folders/0B90MEgZr0TE8QzJ2LUFfdEpncTQ?usp=sharing

**Comment by tklebel** [comment]
Is it simply, that in the first screenshot `tibble` is loaded as well, whereas in the second one it is not?
Then your `data.frame`s would be identical, just the behavior when printing would be different.

The explanation is in differing approaches between dev-version and CRAN-version: The CRAN version is quite old and doesn't use tibble, the dev-version does. 
You can view all your correctly loaded data by using `my_dat <- read_excel("data.xlsx"); View(my_dat)`.

**Comment by jennybc** [comment]
I'm with @tklebel and suspect you may just be reacting to two different styles of data frame printing:

  * base R data frame printing
  * tibble printing from the tibble package, which implements a special case of data frame

readxl (CRAN and GitHub) always returns a tibble. But the CRAN version did not guarantee that the tibble package would be used for printing and, more importantly `[` indexing using `drop = FALSE`.

The GitHub/development version of readxl explicitly guarantees that the printing and indexing for tibbles will come from the tibble package.

Even if you're not experimenting with two versions of readxl, with the CRAN version you could see these differences depending on other packages you have loaded explicitly or via various R start up files. That's obviously bad and is exactly why we've fixed this in the dev version.

I recommend you use the GitHub version or, if using the CRAN version, always load tibble yourself:

``` r
library(tibble)
library(readxl) # if using the CRAN version
```

**Comment by LeuteMatthias** [comment]
Thanks for the replies :)
If I understand what you're saying correct that it would just be a matter of how the data.frame is displayed however, the variables in the data.frame were indeed incorrect. Weirdly enough I am not able to replicate the error anymore although I've experienced it every single day for the past month.
If the error re-occures I will reinvestigate but I think for now this is resolved from my side.

Thanks a lot!
Matt
