### ISSUE TITLE
Potential memory leak with read_xlsx on Linux

### ISSUE THREAD

**Issue by mbeigel** [tidyverse/readxl#269]
When reading `.xlsx` files using `read_excel` the memory usage of the associated R sessions jump to about 100x times the original file size, and this memory usage is not reported by `gc()` but can be seen if you look at the actual process. Removing the associated object created by using `read_excel` doesn't resolve the problem, and memory usage remains high and unreported by `gc()`. This interferes with the ability to continue using the particular R session after reading the associated dataset.

An example is provided below:

    R version 3.3.2 (2016-10-31)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 16.04.1 LTS

    locale:
     [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
     [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
     [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
     [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
     [9] LC_ADDRESS=C               LC_TELEPHONE=C
    [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  base

    other attached packages:
    [1] tibble_1.2   readxl_0.1.1

    loaded via a namespace (and not attached):
    [1] assertthat_0.1 tools_3.3.2    Rcpp_0.12.9    methods_3.3.2

    Process id of R session: 5261

    A look at memory usage before using readxl::read_excel
             used (Mb) gc trigger (Mb) max used (Mb)
    Ncells 294370 15.8     460000 24.6   350000 18.7
    Vcells 401624  3.1    1023718  7.9   786431  6.0
    VmRSS:	   38464 kB

    File info for 311_Service_Requests_from_Feb14_2017_to_Feb21_2017.xlsx
                                                               size isdir mode
    311_Service_Requests_from_Feb14_2017_to_Feb21_2017.xlsx 7346340 FALSE  644
                                                                          mtime
    311_Service_Requests_from_Feb14_2017_to_Feb21_2017.xlsx 2017-02-21 17:35:37
                                                                          ctime
    311_Service_Requests_from_Feb14_2017_to_Feb21_2017.xlsx 2017-02-21 17:35:37
                                                                          atime
    311_Service_Requests_from_Feb14_2017_to_Feb21_2017.xlsx 2017-02-21 17:36:42
                                                             uid  gid   uname
    311_Service_Requests_from_Feb14_2017_to_Feb21_2017.xlsx 1001 1002 michael
                                                             grname
    311_Service_Requests_from_Feb14_2017_to_Feb21_2017.xlsx michael

    Read the data

    Memory usage after loading the data
               used (Mb) gc trigger  (Mb) max used (Mb)
    Ncells   532669 28.5     940480  50.3   750400 40.1
    Vcells 10492263 80.1   16872233 128.8 10558308 80.6
    VmRSS:	  755584 kB

    Object size of loaded data
    32450.7 Kb

    Remove the data and report memory usage now
             used (Mb) gc trigger  (Mb) max used  (Mb)
    Ncells 303708 16.3     940480  50.3   750400  40.1
    Vcells 482964  3.7   13497786 103.0 14977285 114.3
    VmRSS:	  699328 kB

Attached is the data and file used to create this example. 
[mem_leak.zip](https://github.com/tidyverse/readxl/files/791038/mem_leak.zip)

**Comment by hadley** [comment]
This looks fine to me:

``` r
library(readxl)
gc()
#>          used (Mb) gc trigger (Mb) max used (Mb)
#> Ncells 366174 19.6     592000 31.7   460000 24.6
#> Vcells 621932  4.8    1308461 10.0  1023716  7.9
x <- read_xlsx("~/Desktop/mem_leak/311_Service_Requests_from_Feb14_2017_to_Feb21_2017.xlsx")
rm(x)
gc()
#>          used (Mb) gc trigger (Mb) max used (Mb)
#> Ncells 373860   20     750400 40.1   592000 31.7
#> Vcells 646158    5    1906625 14.6  1393077 10.7
x <- read_xlsx("~/Desktop/mem_leak/311_Service_Requests_from_Feb14_2017_to_Feb21_2017.xlsx")
rm(x)
gc()
#>          used (Mb) gc trigger (Mb) max used (Mb)
#> Ncells 373892   20     750400 40.1   592000 31.7
#> Vcells 646211    5    1906625 14.6  1408132 10.8
x <- read_xlsx("~/Desktop/mem_leak/311_Service_Requests_from_Feb14_2017_to_Feb21_2017.xlsx")
rm(x)
gc()
#>          used (Mb) gc trigger (Mb) max used (Mb)
#> Ncells 373912   20     750400 40.1   592000 31.7
#> Vcells 646244    5    1906625 14.6  1408185 10.8
```

Note that you expect memory usage to increase on the first call, as this is when the compiled C code etc is loaded into memory.
