### ISSUE TITLE
Support a logical column type?

### ISSUE THREAD

**Issue by jennybc** [tidyverse/readxl#270]
It seems like an empty column should be filled with logical `NA`s but currently readxl fills with `NA_real_`. I think @hadley has already concurred, at least in principle (https://github.com/tidyverse/tidyverse/issues/34#issuecomment-278500700). Also comes up if all the cells in a column match one of the strings in `na`.

That seems easy enough to do. But it begs the question whether this should be the only way for readxl to return a logical vector. Should `"logical"` become a new column type that can be guessed or that user could specify?

Excel cells can be of Boolean type, so that can be detected when guessing or when enforcing user-specified col types.

But do you take it further? How much effort to make with logical-ish strings and numbers?

**Comment by hadley** [comment]
I think there are two questions here:

* Should we support a logical column type for boolean values in Excel (I'd say yes)

* Should we provide better coercion tools from one type to another? As well as logical, we need to think about string to date or string to number as well. This might be quite a bit of work, but it's worth exploring.

**Comment by jennybc** [comment]
The logical column type is added in #277, along with the expected coercions (logical to numeric or text, numeric or text to logical).

> Should we provide better coercion tools from one type to another? As well as logical, we need to think about string to date or string to number as well. This might be quite a bit of work, but it's worth exploring.

I don't think string to date is urgent. If Excel recognizes a string as a date, believe me, it converts the cell to date with great zeal! So dates-as-strings are quite rare in nature. Plus it is easy enough to convert character to date on the R side.

I'm going to do string to number, which is #217.
