### ISSUE TITLE
Cannot open existing Excel File

### ISSUE THREAD

**Issue by bwiltfong** [tidyverse/readxl#276]
I cannot seem to open an existing Excel file. When the application hits the "Using" line, it gets the following error:

Object reference not set to an instance of an object.

Dim ExcelFile As New FileInfo("E:\Temp\AgingReport.xlsx")

Try
Using workbook As New XLWorkbook(ExcelFile.FullName)
     Dim ws = workbook.Worksheet("Data")

Please let me know how to solve this.

Thanks,
Bob

**Comment by jennybc** [comment]
I don't recognize any of this code. I think it must pertain to some other R package that works with Excel files. This one is readxl and I suspect you're using another.
