### ISSUE TITLE
read_excel() output bag

### ISSUE THREAD

**Issue by rslon** [tidyverse/readxl#279]
grpsource_list=readxl::read_excel('for_test.xls',sheet = 'main')

prints:

DEFINEDNAME: 21 00 00 01 0b 00 00 00 01 00 00 00 00 00 00 0d 3b 01 00 00 00 03 00 00 00 00 00 
DEFINEDNAME: 21 00 00 01 0b 00 00 00 01 00 00 00 00 00 00 0d 3b 01 00 00 00 03 00 00 00 00 00 
DEFINEDNAME: 21 00 00 01 0b 00 00 00 01 00 00 00 00 00 00 0d 3b 01 00 00 00 03 00 00 00 00 00 
DEFINEDNAME: 21 00 00 01 0b 00 00 00 01 00 00 00 00 00 00 0d 3b 01 00 00 00 03 00 00 00 00 00 
DEFINEDNAME: 21 00 00 01 0b 00 00 00 01 00 00 00 00 00 00 0d 3b 01 00 00 00 03 00 00 00 00 00 

at command line

link to xls-file https://file.io/4BlnTu

**Comment by jennybc** [comment]
This has already been fixed in the development version. Please install from github for less chatty behaviour.

**Comment by rslon** [comment]
thanx!
