### ISSUE TITLE
Read in all columns as text without data.type guess

### ISSUE THREAD

**Issue by hannes101** [tidyverse/readxl#288]
Hi all,

I am using readxl to read in nearly 1000 xlsx files. Which are not well behaved, i.e. they do have a different number of columns, which in the end I won't need all. Nevertheless, when importing the files I have two options as far as I can see, either let readxl decide on the column type and most probably end up having a lot of warnings. The other option is to define the type for each column, but then I would need to determine the number of columns before the importing and select the appropriate vector, where the column types are stored.
Would it be possible to add an option, so that regardless of the number of columns I read in all columns as text and then only select the relevant columns and do the data.type conversion in the next step.
I just have a solution for this problem, by getting the number of columns for each file I can then create a vector of this length on the fly, which only has the information "text" for each column.

Perhaps I am missing something, but I think it would be really great to have the option to read in everything as text. 

Thanks for this nice piece of software!

**Comment by jennybc** [comment]
As of 4a34a17fa6ae218256d48623fd46f90077a2156a, if `col_types` is of length 1, it will be recycled. So you can have this now if you use dev version from GitHub.

``` r
library(readxl)
read_excel(readxl::readxl_example("datasets.xlsx"), col_types = "text")
#> # A tibble: 150 × 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <chr>       <chr>        <chr>       <chr>   <chr>
#> 1           5.1         3.5          1.4         0.2  setosa
#> 2           4.9           3          1.4         0.2  setosa
#> 3           4.7         3.2          1.3         0.2  setosa
#> 4           4.6         3.1          1.5         0.2  setosa
#> 5             5         3.6          1.4         0.2  setosa
#> 6           5.4         3.9          1.7         0.4  setosa
#> 7           4.6         3.4          1.4         0.3  setosa
#> 8             5         3.4          1.5         0.2  setosa
#> 9           4.4         2.9          1.4         0.2  setosa
#> 10          4.9         3.1          1.5         0.1  setosa
#> # ... with 140 more rows
```

**Comment by hannes101** [comment]
Thanks a lot for the quick hint!
