### ISSUE TITLE
Scientific notation when numbers read as text

### ISSUE THREAD

**Issue by jennybc** [tidyverse/readxl#298]
Just read an xls with student numbers, which should be character. But the text representation is *post* conversion to scientific notation. Fix that.

**Comment by ljodea** [comment]
Bug still exists on reading xlsx files. 

Fix applied to:
https://github.com/tidyverse/readxl/blob/master/src/XlsCell.h#L238

...should also be applied to:
https://github.com/tidyverse/readxl/blob/master/src/XlsxCell.h#L205

**Comment by jennybc** [comment]
@ljodea Will you open a new issue and provide an xlsx reprex of the problem you're seeing? From reading the relevant commits and code, it sure *seems* like xlsx is OK and is being tested.
