### ISSUE TITLE
col_types problems

### ISSUE THREAD

**Issue by hackHead** [tidyverse/readxl#301]
I've run into this issue with read_excel a number of times. I'm reading in a large Excel sheet (60,371 rows and 357 columns). At first I tried to do it without specifying column types. However, some fields with text data had many rows of na values at the top, and were set to numeric by read_excel (I assume it reads some subset of rows at the top before deciding on column types). That resulted in a loss of data when read_excel encountered text data deep in columns that had been set to numeric. The warning() messages read:

In read_xlsx_(path, sheet, col_names = col_names, col_types = col_types,  ... :  [321, 100]: expecting numeric: got 'REDACTED TEXT'

I then set col_types argument with:

`c("text","date","date",rep("text",178),
                                   rep("numeric",176))`

read_excel gave me the error "Error in read_xlsx_(path, sheet, col_names = col_names, col_types = col_types,  : Need one name and type for each column"

I opened the Excel sheet and hit CTL + END to see where Excel thought the end of the data was. The cursor jumped all the way to cell TN60371, which is in line with the last row of data, but 14 columns *past* where the data resides. (I've seen this behavior in Excel many times.)

The data frame produced by read_excel correctly has just 357 columns, so it does somehow weed out those phantom 14 columns recognized by Excel. But my guess is that it applies col_types *before* doing that weeding and therefore doesn't think I've entered the correct number of arguments for col_types.

I tried adding 14 more text columns to the end of my col_types argument, but that didn't work either.

If possible, I think the best solution would be for the col_types argument to be applied after read_excel figures out where the actual data resides in a sheet and how many columns the resulting data frame will have. Also, it seems like the default data type should be text to prevent a loss of data from ever occurring. Or perhaps there could be an option for all columns to be text, without having to specify how many columns there are. The columns can always be converted down the road, of course.

I could probably provide the example file, with dummy values replacing the actual proprietary data, if that would help.

**Comment by jennybc** [comment]
Will you install the dev version from github and see if you still have this problem? Lots of the above sounds very familiar has been fixed. See [NEWS](https://github.com/tidyverse/readxl/blob/master/NEWS.md). Also you can control the number of rows used for column type guessing with `guess_max` now.

**Comment by hackHead** [comment]
Thanks for the quick response. How do I install the dev version from github?

**Comment by hackHead** [comment]
I figured out the installation:

`install.packages("devtools")
devtools::install_github("tidyverse/readxl")
`
And, yes, with that installed, this code worked:

`df <- read_excel("C:/fileName.xlsx",
                     sheet = "Sheet1",
                     col_types = c("text","date","date","text","text",
                                   rep("text",176),
                                   rep("numeric",176)))`

Thank you.
