### ISSUE TITLE
read_excel importing NAs when importing date and time from third-party xls file

### ISSUE THREAD

**Issue by ea-guerette** [tidyverse/readxl#309]
I am experiencing an issue with read_excel, reading xls files from a third-party. 

I put a cropped example file on Cloudstor as I cannot attach it here: 
https://cloudstor.aarnet.edu.au/plus/index.php/s/EK9NViho5MaxIGF

When I read the file using:

df <- read_excel("reprex_file_readxl.xls", sheet = 1, skip = 3, col_names = F, na = c("", "--"),
                 col_types = c("text", "text", "numeric", "numeric")) 

The first two columns are NAs. I tried setting the col_types to "date", and to "guess", but it did not work either. 

I downloaded readxl from git_hub using:
devtools::install_github("tidyverse/readxl")
(the CRAN version worked fine for the first two columns, but would drop the last column (which is a known issue (#99)).

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readxl_0.1.1.9000

loaded via a namespace (and not attached):
[1] clipr_0.3.2    assertthat_0.1 tools_3.3.1    tibble_1.2     Rcpp_0.12.10   knitr_1.15.1

**Comment by jennybc** [comment]
I see the problem and can fix it. Two questions:

  1. Can I use the example you posted as a test sheet in the package? Obviously it represents an edge case and, once I fix it, this will help make sure it stays fixed.
  2. Do you know the name of the software that made this file? I like to keep track of such things.

**Comment by ea-guerette** [comment]
Hi,

Thank you!


1. Yes, you can use it as a test sheet.

2. I do not know, but I can probably find out.


Cheers,


Elise

________________________________

**Comment by jennybc** [comment]
@ea-guerette You should be able to read this file if you install from a pull request I just made:

```r
devtools::install_github("tidyverse/readxl#312")
```

Something along these lines will be merged into master before too long, but this should work for now. I'd be interested to know either way, in fact.

**Comment by ea-guerette** [comment]
Hi,

It worked!

Thank you so much for the super quick help with this.

It's very much appreciated!


Elise

________________________________

**Comment by jzadra** [comment]
Hi,

I'm still encountering this issue.  the pull request for `devtools::install_github("tidyverse/readxl#312") ` doesn't seem to exist.  I pulled from the master, and now have 1.0.0.9000 but am still having the issue.

Thanks

**Comment by jennybc** [comment]
@jzadra The fix discussed above went into the CRAN release.

So if you're having trouble with that (or something even more recent), please open a new issue and if at all possible provide the problematic file. With these third party xls files, it's almost impossible to figure out the problem without an example.

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box. `.xlsx` is a supported file type. You'll need to zip or gzip `.xls` so it appears as `.zip` or `.gz`.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by jzadra** [comment]
Hi,

The full data file I have contains PII, so I cannot share it.  Unfortunately, when I make a change and save the file (in an attempt to anonymize), the problem does not persist. This is true even if I just save it as a new file name without making any changes.

Please let me know if you have other suggestions for how I could provide a reprex or information that would be helpful given this issue, and I will open a new issue.  Otherwise I will just deal with opening and re-saving files whenever I get them from this source (which was, BTW, a HMIS system [Homeless Information Management System]).

**Comment by jennybc** [comment]
Yeah, I'm afraid I have no idea where to look with just the info that some 3rd party `.xls` doesn't import correctly. Maybe you could get the vendor to produce a test file with no PII?
