### ISSUE TITLE
Too many rows (blank rows) extracted

### ISSUE THREAD

**Issue by Orblux** [tidyverse/readxl#311]
Hello,

I have used readxl packages without issues until today with many different structurered excel files.
But, when I try to extract the datas from the file attached, I get a structure with 273 observations/rows (so 271 blank lines at the end of the structure). Meanwhile, the number of variables/columns is correct...

I copy here the code that I use:
`Dataset_train <- 
    readxl::read_excel("Datas - v0.1.xlsx", sheet="Datas", 
    col_names =TRUE, col_types=NULL, na="")`
[Datas - v0.1.xlsx](https://github.com/tidyverse/readxl/files/883205/Datas.-.v0.1.xlsx)

For information, I used the latest (non-development) version of readxl.

Anyway, thank you very much for providing such an useful tool!

Regards.

**Comment by jennybc** [comment]
This is already fixed in the development version, which you can install from GitHub using instructions in the README. A CRAN release is coming soon.
