### ISSUE TITLE
Document writing to csv immediately after `read_excel()`

### ISSUE THREAD

**Issue by jennybc** [tidyverse/readxl#323]
Re: reproducibility.

One of the reasons I think packages like readxl are important is because they allow reading of data as you found it ... even if that's in xls or xlsx.

But I also like to make my workflows transparent, future proof, and version controlled. So I usually save spreadsheet data to plain text form at the same time as I read it into R, just to have a non-binary, plain text snapshot of what the sheet looked like at that moment.

Should `read_excel()` have an argument that applies `readr::write_delim()` to the tibble its returning? Or should I just put sample user code in a vignette or article about using readxl in workflows? The example currently in `excel_sheets()` about [reading all the worksheets at once](http://readxl.tidyverse.org/reference/excel_sheets.html) is another good candidate. And the combination would be great: snapshot a multi-worksheet workbook in a series of csv files.

cc @hadley

**Comment by jennybc** [comment]
Another idea for a workflow vignette or article: keeping two different tables on two different sheets and then doing a join. E.g., repeated measurements on individuals in a data sheet and then unchanging variables measured on the individuals in another.

**Comment by jennybc** [comment]
The "dump to csv" feature would be cool in combination with `range` or other geometry-controlling arguments, because it helps people save a clean csv of a data rectangle. Excel's csv export operates only at the level of an entire worksheet.

**Comment by hadley** [comment]
It feels like this should be advice not built in - write functions should invisibly return their input so it's easier enough to add to the chain.

**Comment by jennybc** [comment]
Fair enough. I'll use this as inspiration for some sort of documentation.
