### ISSUE TITLE
DEFINEDNAME appears when special characters appear

### ISSUE THREAD

**Issue by RickPack** [tidyverse/readxl#324]
[DEFINEDNAME_error.xlsx](https://github.com/tidyverse/readxl/files/904014/DEFINEDNAME_error.xlsx)
Reminiscent of issue #82 , I see DEFINEDNAME warnings when I attempt to read a file (_attached_ but in .xlsx format because Github required it) with a simple:
`labcds  <- read_excel(DEFINEDNAME_error.xlsx)`

DEFINEDNAME: 21 00 00 01 0b 00 00 00 01 00 00 00 00 00 00 0d 3b 00 00 00 00 06 00 00 00 01 00 
DEFINEDNAME: 21 00 00 01 0b 00 00 00 01 00 00 00 00 00 00 0d 3b 00 00 00 00 06 00 00 00 01 00 
DEFINEDNAME: 21 00 00 01 0b 00 00 00 01 00 00 00 00 00 00 0d 3b 00 00 00 00 06 00 00 00 01 00 
DEFINEDNAME: 21 00 00 01 0b 00 00 00 01 00 00 00 00 00 00 0d 3b 00 00 00 00 06 00 00 00 01 00 

I suppose the problem lies in the special characters that appear in the first column such as a colon sign, @ sign, and number sign.

**Comment by jennybc** [comment]
Are you using the development version from GitHub? This should be fixed in that.

I assume you're using the CRAN version, if you're still getting this chatter.

**Comment by RickPack** [comment]
Thank you, Jenny. Installing the development version of readxl solved the problem.

Possibly of interest to others: I could not get past the proxy on my work network so I downloaded the .zip file from https://github.com/tidyverse/readxl, unzipped the readxl-master subfolder inside of which there were files like .gitignore, and finally ran install_local pointing to that extracted folder:
`install_local('C:/Users/Packr1/Downloads/readxl-master', force = TRUE)`
