### ISSUE TITLE
readxl error

### ISSUE THREAD

**Issue by dennisfisher** [tidyverse/readxl#327]
Hadley asked me to forward this to you.  

The attached file yields an error with readxl — the error is triggered by the second column having no entries in the initial rows.   The workaround was to enter something into an early row in that column — but hopefully that can be avoided.
[ForHadley.xlsx](https://github.com/tidyverse/readxl/files/907130/ForHadley.xlsx)

**Comment by jennybc** [comment]
I don't get an error reading this file with the current GitHub version.

``` r
library(readxl)
(df <- read_excel("~/Downloads/ForHadley.xlsx"))
#> # A tibble: 1,892 × 2
#>    SUBJID COMMENT
#>     <chr>   <chr>
#> 1    1101    <NA>
#> 2    1101    <NA>
#> 3    1101    <NA>
#> 4    1101    <NA>
#> 5    1101    <NA>
#> 6    1101    <NA>
#> 7    1101    <NA>
#> 8    1101    <NA>
#> 9    1101    <NA>
#> 10   1101    <NA>
#> # ... with 1,882 more rows
tail(df)
#> # A tibble: 6 × 2
#>   SUBJID               COMMENT
#>    <chr>                 <chr>
#> 1   1908 Low Internal Standard
#> 2   1908 Low Internal Standard
#> 3   1908 Low Internal Standard
#> 4   1908 Low Internal Standard
#> 5   1908 Low Internal Standard
#> 6   1908 Low Internal Standard
```

If you're using the CRAN version, maybe you see a warnings about finding character data in a numeric column? I believe this is fixed now and there is even a new argument `n_max` that gives you control over the number of rows used for column type guessing.
