### ISSUE TITLE
read .xls error

### ISSUE THREAD

**Issue by Lu2017** [tidyverse/readxl#333]
hi , when I use read_excel() to read an .xls file.   The dataframe in the file such as  data.frame(c("姓名",123),c(1,3)),  the col of containing "姓名" is removed. How to solve this problem ?

**Comment by jennybc** [comment]
I am not able to follow your question and I would need to see an example.

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box. *Sadly, GitHub only supports this for xlsx, not xls.*
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by Lu2017** [comment]
@jennybc 
The R code is as follows:
readxl::read_excel("datatemp.xls")
system: CentOS release 6.7 (Final) 64Bit
![open](https://cloud.githubusercontent.com/assets/25289005/25034957/01c85b90-211d-11e7-98e9-d28115bf7a27.png)
[datatemp.xls.gz](https://github.com/tidyverse/readxl/files/921556/datatemp.xls.gz)

**Comment by jennybc** [comment]
It imports fine for me. Are you running the development version of readxl, installed from GitHub?

``` r
readxl::read_excel("~/Downloads/datatemp.xls")
#> # A tibble: 1 × 3
#>    col1           col2       col3
#>   <chr>          <chr>      <chr>
#> 1  姓名 12345512123456 1234568888
```

**Comment by Lu2017** [comment]
@jennybc  thank you , the problem that can not read .xls is sovled by  using the development version .But there are other problems. I saved the same file by .xls and xlsx, and read by "readxl::read_excel" , it imports flase content about the .xls file  . The code and data examples  is as follows:

[data.tar.gz](https://github.com/tidyverse/readxl/files/924896/data.tar.gz)
![diff_info](https://cloud.githubusercontent.com/assets/25289005/25078174/44d9ba62-2363-11e7-8c36-684e6a2298c1.png)

**Comment by jennybc** [comment]
OK I can reproduce this. I doubt it's a coincidence that reads from the string table wraparound at 127 =  2^7 - 1. I can't reproduce it if I make a similar sheet w/o CJK characters, so I suspect that plays a role here. Thanks for these examples.

In future, it would be really great if you posted code and not a screenshot. That way I don't have to retype everything from an image.

**Comment by Lu2017** [comment]
@jennybc thank you, the next time I will post code instead of  the  screenshot.

**Comment by Lu2017** [comment]
@jennybc  The last problem is solved, but there is another problem. 
If sheet in excel have a numerical value like 18726233581,then read_excel display -2147483648(mean min int value,int signed between -2147483648 and 2147483647)
The data example is as follows:
[data.tar.gz](https://github.com/tidyverse/readxl/files/929254/data.tar.gz)

**Comment by jennybc** [comment]
@Lu2017 OK I will open an issue about that (or you can). You can get the correct number for that cell if you read the column in as numeric. The problem is that numbers this large are not currently anticipated in the routine that converts numbers to character (which only gets called in xls).

**Comment by mcastagnaa** [comment]
Unfortunately, in finance, those large numbers are quite common. The two screenshots below gives you a working example.
 
Naming the type for each column is the solution as you said but, referring to the screenshots below, it would be a bit of a pain getting row 9 right: they would be NA for those columns specified as _numeric_ 
and in order to get them, I need first to read the file without specifying the types first, collect line 9 and then read it with the types in order to get the numbers rights and fill in row 9 from above. Hopefully, the amendment to the bug will solve this.

![capture1](https://cloud.githubusercontent.com/assets/4532767/25304761/884f33de-2765-11e7-8082-8909b8b588a9.PNG)
![capture2](https://cloud.githubusercontent.com/assets/4532767/25304763/8c1b7f22-2765-11e7-9da1-0cfe1ef306ab.PNG)
