### ISSUE TITLE
.xlsx colnames error

### ISSUE THREAD

**Issue by muscatelle** [tidyverse/readxl#334]
Reading .xlsx files with colnames=FALSE results in column names X0....Xn, rather than X1...Xn as specified. 
I've verified this behaviour is consistent by testing .xlsx files from a number of sources
.xls files behave as documented

Haven't had much luck with reprex I'm afraid but test code and file are attached.

[readxl_xlsx_colnames_error.txt](https://github.com/tidyverse/readxl/files/921715/readxl_xlsx_colnames_error.txt)

[testLoadWorkbook.xlsx](https://github.com/tidyverse/readxl/files/921700/testLoadWorkbook.xlsx)

**Comment by jennybc** [comment]
This has been fixed in the development version, which you can install from this GitHub repo.

```r
# install.packages("devtools")
devtools::install_github("tidyverse/readxl")
```
