### ISSUE TITLE
na parameter

### ISSUE THREAD

**Issue by msgoussi** [tidyverse/readxl#348]
I downloaded the file below from IMF and tried several packages to read
http://www.imf.org/external/pubs/ft/weo/2017/01/weodata/WEOApr2017all.xls
I tried read_excel("IMF_WEO_Countries.xls") and I get several warnings
In xls_cols(path, sheet, col_names = col_names, col_types = col_types,  ... :
  Expecting numeric in [236, 44] got `n/a`
if i read_excel("IMF_WEO_Countries.xls", na= "/na) 
then I get other warnings
In xls_cols(path, sheet, col_names = col_names, col_types = col_types,  ... :
  Expecting numeric in [109, 11] got `--`

So my question is: can you edit  **na parameter**  to take more than one values, such as 
na = c( "" ,  "-",  "_", "..", "...",  "--",  "n/a", "n.a." , "#VALUE!")

Also what is the best way  that names of columns starts with x
such as x1980 instead of "1981.000000"  
Thanks

**Comment by jennybc** [comment]
The new version of readxl, which just came out on CRAN, does accept multiple values for `na`. Depending on your platform, the binary might not have been built yet, but will be there very soon.

Re: column names. In `read_excel()` you either take them from the sheet or suppress them or accept default names. There's no way to prepend names from the sheet with `x`. You'll need to do that after import.
