### ISSUE TITLE
Don’t trim whitespace by default

### ISSUE THREAD

**Issue by huftis** [tidyverse/readxl#349]
This is a request for changing the default `trim_ws` argument from `TRUE` to `FALSE`. Having the default being TRUE leads to *data loss by default*, i.e. the data you get when using `read_excel()` on an Excel is *not* the data that is stored in the file. Having the software trying to be ‘clever’ in second-guessing the content of the data seems to be bad practice. I think having `read_excel()` *not* trim whitespace follows the ‘principle of least surprise’ for users.

I accidently discovered this problem after updating `readxl` to the latest version and an R script I had been using started to produce incorrect result (and it turned out to be caused by stripping whitespace from variable names). Of course, changing the default now will affect people depending on the *new* behaviour, but I think it is better in the long run.

**Comment by jennybc** [comment]
I'm sorry the change caused your previously-working script to produce incorrect results 😔. Just to confirm -- you did NOT have internal whitespace stripped from variable name, right? But rather, your names have leading or trailing whitespace and your R code reflected that?

It's not a simple choice, but I still think a default of `TRUE` does the most good for the most people. Even working on the feature and tests, I was reminded how hard it is to detect this whitespace. It can also be hard to hold onto, because Excel sometimes strips it when you visit the cell. I had to rely heavily on formulas in the test sheets. I think it's rare that someone wants `female` and `female ` (← note the trailing space!) to import as two different values.

Finally, the function I am most trying to match is `readr::read_csv()` and `trim_ws = TRUE` is the default there as well. So `read_excel()` gives the same result as "open excel, save as ... csv, read with `readr::read_csv()`".

**Comment by sanjmeh** [comment]
I think the trim_ws=T is not trimming all white spaces. At least not for me with an invocation like this:

```read_excel(path = fileb,sheet = 1,range = cell_limits(c(2,1),c(NA,2)), trim_ws = T, col_names = c("location","district")) %>% as.data.table %>% .[grepl("^\\s.+",district),district] %>% unique()```

the above gives a non zero length output. All the strings that are output have **one leading white space** . How can this happen?

**Comment by jennybc** [comment]
@sanjmeh I'm about to insert standard advice on giving a reprex. If you want to pursue this, please open a new issue with a Sheet we can use to replicate the problem for ourselves. Thanks.

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box. `.xlsx` is a supported file type. You'll need to zip or gzip `.xls` so it appears as `.zip` or `.gz`.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by sanjmeh** [comment]
Here's a reprex.
Consider the sample.xlsx file (zipped and attached).
[zsample.zip](https://github.com/tidyverse/readxl/files/2161831/zsample.zip)

```library(wrapr)
library(magrittr)
library(data.table)
library(readxl)
```

Load the data using following:

```read_excel("sample.xlsx",sheet = 1,trim_ws = T) -> x2```

I prefer data.table format.
```x2  %<>%  as.data.table() ```

Clean the headers:
```names(x2) <- wrapr::qc(loc,distr,d1,d2,d3,distt,total)```
If you donot want to use wrapr pls use quotes in the character arr.

Now you can clearly see leading white spaces are persisting in the data:
```x2[grepl("^\\s",distt)]```

And trailing whitespaces also existing,
```x2[grepl("\\s$",distt)]```


And by the way the reprex() does not work on my mac. There's an open issue on rstudio support here
https://community.rstudio.com/t/reprex-error-no-input-provided-and-clipboard-is-not-available/5197

**Comment by batpigandme** [comment]
> And by the way the reprex() does not work on my mac. There's an open issue on rstudio support here
https://community.rstudio.com/t/reprex-error-no-input-provided-and-clipboard-is-not-available/5197
 
That's not an open issue. The solution chosen was the solution at the time. 

reprex is back on CRAN, and there shouldn't be an issue. If no content is selected, then, you may not be  using it correctly. Are you selecting war you want to run, and using reprex from selection? If you don't have clipboard access, you'll need to specify in and out files. 

If you run into problems with access to your clipboard, you can specify an outfile for the reprex, and then copy and paste (or drag and drop) the contents here.

```r
reprex::reprex(input = "fruits_stringdist.R", outfile = "fruits_stringdist.md")
```
