### ISSUE TITLE
Add support for .xlw

### ISSUE THREAD

**Issue by hrecht** [tidyverse/readxl#350]
While read_excel works on .xlsm (wonderful!!), it doesn't appear to support the legacy .xlw. It would be incredibly helpful to support that format too if possible, since some government datasets are still .xlw only.

```R
> download.file("https://www.fhwa.dot.gov/ohim/summary95/mf201.xlw", destfile="mf201.xlw")
> temp <- read_xlsx("mf201.xlw", range="A9:H85", col_names = F)
Error in read_fun(path = path, sheet = sheet, limits = limits, shim = shim,  : 
  zip file 'mf201.xlw' cannot be opened
```

There are a bunch of .xlw datasets here that would be good for testing: https://www.fhwa.dot.gov/ohim/summary95/section4.html

**Comment by MichaelChirico** [comment]
<img width="425" alt="screen shot 2018-07-20 at 9 51 44 am" src="https://user-images.githubusercontent.com/7606389/42979003-8c98f8f0-8c02-11e8-9100-db6592d964da.png">
Excel tells me this when trying to open the file in your example. Perhaps the file itself is corrupted?

**Comment by jennybc** [comment]
Realistically, we would not implement his directly ourselves and it's clear that libxls is also not heading this direction (https://github.com/evanmiller/libxls/issues/33#issuecomment-448448210). So this is a non-starter unless someone identifies a well-maintained, wrappable library that reads .xlw.
