### ISSUE TITLE
Feature request: seriously need the argument evuivalent 'as.is = TRUE'

### ISSUE THREAD

**Issue by shoebodh** [tidyverse/readxl#354]
This is the issue I have had with read_excel function: Reading sheets that have different column types and I don't want to specify the column type in advance. But the function guesses the col_type automatically and gets it wrong or NA (for the date or datetime columns). 
I think having the argument as_is = TRUE and getting anything that is not numeric as character would be really useful. I understand the purpose of  automatic setting col_types but there are l instances when as_is = T becomes important.  
 Reading a number of field/sheets in a loop or apply type function, it's really tedious to set each col_types for each sheet. And if date column is in ambiguous format or something it gives NA.

**Comment by jennybc** [comment]
You can already set column type to a single default, i.e. `col_types = "text"`, and do the coercion yourself. Or `col_types = "list"` would give even greater control, but sign you up for quite a lot of work.

I don't see how `as.is = TRUE` would help in the case of Excel, which is different than column typing from csv. Please read the [Cell and Column Types](http://readxl.tidyverse.org/articles/cell-and-column-types.html) vignette for more details. Specifically "getting anything that is not numeric as character" is probably not implementable in the way you hope.

Exactly what sort of type guesses are causing trouble? From what to what?

**Comment by jennybc** [comment]
Closing due to lack of response.
