### ISSUE TITLE
Update xls library

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/readxl#356]
I've received a notification that the upstream equivalent of #82 finally has been fixed. It might be worthwhile to check upstream updates.

**Comment by jennybc** [comment]
I did a comprehensive diff of our embedded copy of libxls and svn "master" before the release (#329). We are current. In fact, there are more changes beyond #82 that should probably go upstream (e.g. https://sourceforge.net/p/libxls/patches/13/).
