### ISSUE TITLE
Apply upstream libxls fixes

### ISSUE THREAD

**Issue by tbeu** [tidyverse/readxl#358]
@jennybc FYI, please note that https://github.com/svn2github/libxls currently is not synchronized with svn://svn.code.sf.net/p/libxls/code/trunk, thus you need to pull the latest upstream fixes from https://sourceforge.net/p/libxls/code/.

**Comment by jennybc** [comment]
Thanks @tbeu. Is this a general heads up or do you know of specific fixes in svn but not on github?

I was regarding the github mirror as reliable 😔.

**Comment by tbeu** [comment]
I pinged the author of svn2github. Sdrvice is now resumed.

**Comment by tbeu** [comment]
@jennybc Can you please investigate on your patch for the upstream repo of [libxls](https://sourceforge.net/p/libxls/patches/13/) such that I can incorporate your changes there. Thanks a lot.

**Comment by jennybc** [comment]
@tbeu Sorry, what exactly do you need me to do? I'm happy to help, just need more specifics.

**Comment by tbeu** [comment]
What I would need is a test case (preferable in C language) where current libxls HEAD fails, but works if your [T13.patch](https://sourceforge.net/p/libxls/patches/_discuss/thread/43d09e8c/0864/attachment/T13.patch) is applied.

**Comment by jennybc** [comment]
OK I will see what I can do.

I have only worked with libxls via our embedded version.

I have contemplated doing this: I know there's way to build a command line tool using libxls to go from xls to csv. If I do that, I can find combinations of test file and libxls version that work / don't work.

Does this sound productive?

**Comment by tbeu** [comment]
> Does this sound productive?

Indeed, that would be of help. Thank you.

**Comment by tbeu** [comment]
Any news?

**Comment by jennybc** [comment]
FYI I am going to work on this this week @tbeu.

**Comment by tbeu** [comment]
OK, I was offline anyway.

**Comment by jennybc** [comment]
@tbeu I have made the command line tool and can reproduce some of the problems that led us to patch. So I will be able to provide xls samples and demonstrate how xls2csv behaves before/after a patch.

**Comment by tbeu** [comment]
Thank you. This will definitely be helpful.

**Comment by tbeu** [comment]
What is your schedule for the test? I actually was thinking to apply [T13.patch](https://sourceforge.net/p/libxls/patches/_discuss/thread/43d09e8c/0864/attachment/T13.patch) pretty soon (after I got envolved with libxls, got the push rights and fixed some other bugs) but it takes quite some weeks already. ❓ 😕

**Comment by jennybc** [comment]
I got home last night from 2.5 weeks away. I will make a PR on my own fork today or tomorrow re: this specific patch (I think 1 or 2 other are also related) and include the `.xls` files that demo the problem and effect of the patch(es).

**Comment by tbeu** [comment]
@jennybc Did you make any progress with the PR?

**Comment by tbeu** [comment]
Any news?

**Comment by tbeu** [comment]
Friendly ping

**Comment by jennybc** [comment]
Hi @tbeu. I hear you and thanks for pinging and being friendly 🙂. I'm still here and still want to provide this info to you in a useful way! Will try to do so next week.

**Comment by jennybc** [comment]
@tbeu Has development of libxls moved to GitHub? If not, is that on the horizon?

**Comment by tbeu** [comment]
@jennybc No, development has not yet moved (and I do not want to start with it, though I'd prefer to have it GitHub).

**Comment by jennybc** [comment]
Increased urgency re: pulling upstream fixes and stating our fixes as PRs to upstream:

https://www.scmagazineuk.com/windows-mac-and-linux-all-at-risk-from-flaws-in-excel-file-reader-library/article/708307/

**Comment by tbeu** [comment]
The latest commits to libxls introdude the `exit()` function al lot. This is inappropriate coding since the entire application, R, will be closed then.

**Comment by tbeu** [comment]
I created a [discussion](https://sourceforge.net/p/libxls/discussion/294118/thread/285aaf18/) issue in the upstream repo.

**Comment by jennybc** [comment]
@tbeu So you're saying I should not blindly pull all upstream changes then / yet? You believe they need to be implemented differently and/or in sequential, issue-specific units?

**Comment by tbeu** [comment]
Yes, that is what I am saying. Same reason I did not pull these latest commits to my own fork. Let's see what the upstream dev replies.
