### ISSUE TITLE
read_xlsx not retrieving current computed values from formula cells

### ISSUE THREAD

**Issue by sz-cgt** [tidyverse/readxl#359]
In the xlsx format (not sure about xls), cells with formulas in them also have the current value of the formula saved in the xml.

However, readxl is ignoring the calculated value and returning NA instead.  Is there a reason for that?

**Comment by sz-cgt** [comment]
close #359

Apparently I'm confused.

**Comment by jennybc** [comment]
It would be possible to retrieve formulas, but I think that's outside the scope of readxl. Something like that would probably happen in a separate package and there are already others that provide this functionality.

**Comment by sz-cgt** [comment]
It wasn’t the formulas I was looking for.  It was their results, which readxl is already retrieving.

Not sure why I thought it wasn’t.  I must have screwed something up.
