### ISSUE TITLE
column type conversion warnings can be overwhelming

### ISSUE THREAD

**Issue by heseber** [tidyverse/readxl#361]
Sometimes I come across very large Excel files (e.g., 35,000 rows, 100 columns) where numeric values are stored in Excel as "text" cells. If readxl guesses that these are in fact numeric columns or if the column type is specified explicitly to be numeric, readxl spits out tons of warning messages about type conversions. Reading the excel file takes virtually forever if the number of rows is larger than just a couple of thousands, and it also seems to bring RStudio to its limits. If reading the file is interrupted, there seems to be a memory leak because after a couple of failed and interrupted attempts the R session in RStudio gets incredibly slow. It does not help to add "suppressWarnings" and "suppressMessages". If the col_types are defined explicitly to be in line with the cell types defined in the Excel file, the readxl call returns after reasonable time and converting the columns of the data frame afterwords is also quick:

```
df <- read_excel(inputFile, col_types = "text")
numericCols <- c(17, 23, 24, 25 + 2*(0:18), 76)
df[, dnaNumericCols] <- sapply(dna[, dnaNumericCols], as.numeric)
```

This is a real issue for large files because readxl can only be used after making sure that the col_types are specified to be exactly in sync with the cell types in the Excel file. This is painful if the number of columns is in the hundreds.

**Comment by jennybc** [comment]
Thanks for this report. Yes the messages are originating in the C++ code, so apparently are not suppressed via `suppressMessages()` et al.

I already have this idea on my radar: don't emit coercion warnings if a column type has been set specifically. Or perhaps we just need a general way to suppress the warnings.

As for the code snippet, another nice way to implement your current workaround would be with `purrr::modify_at()`.

``` r
library(readxl)
library(purrr)
(idf <- read_excel(readxl_example("datasets.xlsx"), col_types = "text"))
#> # A tibble: 150 × 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <chr>       <chr>        <chr>       <chr>   <chr>
#>  1          5.1         3.5          1.4         0.2  setosa
#>  2          4.9           3          1.4         0.2  setosa
#>  3          4.7         3.2          1.3         0.2  setosa
#>  4          4.6         3.1          1.5         0.2  setosa
#>  5            5         3.6          1.4         0.2  setosa
#>  6          5.4         3.9          1.7         0.4  setosa
#>  7          4.6         3.4          1.4         0.3  setosa
#>  8            5         3.4          1.5         0.2  setosa
#>  9          4.4         2.9          1.4         0.2  setosa
#> 10          4.9         3.1          1.5         0.1  setosa
#> # ... with 140 more rows
idf %>% 
  modify_at(1:4, as.numeric)
#> # A tibble: 150 × 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl>   <chr>
#>  1          5.1         3.5          1.4         0.2  setosa
#>  2          4.9         3.0          1.4         0.2  setosa
#>  3          4.7         3.2          1.3         0.2  setosa
#>  4          4.6         3.1          1.5         0.2  setosa
#>  5          5.0         3.6          1.4         0.2  setosa
#>  6          5.4         3.9          1.7         0.4  setosa
#>  7          4.6         3.4          1.4         0.3  setosa
#>  8          5.0         3.4          1.5         0.2  setosa
#>  9          4.4         2.9          1.4         0.2  setosa
#> 10          4.9         3.1          1.5         0.1  setosa
#> # ... with 140 more rows
```

**Comment by stla** [comment]
@heseber 
I have a function which converts character columns of a dataframe to numeric columns when this is safe:
```
> dat <- data.frame(x=1:4,
+                   y=c("a","b","c","d"),
+                   z=c("1", "1.4", "-3", "   0"))
> numdat <- Numerize.df(dat)
Warning message:
Column `y` is not numerizable. 
> str(numdat)
'data.frame':	4 obs. of  3 variables:
 $ x: int  1 2 3 4
 $ y: Factor w/ 4 levels "a","b","c","d": 1 2 3 4
 $ z: num  1 1.4 -3 0
 - attr(*, "unnumerizable")= chr "y"
```
I can share it if it can help. Then you could read your Excel files with `col_types="text"` and apply this function `Numerize.df`. I don't know whether this would be more efficient by my function is rather fast with a big dataframe:
```
> dat <- as.data.frame(matrix("1", nrow=35000, ncol=100))
> system.time(numdat <- Numerize.df(dat))
   user  system elapsed 
   1.75    0.18    1.92 
```

**Comment by heseber** [comment]
@stla 
The workaround you suggest requires that I know in advance whether a column in an Excel file that is supposed to be numeric is actually a numeric column in Excel or whether it is text. This means using read_excel would only be safe if I check in advance the types in the Excel fail. If I make a mistake, I get these tons of warning messages that slow down the reading, which is an issue especially for large tables with thousands of rows. If I interrupt this process in RStudio, there seems to be a memory leak because after a couple of such attempts nothing works anymore and I have to restart the R session and the RStudio session.
Has there been any progress regarding this issue? I wanted to switch from xlsx to read.xl because for xlsx I sometimes get Java out of memory exceptions, but the issues I described in this bug report prevent me from switching. Thanks!

**Comment by jennybc** [comment]
I haven't fixed this but it should not be too hard and will happen on the next pass. Realistically, that cannot start until after early February.

If someone wants, they could also do a quick-and-dirty temporary fix (i.e. comment some warnings out) and make a PR against this issue, for people to install and use until I fix it properly.

**Comment by hadley** [comment]
Are you sure you don't have `option(warn = 1)` set?

**Comment by heseber** [comment]
It's been a while since I have reported this issue, and I switched to openxlsx a while ago. But I am pretty sure that I did not set `option(warn = 1)`.

**Comment by jennybc** [comment]
Based on current readxl, I don't see anything that needs to be done here.

Yes, it's true that you want to attend to your `warn` option!

For posterity, here are some docs and comments:

> `warn`:
> sets the handling of warning messages. If `warn` is negative all warnings are ignored. If `warn` is zero (the default) warnings are stored until the top–level function returns. If 10 or fewer warnings were signalled they will be printed otherwise a message saying how many were signalled. An object called `last.warning` is created and can be printed through the function warnings. If `warn` is one, warnings are printed as they occur. If `warn` is two or larger all warnings are turned into errors.

So `options(warn = 0)` is the default and works well with readxl.

`options(warn = 1)` can easily result in an overwhelming amount of messaging, in a large sheet with lots of coercions.

If you like to have `warn = 1` in general, then use a local method to suppress the warnings, e.g.:

```
withr::with_options(list(warn = 0), read_excel("investigations/Voice_Master.xls"))
## or
suppressWarnings(read_excel("investigations/Voice_Master.xls"))
```

Otherwise, I believe #307 "Provide diagnostics a la 'problems' from readr" captures possible enhancements re: reporting around mismatch of cell and column type.

**Comment by heseber** [comment]
As I wrote, I am pretty sure that I did not change the warnings level from the default because I never did this so far. Anyway, I may give it a try when I again have to work with a large file for which type conversions are necessary.
