### ISSUE TITLE
skip = -1 causes hard crash

### ISSUE THREAD

**Issue by jebyrnes** [tidyverse/readxl#363]
This was an accident, but instead of skip=1 I accidentally put in -1 the other day and it caused a hard crash of rstudio. This was repeatable and worked even with a fresh session. I know this is a bad value to supply, but, um, the consequences seem a bit....problematic? Might want to keep the user from trying that lest they love their work!

**Comment by Ironholds** [comment]
This now appears fixed?

```
> datasets <- readxl_example("datasets.xls")
> read_excel(datasets, skip = -1)
Error: `skip` must be a positive integer
```

**Comment by jennybc** [comment]
Yes, I agree this seems to be ok in the CRAN version. Closing @jebyrnes. Please open a new issue with reprex and more details if you still see this. Maybe you had a stale development version installed?
