### ISSUE TITLE
Behaviour of read_excel na parameter

### ISSUE THREAD

**Issue by m-macaskill** [tidyverse/readxl#366]
In the documentation, the `na` parameter of the read_excel function is described as a "Character vector of strings to use for missing values."

This implies that it should be possible to use something like `na = c('NA', 'NA1', 'NA2')` to specify a vector of several strings that represent missing values. Attempting to do this, however, yields:
`Error: expecting a single value`

Examples which include the `na` parameter  show only a single string literal. The documentation should either be altered to something like "A string to use for missing values." to reflect actual behaviour, or (preferably) the code changed to actually allow several missing value strings to be specified.

**Comment by jennybc** [comment]
I am able to specify your `na` vector to the `na` argument (it has no affect on the iris data, but I don't get an error). Are you sure you're using the most recent release of readxl?

``` r
library(readxl)
read_excel(readxl_example("datasets.xlsx"), na = c('NA', 'NA1', 'NA2'))
#> # A tibble: 150 x 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl>   <chr>
#>  1          5.1         3.5          1.4         0.2  setosa
#>  2          4.9         3.0          1.4         0.2  setosa
#>  3          4.7         3.2          1.3         0.2  setosa
#>  4          4.6         3.1          1.5         0.2  setosa
#>  5          5.0         3.6          1.4         0.2  setosa
#>  6          5.4         3.9          1.7         0.4  setosa
#>  7          4.6         3.4          1.4         0.3  setosa
#>  8          5.0         3.4          1.5         0.2  setosa
#>  9          4.4         2.9          1.4         0.2  setosa
#> 10          4.9         3.1          1.5         0.1  setosa
#> # ... with 140 more rows
```

**Comment by m-macaskill** [comment]
Jenny, thanks for your remarkably quick response. Apologies, but an update did indeed resolve the issue.
