### ISSUE TITLE
Import of Excel version 4 files fails

### ISSUE THREAD

**Issue by robbriers** [tidyverse/readxl#368]
Trying to read in old Excel version 4 workbooks raises an error. The following example has a single sheet within the workbook. Either using the below or specifying the sheet explicitly both fail.

`fails<-read_xls("15-PWLL.XLS")`

Error message:
Not an excel file
Error in sheets_fun(path) : Failed to open 15-PWLL.XLS

File specified can be found [here](https://github.com/robbriers/readxl_fail/raw/master/15-PWLL.XLS)

**Comment by jennybc** [comment]
The [libxls library](http://libxls.sourceforge.net), which readxl wraps, can read files starting with Excel 97 only.
