### ISSUE TITLE
Unexpected result trying to import an online excel file using Readxl --- Error: Missing file extension.

### ISSUE THREAD

**Issue by hughmarera** [tidyverse/readxl#371]
I have just noticed a difference between readxl and openxlsx when reading an online excel spreadsheet. openxlsx appears to read the file with no error but readxl gives the following "Error: Missing file extension." Is this feature of "readxl" or perhaps a bug in "openxlsx"? The code i ran is below

```
example1 <- openxlsx::read.xlsx("http://www.education.gov.za/LinkClick.aspx?fileticket=8CuGlTzTfPY%3d&tabid=466&portalid=0&mid=5913&forcedownload=true")

example2 <- readxl::read_excel("http://www.education.gov.za/LinkClick.aspx?fileticket=8CuGlTzTfPY%3d&tabid=466&portalid=0&mid=5913&forcedownload=true")
```

**Comment by jennybc** [comment]
Related to #342. In the meantime, you can use `read_xls()` and `read_xlsx()` directly, in order to work with extension-less files.

**Comment by jennybc** [comment]
readxl also doesn't read straight from the web, which is #278. So you will likely need to download the file first. If you use RStudio, the helper you get with *File > Import Dataset > From Excel...* will facilitate this and give you a nice code snippet to drop into your script.

**Comment by hughmarera** [comment]
Thank you for the response. I was not aware that readxl does not  have URL support. So, i will consider this closed until the feature has been added to the readxl.
