### ISSUE TITLE
Excel file that cannot be opened with readxl, but can be with Excel

### ISSUE THREAD

**Issue by danielsjf** [tidyverse/readxl#374]
The excel is a public excel file. I have no information on how it is generated.

https://clients.rte-france.com/servlets/IndispoProdServlet?annee=2016 (it's zipped)

When I try to open it with readxl, I get the following error:
```
outages <- readxl::read_excel("X:/.../DonneesIndisponibilitesProduction_2016.xls",
                              sheet = 'DonneesIndisponibilitesProducti')
Not an excel file
Error in sheets_fun(path) : 
  Failed to open X:/.../DonneesIndisponibilitesProduction_2016.xls
```

When I save it from excel manually, it does open with readxl.

**Comment by antaldaniel** [comment]
A similar issue with this file:
```
url <- "https://www.dzs.hr/Hrv_Eng/publication/2015/12-01-04_01_2015.xlsx"
destfile <- "X12_01_04_01_2015.xlsx"
download.file(url, destfile)
t_cols2 = as.character(
  readxl::read_excel(
    path = destfile, 
    sheet = 3,
    range = "C521:CF521", 
    col_names = FALSE
  ))
```
The error message:
> Error in read_fun(path = path, sheet = sheet, limits = limits, shim = shim,  : 
  Evaluation error: error -103 with zipfile in unzGetCurrentFileInfo

However, the file is not zipped, and after opening in Excel, it can be read in. I think there is a problem with the fact that some elements of the file are somehow protected.

**Comment by jcolomb** [comment]
I cannot open the file you mention with excel either, probably something strange with download.file or with the fact that it is https ??

**Comment by jennybc** [comment]
Just to be sure, on Windows it is important to use, e.g., `download.file( ..., mode = 'wb' )`. I haven't dug in to the files above yet, but offer this in case it's an easy solution.

**Comment by antaldaniel** [comment]
@jennybc  Thank you very much.  Indeed it works that way.

**Comment by dannyfraser** [comment]
The issue here is that the file provided by @danielsjf isn't really an Excel file - it's a tab-delimited text file with the .xls extension. Open it with readr::read_tsv instead.

**Comment by cderv** [comment]
@danielsjf For your interest, data are also available by API now at https://data.rte-france.com/home
You will find the same information as in the excel-like file. The awesome aprt is that you won't have to download a new file when you want update - just make a new call to the API.
You can use `httr` package to call the API - Working on an API package for that website, I made `httr` compatible with the special workflow credential grant workflow chosen by RTE.

As @dannyfraser said, I can confirm that the file is not an .xls per-se but a text file with xls extension - a method used (wrongly) a lot to make the text file open directly in Excel after download. I am from RTE so I played a lot with this type of data from https://clients.rte-france.com and its text based file. (you could try opening the xls in an editor (like Notepad++), it will work.

Fill free to contact me if you have further questions.

**Comment by danielsjf** [comment]
@dannyfraser and @cderv, thank you for these tips. I wasn't aware of the text file format. It is indeed confusing as the extension should describe the data, not the tool to open it. I will definitely look into the API as well.

**Comment by jennybc** [comment]
Interesting! I now have a file signature check in readxl, in order to detect xlsx vs xls in the absence of an extension. Perhaps I should do more with that capability and implement it a bit differently. It could be useful for troubleshooting in cases like this.

**Comment by alfredojavier5** [comment]
I'm having the same issue with this .xls file.
It's suppose to be an excel file, but it was generated as a html and saved as xls to open directly in excel.
 
Could anyone tell me how to import it.

Thanks

[example.zip](https://github.com/tidyverse/readxl/files/2006410/example.zip)

**Comment by cderv** [comment]
You seem to already know that file is html not xls. You should read it with {rvest} :package: or {xml2}, not {readxl}

Here some explanation on how to investigate in such case

First, download the file (here in temp folder)

``` r
url <- "https://github.com/tidyverse/readxl/files/2006410/example.zip"
temp_zip <- fs::file_temp(ext = ".zip")
download.file(url, destfile = temp_zip, mode = "wb")
```

extract the file

``` r
temp_dir <- fs::path_temp("dir_example")
unzip(temp_zip, exdir = temp_dir)
(file_to_read <- fs::dir_ls(temp_dir))
#> C:/Users/chris/AppData/Local/Temp/Rtmpc9jym2/dir_example/example.xls
```

You can try reading it as plain text file and see what is coming.

``` r
readr::read_lines(file_to_read, n_max = 20)
#>  [1] "<html LANG=\"es\">"                                                    
#>  [2] "<head>"                                                                
#>  [3] "<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\">"
#>  [4] "<style type=\"text/css\">"                                             
#>  [5] "#tablaReporteVacunaAnimal"                                             
#>  [6] "{"                                                                     
#>  [7] "font-family:\"Trebuchet MS\", Arial, Helvetica, sans-serif;"           
#>  [8] "display: inline-block;"                                                
#>  [9] "width: auto;"                                                          
#> [10] "margin: 0;"                                                            
#> [11] "padding: 0;"                                                           
#> [12] "border-collapse:collapse;"                                             
#> [13] "}"                                                                     
#> [14] "#tablaReporteVacunaAnimal td, #tablaReporteVacunaAnimal th "           
#> [15] "{"                                                                     
#> [16] "font-size:1em;"                                                        
#> [17] "border:1px solid #98bf21;"                                             
#> [18] "padding:3px 7px 2px 7px;"                                              
#> [19] "}"                                                                     
#> [20] "#tablaReporteVacunaAnimal th "
```

ok this is working and we can guess that it is an html file \!\! Parse it as is.

``` r
library(rvest)
#> Le chargement a nécessité le package : xml2
parsed_file <- read_html(file_to_read)
parsed_file
#> {xml_document}
#> <html lang="es">
#> [1] <head>\n<meta http-equiv="Content-Type" content="text/html;charset=u ...
#> [2] <body>\r\n<div id="textoEncabezado">\r\n\tMINISTERIO DE AGRICULTURA, ...
```

As it open in Excel,  I believe you want the table. you could get it this way. I do not know your use case, so obviously you'll need to build on this and adapt.

``` r
tab <- html_node(parsed_file, "table") %>% html_table() %>% tibble::as_tibble()
dplyr::glimpse(tab)
#> Observations: 1,663
#> Variables: 37
#> $ `Número Certificado`                 <dbl> 4.100000e+13, 4.100000e+1...
#> $ `Provincia Emisión`                  <chr> "", "", "", "", "", "", "...
#> $ `Oficina Emisión`                    <chr> "", "", "", "", "", "", "...
#> $ `Operación Origen`                   <chr> "Productor", "Productor",...
#> $ `Provincia Origen`                   <chr> "Carchi", "Carchi", "Carc...
#> $ `Cantón Origen`                      <chr> "Montúfar", "Montúfar", "...
#> $ `Parroquia Origen`                   <chr> "González Suárez", "Gonzá...
#> $ `Sitio Origen`                       <chr> "JOSE VILLOTA", "JOSE VIL...
#> $ `Identificación Operador Origen`     <dbl> 401198635, 401198635, 400...
#> $ `Razón Social Operador Origen`       <chr> "JOSE RODRIGO VILLOTA CRU...
#> $ `Nombre Operador Origen`             <chr> "JOSE RODRIGO VILLOTA CRU...
#> $ `Operación Destino`                  <chr> "Feria de comercializaciò...
#> $ `Provincia Destino`                  <chr> "Imbabura", "Imbabura", "...
#> $ `Cantón Destino`                     <chr> "Ibarra", "Ibarra", "Mont...
#> $ `Parroquia Destino`                  <chr> "San Antonio", "San Anton...
#> $ `Sitio Destino`                      <chr> "FERIA COMERCIAL DE ANIMA...
#> $ `Identificación Operador Destino`    <dbl> 1.060031e+12, 1.060031e+1...
#> $ `Razón Social Operador Destino`      <chr> "EMPRESA PUBLICA MUNICIPA...
#> $ `Nombre Operador Destino`            <chr> "SEGUNDO JUAN GAVILIMA YA...
#> $ `Identificación Usuario Responsable` <chr> "0401198635", "0401198635...
#> $ `Nombre Usuario Responsable`         <chr> "JOSE RODRIGO VILLOTA CRU...
#> $ Producto                             <chr> "Cerdo levante", "Cerda l...
#> $ Cantidad                             <int> 4, 3, 1, 4, 8, 2, 1, 2, 3...
#> $ `Identificación Solicitante`         <dbl> 401198635, 401198635, 400...
#> $ `Nombre Solicitante`                 <chr> "JOSE RODRIGO VILLOTA CRU...
#> $ `Identificación Conductor`           <chr> "0401198635", "0401198635...
#> $ `Nombre Conductor`                   <chr> "josev villota", "josev v...
#> $ `Medio Transporte`                   <chr> "Terrestre", "Terrestre",...
#> $ `Placa de Transporte`                <chr> "IBB-2011", "IBB-2011", "...
#> $ Observación                          <chr> "camioneta", "camioneta",...
#> $ `Fecha Registro`                     <chr> "14-02-2018 03:46:25", "1...
#> $ `Fecha Inicio Vigencia`              <chr> "14-02-2018 04:00", "14-0...
#> $ `Fecha Fin Vigencia`                 <chr> "14-02-2018 18:00", "14-0...
#> $ Estado                               <chr> "caducado", "caducado", "...
#> $ `Fecha Anulación`                    <chr> "", "", "", "", "", "", "...
#> $ `Observación Anulación`              <chr> "", "", "", "", "", "", "...
#> $ `Motivo Anulación`                   <chr> "", "", "", "", "", "", "...
```

About guessing the format of a file, there are solutions.  
If you have to do this kind of things as batch processing, or with more difficult file,
some magic can help you. see [{simplemagick} :package:](https://github.com/hrbrmstr/simplemagic)

``` r
# devtools::install_github("hrbrmstr/simplemagic")
simplemagic::get_content_type(file_to_read)
#> [1] "text/html"
```

you see that judging by the content, it can guess that file is not xls as extension is saying but html ! 
The package name is well chosen it is simple magic.

If I may give an advice for next time, your question is more suited toward https://community.rstudio.com than a github issue. You should post there, you'll get a broader audience there.

Hope it helps.
