### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by afdta** [tidyverse/readxl#375]
Installed using install.packages("readxl").  It appears the package installs OK, but there are a bunch of compiler warnings. For example:

ole.c: In function ‘ole2_open’:
ole.c:297:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(oleh,1,512,ole->file);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
ole.c:412:6: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
      fread(wptr,1,ole->lsector,ole->file);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ole.c: In function ‘read_MSAT’:
ole.c:547:4: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
    fread(wptr,1,ole2->lsector,ole2->file);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

or....

xlstool.c: In function ‘xls_getfcell’:
xlstool.c:643:9: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
         asprintf(&ret,"%s",pWB->sst.string[xlsIntVal(*(DWORD_UA *)label)].str);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
xlstool.c:647:9: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
         asprintf(&ret, "%s", "");
         ^~~~~~~~~~~~~~~~~~~~~~~~

=====

I'm Running R version 3.4.0 on Ubuntu 17.04

**Comment by jennybc** [comment]
These are all originating in the embedded libxls library. I've seen them and ... so has CRAN presumably. They are not actually problematic.
