### ISSUE TITLE
Bug when reading columns with both numeric and text data

### ISSUE THREAD

**Issue by steve4444** [tidyverse/readxl#376]
Create the following `foo.xls` file:

          A
    1 Employee 
    2 9999999999
    3 a111111111

where the cell:

a) A1 can be any text;
b) A2 can be any number not greater 2147483647;
c) A3 can be any text with at leat one letter.

You get:

    read_xls("foo.xls")
    # # A tibble: 2 × 1
    #     Employee
    #        <chr>
    # 1 -2147483648
    # 2  a111111111

Whatever the number in A2 satisfying the condition b) above, it is always reported as -2147483648.   
One can add more numbers satisfying b) and all will be reported as -2147483648.  
If no cell, apart the header, satisfies c), data is correctly reported.  

`read_xls("foo.xls", col_types='text')` does not fix the problem.  One workaround is:

    x=read_xls("foo.xls", col_types='list')
    x[1]=sapply(x, as.character)

I observed the problem with some files possibly exported from a database and I reproduced the problem with LibreOffice.

**Comment by jennybc** [comment]
Yes, this is same issue as #378. I'll close this one.
