### ISSUE TITLE
Support for Excel Named Cells, Ranges, and Tables

### ISSUE THREAD

**Issue by jjcad** [tidyverse/readxl#377]
This would be useful in the case where the dimensions of the range can vary from worksheet to worksheet or workbook to workbook, but the range is still consistently named. Another case is where the range desired is a named Excel Table.

https://support.office.com/en-us/article/Define-and-use-names-in-formulas-4d0f13ac-53b7-422e-afd2-abd7ff379c64

**Comment by jennybc** [comment]
Covered by #317 🙂, where I also speculate on what the future interface might be.
