### ISSUE TITLE
Error in sheets_fun(path) : invalid Unicode point 56141

### ISSUE THREAD

**Issue by willtudorevans** [tidyverse/readxl#380]
Upon upgrading to version 1.0.0 I now get the above error message after typing the command:

    ExcelFile <- read_excel(tempurl, sheet = "DK")

This command worked fine with version 0.1.1. The excel file is `.xlsm` but the same problem occurs if I save it as `.xlsx`. 

I have also have a different `.xlsm` file that the `read_excel` function seems to work fine for. 

Any tips on what I can try to solve this issue?

**Comment by jennybc** [comment]
Can you provide `tempurl`?

**Comment by willtudorevans** [comment]
Hi Jenny,

I've attached the file that's generating the error. I've had to abbreviate it for work confidentiality reasons but the abbreviated version still generates the same error. 

It seems that the PlNm tab is the offending tab (if I remove the error no longer occurs) but I would like to know why so I can work around the issue (rather than remove the tab!). 

[Samplefile8.zip](https://github.com/tidyverse/readxl/files/1230967/Samplefile8.zip)

**Comment by jennybc** [comment]
I can read this sheet with dev readxl. I've recently pulled in many improvements to the embedded libxls, so looks like this is fixed.

``` r
readxl::read_excel("~/Downloads/Samplefile8.xlsm", sheet = "PlNm")
#> # A tibble: 1,101 x 8
#>    Iteration     Actual      Team   Whoscored.ID NmTm  Team__1 PosDK PosMD
#>    <chr>         <chr>       <chr>         <dbl> <lgl> <lgl>   <chr> <lgl>
#>  1 G. Pizarro    Guido Piza… NA          125629. NA    NA      M     NA   
#>  2 Guido Pizarro Guido Piza… NA          125629. NA    NA      M     NA   
#>  3 Georgios Man… Georgios M… Olymp…      302403. NA    NA      M     NA   
#>  4 G. Manthatis  Georgios M… Olymp…      302403. NA    NA      M     NA   
#>  5 Giorgos Mant… Georgios M… Olymp…      302403. NA    NA      M     NA   
#>  6 Thanasis And… Thanasis A… Olymp…      322959. NA    NA      M     NA   
#>  7 T. Androutsos Thanasis A… Olymp…      322959. NA    NA      M     NA   
#>  8 Athanasios A… Thanasis A… Olymp…      322959. NA    NA      M     NA   
#>  9 Aleks Pihler  Aleks Pihl… NA          328887. NA    NA      M     NA   
#> 10 A. Pihler     Aleks Pihl… NA          328887. NA    NA      M     NA   
#> # ... with 1,091 more rows
```

Created on 2018-04-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
