### ISSUE TITLE
Import the desired cells or cell range from .xlsx file into R data.frame using readxl package range

### ISSUE THREAD

**Issue by Deepu298** [tidyverse/readxl#386]
I am using readxl R package to read my .xlsx excel sheet, when I use range function, it shows me an error:
<in read_excel("C:/Data/Digital/Actual.xlsx", range = "D11:E20",  :   
unused argument (range = "D11:E20")>

My code is:
<X <- read_excel("C:/Data/Digital/Actual.xlsx",range="D11:E20", col_names = FALSE, skip = 0)>

Along with readxl, I have installed
<library(cellranger)
library(Rcpp)
library(tibble)
library(tidyverse)>

Also I am followin the guidelines stated in- https://cran.r-project.org/web/packages/readxl/readxl.pdf

Thanks

**Comment by jennybc** [comment]
readxl gained the `range` argument with version 1.0.0. Perhaps your version is earlier? Use `packageVersion("readxl")` to check.

**Comment by Deepu298** [comment]
Thank you Jenny, 
re-installing package <("readxl")> from "Tools" -> "Install Packages" -> "Repository" was installing old version. 
I took zip file "readxl_1.0.0.zip" from the below location and installed it "Tools" -> "Install Packages" -> "Pachage Archive File". This resolves the issue.
[New version](https://cran.r-project.org/web/packages/readxl/index.html)

**Comment by jennybc** [comment]
Glad it's resolved! You might want to figure out why RStudio is installing from a repository that seems to be out of date? readxl 1.0.0 came out several months ago. Because that will certainly cause you grief with other packages eventually.

**Comment by Deepu298** [comment]
sure, will check that.
Thanks again for the quick turnaround.
