### ISSUE TITLE
read_excel crashes for particular sheet(s)

### ISSUE THREAD

**Issue by ramanan82** [tidyverse/readxl#387]
I have an .xls file with multiple sheets. I used read_excel to read a particular sheet in a particular cell range. It crashes R (I tried both in terminal window as well as in R studio). However, when I convert to .xlsx, it imports fine

**Comment by jennybc** [comment]
I can't look into this without that actual `.xls` file.

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box. `.xlsx` is a supported file type. You'll need to zip or gzip `.xls` so it appears as `.zip` or `.gz`.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by ramanan82** [comment]
Thank you for the response. 
[2016_GCP_Sequential Template.zip](https://github.com/tidyverse/readxl/files/1327868/2016_GCP_Sequential.Template.zip)
I wanted to attach, but did not look carefully. Here is a .zip archive of that single .xls file. The problem occurs when I want to read the sheet "G 01" sheet (third in the .xls)

**Comment by ramanan82** [comment]
I had attached the zip file in my previous post. Can someone kindly answer, if thus issue was forgotten?

**Comment by jennybc** [comment]
Sorry I just haven't done a maintenance pass on readxl since September. But it's getting some love in December.

**Comment by jennybc** [comment]
I've recently pulled in many updates from libxls and readxl now appears to be able to read this file 🎉

You will need to install the dev version from GitHub for now, but a CRAN release with these changes is coming soon.
