### ISSUE TITLE
Leading zeros trimmed when col_type = "text"

### ISSUE THREAD

**Issue by hlynurhallgrims** [tidyverse/readxl#389]
I was reading in a series of fixed-digit identification codes that contain leading zeros.  

```
library(readxl)
id_7 <- read_excel(path = "X:/.../id_7.xlsx", 
                   col_names = TRUE, col_types = c("text", "text", "text", "text"), 
                   na = "") 
```
The Excel document I'm reading from has the columns set to a "Custom" number format, where the type is set as 0000000. So in effect Excel pads the id-code with leading zeros until the length of each code is 7 characters. Ideally, this should be read into R (when col_type = "text") as a character vector with the leading zeros included, but unfortunately they are trimmed in the process.

So, to be clear, data that looks like this in your spreadsheet
0000123
0000012
0000001

becomes
123
12
1

in R.

Of course, fixing this in R after the fact is no big deal using stringr::str_pad(), but I figured I'd post the issue anyway as this trimming of leading zeros could lead to some problems for unknowing readxl users.

**Comment by jennybc** [comment]
If the cells are numeric, then there's no easy way to get at this formatted value you see. It exists no where on disk, but is generated for the benefit of human eyeballs in the Excel application.

This is actually the same issue as this re: dates #118. To get the result you want, readxl would have to understand Excel number formats and be able to apply them. That is a long-term goal, but it's not trivial to implement.

I'm going to close this and let #118 represent this problem, but now they are linked. Thanks for another good example.

**Comment by hlynurhallgrims** [comment]
Thanks for the swift reply and the explanation... and for this wonderful tool, obviously :)
