### ISSUE TITLE
Error with read_xlsx(): Invalid sheet xml (no <worksheet>)

### ISSUE THREAD

**Issue by mdbauer** [tidyverse/readxl#393]
When using `read_xlsx(path, sheet)` _one_ particular sheet, in _one_ particular Excel file, gives me -- and _only me_ not my colleagues who run the same code -- the following error:
```
Error in read_fun(path = path, sheet = sheet, limits = limits, shim = shim,  : 
  Sheet 'Chart' (position 3): Invalid sheet xml (no <worksheet>)
```
To be clear, I can load other Excel files and even all other sheets in the problem file. Just not this one sheet that I need. 

Unfortunately I can't share the file since it contains proprietary data (you must be sick of hearing that).

What is striking is that we cannot reproduce this error on any of my coworkers' computers. Comparing our sessionInfo()'s, the only systematic difference is that they are running Windows 8 and I'm running Windows 10. 

Any idea what this could be or how I can continue to dig deeper?

My apologies if this is the wrong forum to ask such a question but I'm at my wit's end.

Thank you,
Michael

**Comment by jennybc** [comment]
That's really weird. How sure are you that no one has, say, opened the file in Excel and then resaved it? Excel itself can open all sorts of peculiar files that no third party library can deal with.

It's really hard to say any more without getting my hands on the xlsx. Could that sheet have ... I don't know ... protection applied to it? Are there hidden Sheets? Is there any evidence of a Chart Sheet (see your error message)?

**Comment by mdbauer** [comment]
The solution was that the sheet `Chart` does not contain any data, just a chart. The code should have referred to another worksheet. Why this worked for other users is a puzzle for me to solve. 
Sorry to take up your time with this, and thank you for the great work you are doing here.
