### ISSUE TITLE
Reading Many Rows Leads to error

### ISSUE THREAD

**Issue by alexhallam** [tidyverse/readxl#395]
I got the following error

`Error: Cell references aren't uniformly A1 or R1C1 format: A1:V296066`

When using the following command

`data <- read_excel("data.xlsx",range = "A1:V296066")`

but not when reading fewer rows such as 

`data <- read_excel("data.xlsx",range = "A1:V29606")`

I am guessing this is because the row number is so long that `readxl` thinks that this is in R1C1 format, but I am not sure.

Is there a good work around for this?

**Comment by alexhallam** [comment]
False alarm. Turns out it really is my excel file not the size.

**Comment by jennybc** [comment]
If I follow ... we can close this then?
