### ISSUE TITLE
Dealing with Blanks

### ISSUE THREAD

**Issue by tres-pitt** [tidyverse/readxl#396]
Related to: https://github.com/tidyverse/readxl/issues/361

One specific type conversion generating a warning at every pertinent row is blanks (which should be null). Confusingly, the documentation states 'If NAs are represented by something other than blank cells, set the na argument.' I'm not sure if the warnings get generated by an all-null/blank column; my case is a column with a mixture of characters and blanks. I've confirmed read.csv does not have this issue when reading the same file (well, same data - .xlsx vs .csv)

**Comment by jennybc** [comment]
Can you say a bit more about what you're seeing? And/or provide an example?

**Comment by jennybc** [comment]
Closing due to lack of follow up.
