### ISSUE TITLE
Read rows based on start and end cell number

### ISSUE THREAD

**Issue by tarunparmar** [tidyverse/readxl#406]
I wanted to submit this as feature request.

Sometimes Excel files has certain rows and columns which are only used for information, the real data is offset by x number or rows and y number of columns.

The above use case is met by the package but I my sheet has multiple blocks of data and to read those as separate dataframes, I want to specify search string or keyword to identify a starting cell and ending cell which can be used to read rows between the specified cells only.

**Comment by nacnudus** [comment]
Have you tried the `range` argument to `read_excel()`?

> range: A cell range to read from, as described in cell-specification. Includes typical Excel ranges like "B3:D87", possibly including the sheet name like "Budget!B2:G14", and more. Interpreted strictly, even if the range forces the inclusion of leading or trailing empty rows or columns. Takes precedence over ‘skip’, ‘n_max’ and ‘sheet’.

**Comment by tarunparmar** [comment]
I do not know where the data in the sheet start, I am trying to look for a keyword which hints the onset of rows and columns where the data starts. Does that make sense ?

**Comment by jennybc** [comment]
I don't think readxl is likely to acquire this ability natively in the near term or maybe ever. It's pretty specialized and would really complicate cell reading.

A way forward: when your knowledge of the spreadsheet is this limited, do an initial read with readxl (or tidyxl?). Find your sentinel values are and use that info to form a clean call to readxl. You could package this nicely for yourself and make it feel pretty slick.

There's no way to avoid two passes.

**Comment by tarunparmar** [comment]
Two pass solution is what got me going for now , I got it working with this code :

```
cellfinder <- function(DF, search_str){
     ### Ref: https://stackoverflow.com/a/12465387/6616640
     ### Below two statements help identify the row for giving search_str
     ind <- which(DF==search_str, arr.ind=TRUE)
     
     cell_loc <- paste(rownames(DF)[ind[1:nrow(ind)]],  colnames(DF)[ind[2]], sep=', ')

     ## Ref: https://stackoverflow.com/a/17009781
     ## split string at non-digits
     s <- strsplit(cell_loc, "[^[:digit:]]")
     
     ## convert strings to numeric ("" become NA)
     solution <- as.numeric(unlist(s))
     
     ## remove NA and duplicates
     solution <- unique(solution[!is.na(solution)])  
     
     return(solution)
}

### function call
cellfinder(dt,"Search Keyword")
```

Closing the thread!
