### ISSUE TITLE
Ruining large numbers in columns with characters when reading XLS

### ISSUE THREAD

**Issue by alexeyknorre** [tidyverse/readxl#410]
Hi everybody. Thank you much for the package, it is great. I use it (among other things) to parse big dirty government spreadsheets like this (it's in Russian): 
![image](https://user-images.githubusercontent.com/5637722/33432844-8b2c6c6e-d5ea-11e7-9771-b9a24e2a7140.png)
I read the whole sheet like the one I linked and then cleanse it (cutting off useless rows and columns, etc). It has been a great pleasure, as I was able to do it in R way. Why am I writing about this is that I cannot explicitly set column types for such data, and it's relevant to the issue.

I am encountering a reading error when working with such files and managed to reproduce it on very simple example.
So, imagine we have an XLSX spreadsheet with one column, which consists of the header, one string row, and three number rows. [test_forma_xlsx.xlsx](https://github.com/tidyverse/readxl/files/1517923/test_forma_xlsx.xlsx)
It works great:
```
> xlsx <- read_excel("C:/Users/Alexey/Desktop/test_forma_xlsx.xlsx")
> xlsx
# A tibble: 4 x 1
  `Column header`
            <chr>
1     Some string
2      9999999999
3      2147483648
4      2146483647
```

But if you try to save the XLSX file as XLS and then read (sorry, github doesn't let me upload .xls), something breaks when a number in a row is bigger than 2146483647 :

```
> xls <- read_excel("C:/Users/Alexey/Desktop/test_forma_xls.xls")
> xls
# A tibble: 4 x 1
  `Column header`
            <chr>
1     Some string
2     -2147483648
3     -2147483648
4      2146483647
```
Can somebody reproduce it? Any idea how to fix this?

**Comment by jennybc** [comment]
This is probably what I recently fixed in https://github.com/tidyverse/readxl/commit/c1d3bd5f62479631fa98e6177ff3a44c89879af0.

Can you install the dev version from GitHub and see if it's fixed for you?

**Comment by alexeyknorre** [comment]
Hey @jennybc, thanks, it worked. Hope it gets to CRAN as soon as possible.

```
> sessionInfo()$otherPkgs
$readxl
Package: readxl
Title: Read Excel Files
Version: 1.0.0.9000
...
> xls <- read_excel("C:/Users/Alexey/Desktop/test_forma.xls")
> xls
# A tibble: 4 x 1
  `Column header`
            <chr>
1     Some string
2      9999999999
3      2147483648
4      2146483647
```

**Comment by jennybc** [comment]
I'm hoping in December? There are some other smallish things that need to be done before it makes to submit.
