### ISSUE TITLE
incorrect plot for read_excel's result

### ISSUE THREAD

**Issue by MikhailLagutin** [tidyverse/readxl#412]
[err_data.txt](https://github.com/tidyverse/readxl/files/1542077/err_data.txt)
>library(readxl)
>err_data <- read_excel("err_data.xls")
>plot(err_data, col=err_data[,3])

Warning message:
There were 50 or more warnings (use warnings() to see the first 50)
The plot is incorrect.

if I change a function call:

>plot(err_data, col=err_data$GROUP))

plot is OK.

If I save "err_data.xls" in text format and import it with function read.delim2, then the plot is correct.
Imported frame has type "int" (not "num") for third column.

I was not permitted to attach my excel file to this letter. So I have submitted a text format version of the file.

**Comment by batpigandme** [comment]
Could you please make this into a self-contained reproducible example (aka a [reprex](https://www.tidyverse.org/help/#reprex))? That way we can see the code and the output. It's hard to tell what the problem is from the description alone.

**Comment by MikhailLagutin** [comment]
It's not posible, because I can't attach the excel-file to this letter. I think that the bug is caused by inputation algorithm of the function read_excel().  This function has only one column type for real numbers - "num". But, for example, function utils::read.delim2 creates a data frame wich columns have two types: "num" and "int".  The function graphics::plot works incorrectly with data frames imported by the function read_excel(). It does not shows colored points in the scatter plots. 

To reproduce the bug you need to transform an attached text "file err_data.txt" to excel format file "err_data.xls". Then you need to import the excel  file with the function read_excel():

>err_data <- read_excel("err_data.xls")

Finally, you have to call the plot function:

>plot(err_data, col=err_data[,3])

The resulting plot does not show colored points. It is a bug.

Nevertheless, if you change the plot call to the following:

>plot(err_data, col=err_data$GROUP)

then you shall receive a correct scatter plot with colored points.

**Comment by batpigandme** [comment]
Please see Jenny's comment here for a fuller explanation of how to provide a reprex for readxl https://github.com/tidyverse/readxl/issues/387#issuecomment-331465411.

**Comment by nacnudus** [comment]
@MikhailLagutin Have you checked the settings in Excel for the decimal separator?  I suspect it is set to use a point `.` rather than a comma `,`, which means that it is storing the numbers as text, and readxl is correctly reading them as text.

You can check this in Settings > Advanced > Use system separators.  Here is a screenshot.

![temp](https://user-images.githubusercontent.com/3522552/33788476-6c80471e-dc6a-11e7-99bb-78b5dd2a652b.png)

**Comment by MikhailLagutin** [comment]
[err_data.xlsx](https://github.com/tidyverse/readxl/files/1544583/err_data.xlsx)
When I call reprex(), it generares meaningless error comments:
 
library("readxl")
err_data <- read_excel("err_data.xlsx")
#> Error in read_fun(path = path, sheet = sheet, limits = limits, shim = shim, : Evaluation error: zip Ñ„Ð°Ð¹Ð» 'err_data.xlsx' Ð½Ðµ Ð¼Ð¾Ð¶ÐµÑ‚ Ð±Ñ‹Ñ‚ÑŒ Ð¾Ñ‚ÐºÑ€Ñ‹Ñ‚.
plot(err_data, col=err_data[,3])
#> Error in plot(err_data, col = err_data[, 3]): Ð¾Ð±ÑŠÐµÐºÑ‚ 'err_data' Ð½Ðµ Ð½Ð°Ð¹Ð´ÐµÐ½
```
I think you should not to pay any attention to them.

A bug:

>library("readxl")
>err_data <- read_excel("err_data.xlsx")
>plot(err_data, col=err_data[,3])

The resulting scatter plot is not correct: there are no colored points in the plot.
When a use different (equivalent) call
[err_data.xlsx](https://github.com/tidyverse/readxl/files/1544582/err_data.xlsx)


>plot(err_data, col=err_data$GROUP)

the points appear.

**Comment by cderv** [comment]
I do not think this something to do with inputation algorithm but more how things work in the tidyverse. I use your post link  to get the data

``` r
url <- "https://github.com/tidyverse/readxl/files/1544583/err_data.xlsx"
tmp <- tempfile("ex_data", fileext = ".xlsx")
resp <- httr::GET(url, httr::write_disk(tmp))
library(readxl)
err_data <- read_excel(tmp)

# this is a tibble
err_data
#> # A tibble: 43 x 3
#>        X     Y GROUP
#>    <dbl> <dbl> <dbl>
#>  1 -2.78 -1.37     1
#>  2 -1.86 -0.41     1
#>  3 -1.28 -1.22     1
#>  4 -0.62 -0.60     1
#>  5 -1.61 -1.52     1
#>  6 -1.50 -1.37     1
#>  7 -0.07 -0.14     1
#>  8 -0.99 -1.45     1
#>  9  0.26 -0.21     1
#> 10  0.59  0.06     1
#> # ... with 33 more rows

# this is still a tibble with only the third column
err_data[, 3]
#> # A tibble: 43 x 1
#>    GROUP
#>    <dbl>
#>  1     1
#>  2     1
#>  3     1
#>  4     1
#>  5     1
#>  6     1
#>  7     1
#>  8     1
#>  9     1
#> 10     1
#> # ... with 33 more rows

# this is a vector
err_data$GROUP
#>  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2
#> [36] 2 2 2 2 2 2 2 3
```

As we see above, `tibble` extraction operator `[` subsets as a one column tibble and not a vector as base `[` operator do

``` r
# using [ with a data.frame (not a tibble) gives a vector
mtcars[, 1]
#>  [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2
#> [15] 10.4 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4
#> [29] 15.8 19.7 15.0 21.4
```

So, first, this is nothing to do with `readxl` but more with `tibble` way of working. It seems you need to provide a vector to your `plot` function, not a tibble. It is why you have an error unless you use `$`

``` r
# not ok
plot(err_data, col=err_data[,3])
#> Warning in plot.xy(xy, type, ...): la couleur fournie doit être soit une
#> valeur numérique, soit une chaîne de caractères
```

![](https://i.imgur.com/1e5tWal.png)

``` r
# ok
plot(err_data, col=err_data[,3][[1]])
```

![](https://i.imgur.com/lJx2GG4.png)

``` r
# ok with $
plot(err_data, col=err_data$GROUP)
```

![](https://i.imgur.com/lJx2GG4.png)

or using the tidyverse with function `pull` from `purrr`

``` r
library(tidyverse)
err_data %>%
  plot(col = pull(., 3))
```

![](https://i.imgur.com/vnDMIuE.png)

Created on 2017-12-09 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by MikhailLagutin** [comment]
Thank you for the detailed explanation. Till now I knew nothing about tibbles. I assume that most inexperienced R-users also have not heard anything about them. So they will be surprised by the unexpected error scatter plot.
