### ISSUE TITLE
“readxl” R package creates “TRUE” value in cells after importing excel files

### ISSUE THREAD

**Issue by fritz35** [tidyverse/readxl#413]
After importing excel files (xlsx) with "readxl" package in RStudio, many "TRUE" values seem in the imported file, is there any solution for this problem?  Screenshots as attachments:

Original file:

![original](https://user-images.githubusercontent.com/29121623/33796884-840d5daa-dd0e-11e7-8d3d-41d96178aa51.jpg)

While importing to RStudio:

![import](https://user-images.githubusercontent.com/29121623/33796433-2abec95e-dd05-11e7-8609-ea55b0e96744.jpg)

After importing to RStudio

![true](https://user-images.githubusercontent.com/29121623/33796426-fc6be410-dd04-11e7-9a83-7ad124bc5644.jpg)

**Comment by cderv** [comment]
Hi, what is the issue ? What value did you expect in this cell instead of TRUE ?
What is in your excel sheet for this cell ? 
We need a more precise example to help us help you. A [reprex](http://reprex.tidyverse.org/) is even better !

**Comment by fritz35** [comment]
I updated the issue with the original file screenshot, the original value in the screenshot is 949.

**Comment by batpigandme** [comment]
It's very hard to look into this without the  `.xls` file.

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box. `.xlsx` is a supported file type. You'll need to zip or gzip `.xls` so it appears as `.zip` or `.gz`.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by cderv** [comment]
@fritz35 I think you should look into the column type that is your excel file and how `readxl` reads it.
This could help you look into this : http://readxl.tidyverse.org/articles/cell-and-column-types.html

Your column has a lot `.`  in the column and it is possible that the `na = c(".")` does not play well with column guessing. However, column guessing is based on excel type, so... 

I let you dig into this yourself or provide us with an example with can reproduce.

**Comment by jennybc** [comment]
As others have already said, it's very hard to be sure w/o an example.

But I'm guessing that you have lots of blank values at the top of this worksheet. Looks like this column is being guessed as logical, and anything that's neither `NA` nor zero is becoming `TRUE`. If my diagnosis is correct, you should either specify the column type you want (probably numeric in this case) or increase `guess_max` to something higher than the default of 1000.

**Comment by fritz35** [comment]
> file1 <- read_excel("file1.xlsx", sheet = 1, guess_max = 21474836, col_types = "numeric") and then 
> write.csv(file1, file = "file1 .csv") worked for me.  First code automatically gives "NA" values for both the files which have "." values or blank cell values automatically. Thanks for your suggestions.

**Comment by Elaine-AL** [comment]
thanks alot @jennybc  and @oozdmr .... the use of guess_max has really worked for me

**Comment by hfmolinal** [comment]
@jennybc I had the same issued and your suggestion worked for me too. Why is this problem? Should we think of always importing data in .csv format?
