### ISSUE TITLE
feature request: use column names in col_types

### ISSUE THREAD

**Issue by RobertMyles** [tidyverse/readxl#415]
Would it be possible to use column names with `col_types` in `read_excel()`? I have some Excel spreadsheets that have many columns, and that need to be formatted with `col_types` because of some badly formatted cells. It gets to a point where it's hard to keep track of what column is what type! For example, I have this snippet of code:

```
obras <- read_excel("CONTROLE DE DOCUMENTOS 2017.xlsx", sheet = "DATAS - ETAPAS",
                 col_types = c("text", "text", "text", "text", "text", 
                               "text", "text", "text", "text", "text", "text", 
                               "text", "text", "text", "text", "text", 
                               "text", "text", "text", "text", "text",
                               "text", "date", "date", "date", "date",
                               "date", "date", "date", "date", "date",
                               "date", "date", "date", "date", "date", 
                               "date", "date", "date", "date", "numeric", 
                               "date", "numeric", "text"), na = "----------")
```

It would be great to be able to use something like `col_types = c("Column1" = "text", "Column2" = "date")`, (with `Column1` the actual name of the first column).

**Comment by jennybc** [comment]
I mostly consider this a subset of "Add column specification as in readr" #198. It would certainly be *implied* if readxl got a readr-like col spec. I'll leave this open for now, in case it's easy to implement this specific feature on a shorter timeframe.

**Comment by jennybc** [comment]
Improved col spec handling, here and in readr, is on the horizon now. So I seriously I doubt I will extend readxl's current `col_names` / `col_types` system. Therefore, folding this into #198.

**Comment by apsalverda** [comment]
For the time being, while readxl lacks improved column specification handling, it would be extremely useful if its parsing functions could output the column formats it applies when a file is parsed, much like read_csv does, for instance:

```
read_excel("my_excel_file.xls")
(...)
Parsed with column specification:
col_types = c(
"text",
"text"
)
```

This would allow the user to:
1. Parse a file
2. Check the resulting tibble and note which columns are parsed incorrectly
3. Copy the "col_types" output by the parsing function
4. Update the format for only those columns parsed incorrectly
5. Parse the file again, using the col_types specification from step 4 as an argument

I'm working with an Excel file with 58 columns and second @RobertMyles 's comment that it's quite challenging to put together and manage the appropriate col_types specification, given how this is currently handled in readxl--where I have to create from scratch a long string with each column's format.
