### ISSUE TITLE
Fatal error when reading an xls file in R Notebook session

### ISSUE THREAD

**Issue by alexeyknorre** [tidyverse/readxl#439]
Hi there,

when I create a new R Notebook and try to read an Excel file through `readxl::read_excel()`, the RStudio crashes. UPD: there is similar behaviour when I do this in usual script setting. As the file is available online, it is easy to reproduce an error. Please create a new R Notebook and execute the following piece (note that I had to remove three apostrophes before `{r}` and in the end of the chunk):
```
{r}
download.file("http://www.gks.ru/free_doc/2017/demo/t3_3.xls", "deaths-russia-2017.xls")
library(readxl)
df <- read_excel("deaths-russia-2017.xls")
```

I immediately encounter an error
`seek: wanted to seek to sector 22085632 (0x1510000) loc=11307844096`
and session crashes. I am wondering if it is reproducible (I did it on two different computers with different versions of R and RStudio; `readxl` is latest), and if yes is there any way to fix this?

Thanks in advance, attaching sessionInfo just in case. 
```
> sessionInfo()
R version 3.4.0 (2017-04-21)`
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251    LC_MONETARY=Russian_Russia.1251
[4] LC_NUMERIC=C                    LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readxl_1.0.0

loaded via a namespace (and not attached):
[1] compiler_3.4.0   tools_3.4.0      yaml_2.1.16      Rcpp_0.12.16     cellranger_1.1.0`
```

**Comment by jennybc** [comment]
I can read the sheet just fine. I mean, it's in Cyrillic so I have no idea if all is well, but there is no error and it looks pretty plausible.

Just to be sure, on Windows it is important to use, e.g., `download.file( ..., mode = 'wb' )`.

**Comment by alexeyknorre** [comment]
Jenny, thanks a lot! Just found out that `download.file()` somehow breaks the file, so it is not about `readxl`. `mode = "wb"` fixed everything. Thanks again for the quick reply, you saved my tomorrow class.
