### ISSUE TITLE
Warning when loading data from Excel spreadsheet if warnPartialMatch options set

### ISSUE THREAD

**Issue by gp2x** [tidyverse/readxl#440]
I run R with the options **warnPartialMatchArgs**, **warnPartialMatchAttr**, and **warnPartialMatchDollar** set to TRUE, in order to minimize the chances of inadvertently assigning data to the wrong variable. However, this has the effect of generating warnings in cases where, for example, a function in a package calls another function using a partial variable name, or the variable name has been lengthened since the calling function was written.

### Reproducible example

```r
options(warnPartialMatchArgs=TRUE,
        warnPartialMatchAttr=TRUE,
        warnPartialMatchDollar=TRUE)
library(readxl)
datasets <- readxl_example("datasets.xlsx")
test <- read_excel(datasets)
```

On my machine, this results in the following warnings:

```
Warning message:
In read_fun(path = path, sheet = sheet, limits = limits, shim = shim,  :
  partial argument match of 'sheet' to 'sheet_i'
```

### Session Info

```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS: /usr/lib/libblas.so.3.8.0
LAPACK: /usr/lib/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readxl_1.0.0

loaded via a namespace (and not attached):
[1] compiler_3.4.4   tools_3.4.4      pillar_1.2.1     tibble_1.4.2    
[5] Rcpp_0.12.16     cellranger_1.1.0 rlang_0.2.0     
```

### Possible cause

Digging around in the source a bit, it looks like the function **read_fun()** is being called in **read_excel.R** using the named variable "**sheet**", when it's expecting "**sheet_i**".
I believe you could fix the warning by changing line 145 in **read_excel.R** from:

`read_fun(path = path, sheet = sheet,`

to:

`read_fun(path = path, sheet_i = sheet,`

...but this is my first time looking at the code so I could be wrong about this.

**Comment by jennybc** [comment]
This was fixed in dev a while ago:

https://github.com/tidyverse/readxl/commit/aab4ad483bf1975871c86afebf9f6d836bdd5257

I assume you must be seeing this in the CRAN version (?). Let me know if I've misunderstood.
