### ISSUE TITLE
read_excel() transforming percentages in uncontrollable ways

### ISSUE THREAD

**Issue by siemersn** [tidyverse/readxl#462]
# Issue

There are percentage math transformations taking place in read_excel() that seem to happen regardless of setting col_types options.  It doesn't seem to be an internal excel problem, as export from .xlsx to .csv within excel is a workaround. 

Welcome to the wonderful world of clinical pathologist spreadsheets.

```r

library(readxl)
url = 'http://fiveprime.org/minimal.readxl.bug.xlsx'
file = 'minimal.readxl.bug.xlsx'
download.file(url, file)
df = read_excel(file)
df
df = read_excel(file, col_types = 'text')
df
url = 'http://fiveprime.org/minimal.readxl.bug.csv'
file = 'minimal.readxl.bug.csv'
download.file(url, file)
system( paste( 'cat', file ) )

```

sessionInfo()                                                
 R version 3.3.2 (2016-10-31)
 Platform: x86_64-apple-darwin13.4.0 (64-bit)
 Running under: macOS  10.13.4

 locale:
 [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

 attached base packages:
 [1] stats     graphics  grDevices utils     datasets  methods   b\
 ase

 other attached packages:
 [1] readxl_1.1.0    devtools_1.13.4

 loaded via a namespace (and not attached):
  [1] assertthat_0.2.0 cli_1.0.0        tools_3.3.2      pillar_1.\
 0.1     withr_2.1.1.9000 tibble_1.4.1     crayon_1.3.4     Rcpp_0\
 .12.14     memoise_1.1.0    utf8_1.1.3       cellranger_1.1.0
 [12] digest_0.6.13    rlang_0.1.6.9003

**Comment by siemersn** [comment]
> library(readxl)                                                                                                                                   
 > url = 'http://fiveprime.org/minimal.readxl.bug.xlsx'                                                                                              
 > file = 'minimal.readxl.bug.xlsx'                                                                                                                  
 > download.file(url, file)                                                                                                                          
 trying URL 'http://fiveprime.org/minimal.readxl.bug.xlsx'
 Content type 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' length 8643 bytes
 ==================================================
 downloaded 8643 bytes

 > df = read_excel(file)                                                                                                                             
 Warning message:
 In strptime(x, format, tz = tz) :
   unknown timezone 'zone/tz/2018c.1.0/zoneinfo/America/Los_Angeles'
 > df                                                                                                                                                
 # A tibble: 4 x 2                                                                                                                                   
      ID Value
   <dbl> <chr>
 1  1.00 0.01
 2  2.00 2
 3  3.00 <1%
 4  4.00 3
 > df = read_excel(file, col_types = 'text')                                                                                                         
 > df                                                                                                                                                
 # A tibble: 4 x 2                                                                                                                                   
   ID    Value
   <chr> <chr>
 1 1     0.01
 2 2     2
 3 3     <1%
 4 4     3
 > url = 'http://fiveprime.org/minimal.readxl.bug.csv'                                                                                               
 > file = 'minimal.readxl.bug.csv'                                                                                                                   
 > download.file(url, file)                                                                                                                          
 trying URL 'http://fiveprime.org/minimal.readxl.bug.csv'
 Content type 'text/csv' length 34 bytes
 ==================================================
 downloaded 34 bytes

 > system( paste( 'cat', file ) )                                                                                                                    
  ID,Value
 1,1%
 2,2
 3,<1%
 4,3

**Comment by nacnudus** [comment]
@siemersn I think readxl is correct.  Cell B2 is the number `0.01` formatted (displayed) in Excel as a percentage `1%`.  Cell B4 is a text value `"<1%"`.

When Excel exports to a csv file, it gives what you see, rather than what is really there.  That is why you see `1%` rather than `0.01` in the csv file.

**Comment by siemersn** [comment]
Why would a csv export not reflect the internal representation of numbers,
as csv has no typing information? * If this behavior is correct, there's no
way in readxl to un-corrupt data that a user has entered with inconsistent
use of % signs. *I'll need to abandon my use of readxl for data science
applications, and do a manual .csv export instead.

At least, defining a column as 'text' in the import should work as need,
yes?  It should give what is "seen", which is what the user typed into the
spreadsheet, which is what I need.

Thanks,
Nathan






Nathan Siemers
Fiveprime.org

On Tue, Apr 24, 2018 at 9:29 AM, Duncan Garmonsway <notifications@github.com

**Comment by siemersn** [comment]
asking for 'list' column types does not solve the issue

read_excel(file, col_types = c("text", "list"))
returns:

 > data.frame(df)                                                                                                                                                                                                 
   ID Value
 1  1  0.01
 2  2     2
 3  3   <1%
 4  4     3

exporting the exel file to csv gives (as shown before):
system( paste( 'cat', file ) )
ID,Value
1,1%
2,2
3,<1%
4,3

The latter is what the user actually typed into the spreadsheet. 
Looking through the workbook xml, it seems like cell B1 (originally 1%) is indeed stored as 0.01.  **Yet excel has the ability to retrieve '1%', exactly what the user entered, in a csv export, while readxl does not**.  Please think about the ramifications of this, and see if there's a way to improve readxl to be able to return user input without modification, as excel can do during export.

Thanks
Nathan
