### ISSUE TITLE
xls files that can't be opened

### ISSUE THREAD

**Issue by chrowe** [tidyverse/readxl#466]
Based on #463 I am not sure if this is the kind of thing you want to fix but I figured I would share it since I got stuck on this for a while...

## Example
```r
library(readxl)
url = "https://www2.census.gov/programs-surveys/susb/tables/1999/county_naicssector_emplchange_1998-1999.xls"
download.file(url, paste0("output/susb/county_naicssector_emplchange_1998-1999.xls"), mode="wb")
excel_sheets("output/susb/county_naicssector_emplchange_1998-1999.xls")
```
## Output
```r
Error in xls_sheets(path) : Failed to open output/susb/county_naicssector_emplchange_1998-1999.xls
3. stop(structure(list(message = "Failed to open output/susb/county_naicssector_emplchange_1998-1999.xls", call = xls_sheets(path), cppstack = structure(list(file = "", line = -1L, stack = "C++ stack not available on this system"), .Names = c("file", "line", "stack"), class = "Rcpp_stack_trace")), .Names = c("message", ...
2. xls_sheets(path)
1. excel_sheets("output/susb/county_naicssector_emplchange_1998-1999.xls")
```

**Comment by chrowe** [comment]
For reference my workaround was to batch convert files to `.xlsx` using LibreOffice in Git Bash
```
/c/Program\ Files/LibreOffice\ 5/program/soffice.exe --headless --convert-to xlsx:"Calc MS Excel 2007 XML" -outdir /d/cori/GitHub/aws/output/susb/ /d/cori/GitHub/aws/output/susb/*.xls
```

**Comment by jennybc** [comment]
This appears to be another libxls regression. I can open it with readxl v1.0.0 but not v1.1.0. I also cannot read it with a standalone tool built from libxls, i.e. it's not fixable in readxl code.

Thanks, I'll pass the report along to libxls.

In the meantime, I suggest you read this file with readxl v1.0.0. Here's one way to install that:

``` r
devtools::install_version("readxl", version = "1.0.0")
```

You could install this to a non-default library (and keep v1.1.0 in whatever your usual place is) and load readxl from there on purpose when it's one of these problematic files.

``` r
library(readxl)
packageVersion("readxl")
#> [1] '1.0.0'
url = "https://www2.census.gov/programs-surveys/susb/tables/1999/county_naicssector_emplchange_1998-1999.xls"
download.file(url, file.path("investigations", "county_naicssector_emplchange_1998-1999.xls"), mode="wb")
excel_sheets("investigations/county_naicssector_emplchange_1998-1999.xls")
#> [1] "county9899"
read_excel("investigations/county_naicssector_emplchange_1998-1999.xls")
#> # A tibble: 64,802 x 9
#>    X__1        `Establishment B… X__2  X__3  X__4  X__5  X__6  X__7  X__8 
#>    <chr>       <chr>             <chr> <chr> <chr> <chr> <chr> <chr> <chr>
#>  1 <NA>        Constants by Sta… <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  2 <NA>        <NA>              <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  3 SOURCE: 19… <NA>              <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  4 <NA>        <NA>              <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  5 Note: Due … <NA>              <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  6 <NA>        <NA>              <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  7 <NA>        <NA>              <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  8 <NA>        <NA>              NAICS <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  9 STATE       COUNTY            CODE  NAIC… Birt… Deat… Expa… Cont… Cons…
#> 10 ALABAMA     STATE TOTAL       --    Total 10002 9649  26505 25168 29781
#> # ... with 64,792 more rows
```

Created on 2018-04-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jennybc** [comment]
You should be able to open this with dev version now.

Do you know of any files with similar problem that are a lot smaller? To put into our test suite?

**Comment by wagnerato** [comment]
Hi Jenny I have another file, because devtools::install_version("readxl", version = "1.0.0") didn't work. 
Can you help me?

[3PP9TC.zip](https://github.com/tidyverse/readxl/files/2430788/3PP9TC.zip)

> excel_aux<-c(excel_sheets("3PP9TC.xls"))
Error in xls_sheets(path) : Failed to open 3PP9TC.xls

The file is in correct directory

**Comment by jennybc** [comment]
@wagnerato You should open a new issue as there is no guarantee that each problematic xls fails for the same reason. In fact, that is definitely not true. Thanks providing a sample (I haven't looked at it yet or repro'd, though).
