### ISSUE TITLE
Difficulty in trying to determine if really an Excel file

### ISSUE THREAD

**Issue by gregdutkowski** [tidyverse/readxl#468]
I have a general script that tries to open an Excel file specified by the user.
I want to test if the file is actually an Excel file.
excel_format(FileName)
only seems to detect if the file has the appropriate extension.

If I try and read a file that is not excel even though it has the appropriate extension 
`SheetNames=excel_sheets(FileName)`
then I get 

Error in xlsx_sheets(path) :
  Evaluation error: zip file 'CSV_as.xlsx' cannot be opened.

Calls: excel_sheets -> xlsx_sheets
Execution halted

Which is good, but I want to trap the error an give the user a nice message.
However if I use try
```
 options(show.error.messages = FALSE)
 test <- try(SheetNames=excel_sheets(FileName))

```Then I just get the message
Execution halted

Any way around this?

**Comment by jennybc** [comment]
The [help file for `excel_format()`](http://readxl.tidyverse.org/reference/excel_format.html) goes into the `guess` argument and the two underlying helpers `format_from_ext() ` and `format_from_signature()`.

> excel_format(FileName)
> only seems to detect if the file has the appropriate extension.

With `guess = TRUE`, it should first consult file extension, then, if necessary, file signature. Do you have an example where that is not happening?

> If I try and read a file that is not excel even though it has the appropriate extension

`read_excel()` will use `excel_format(guess = TRUE)` and it will be fooled by the extension. If you want to be less trusting, use `format_from_signature()` directly to verify the format, before you ever attempt to read.

In general, it's much easier to answer a question if you present a complete code snippet I can run. Above, I have no idea what `FileName` or `CSV_as.xlsx'` actually are. I can guess, but such this guessing and ambiguity is where people miscommunicate. And it also takes much more time to fabricate the example myself, based on prose.

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box. `.xlsx` is a supported file type. You'll need to zip or gzip `.xls` so it appears as `.zip` or `.gz`.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.
