### ISSUE TITLE
read failure

### ISSUE THREAD

**Issue by ltierney** [tidyverse/readxl#471]
On Ubuntu 16.04, R 3.4.4, `readxl` version 1.0.0 reads this successfuly:

```r
if (! file.exists("Arrivals-2017-01-06.xls"))
   download.file("http://homepage.stat.uiowa.edu/~luke/data/Arrivals-2017-01-06.xls",
                         "Arrivals-2017-01-06.xls")
read_excel("Arrivals-2017-01-06.xls")
```
`readxl` Version 1.1.0 produces

```r
# A tibble: 0 x 0
```
The current GitHub version installed with `devtools` segfaults.

**Comment by jennybc** [comment]
I can reproduce the segfault with libxls alone. It appears to have nothing to do with readxl. I've reported it there:

https://github.com/evanmiller/libxls/issues/20

**Comment by jennybc** [comment]
I just merged a PR that includes an update to libxls that fixes the segfault. But readxl still does not read any data 😔, i.e. we're back to the v1.1.0 state.

This joins #417 and #391 where libxls no longer segfaults but doesn't read data.

@evanmiller is chipping away at major refactoring of libxls, to our great benefit. There are some regressions along the way (like this one) and he is prioritizing segfaults right now.

In the past I have sometimes debugged stuff in libxls itself, which I may eventually do here. But I can't do it right now.

**Comment by jameshunterbr** [comment]
I have hit the same bug with the following command and file. As with another reporter, I resaved the xls in xlsx format and read_excel() read it perfectly. I have removed all but 50 rows of the file so you won't be overwhelmed by its size (almost 2000 rows)



The command I used:
> x <- read_xls("mod_ctl_summary.xls", skip = 2,
+               col_types = c(rep("text", 2), rep("numeric", 2), 
+                             rep("text", 5)), 
+               col_names = c("A", "B", "C", "D", "E", "F", "G", "H", "J"))

Ooops. Github says it doesn't support xls files. How should I send it to you?

Jim Hunter

**Comment by jennybc** [comment]
Roger. When you've done so, I'm going to delete some messages here to keep things cleaner / separated.

**Comment by mschilli87** [comment]
I also have an XLS file (cannot share unfortunately) that I used to import with `read_excel` and now (after updating my R packages), I get an empty tibble (with the same code).

I worked around it by opening the file in Office and saving it as XLSX.

**Comment by jzadra** [comment]
Still having this issue.

**Comment by jennybc** [comment]
Making a pass through all xls issues.

The current release candidate for readxl embeds libxls as of https://github.com/evanmiller/libxls/commit/b6192a3eb4f5ba99435db259ca1fb442b1e8cba7.

And it still returns a 0 zero tibble 😐

I'll re-report upstream.

**Comment by jennybc** [comment]
More quick work by @evanmiller has fixed this. We are now back to the happy state of readxl v1.0.0 and can read this sheet with the dev version of readxl. It will go to CRAN soon.

``` r
readxl::read_excel("investigations/Arrivals-2017-01-06.xls")
#> New names:
#> * `` -> `..2`
#> * `` -> `..3`
#> * `` -> `..4`
#> * `` -> `..5`
#> * `` -> `..6`
#> * … and 12 more
#> # A tibble: 735 x 18
#>    `Department of … ..2   ..3   ..4   ..5   ..6   ..7   ..8   ..9   ..10 
#>    <chr>            <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr>
#>  1 Bureau of Popul… <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  2 <NA>             <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  3 Office of Admis… <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  4 Refugee Arrivals <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  5 by Placement St… <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  6 All Nationaliti… <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  7 October 01, 201… <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  8 <NA>             <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  9 <NA>             <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#> 10 <NA>             <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#> # … with 725 more rows, and 8 more variables: ..11 <chr>, ..12 <chr>,
#> #   ..13 <chr>, ..14 <chr>, ..15 <chr>, ..16 <chr>, ..17 <chr>, ..18 <chr>
```

<sup>Created on 2018-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
