### ISSUE TITLE
Regression testing on wild-caught spreadsheets

### ISSUE THREAD

**Issue by jennybc** [tidyverse/readxl#472]
Best explained here: https://github.com/evanmiller/libxls/issues/21

**Comment by mjsteinbaugh** [comment]
Hi @jennybc I'm hitting the libxls error on some old Excel spreadsheets. I'd like to be able to load these directly rather than resaving to CSV, because there's a lot of legacy data I need to work with. What's the best way to prepare a reprex? I'm happy to prepare some of these to add for regression testing.

**Comment by batpigandme** [comment]
Just giving you the readxl reprex best-practice here:

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:
1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box. `.xlsx` is a supported file type. You'll need to zip or gzip `.xls` so it appears as `.zip` or `.gz`.
2.  Share via DropBox or Google Drive and provide the link in your issue.
3.  Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
4.   Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by mjsteinbaugh** [comment]
Thanks @batpigandme I'll work on some minimal examples.
