### ISSUE TITLE
Failed to open a specific .xls: Unable to allocate memory

### ISSUE THREAD

**Issue by antuki** [tidyverse/readxl#478]
Hi, 
I'm writing about an issue a bit similar to #373 
When i download [this](https://www.insee.fr/fr/statistiques/fichier/1893204/pop-sexe-age-quinquennal6814.zip) file and I unzip it on my windows computer, The following line returns an error : 

      > bdd <- read_excel("pop-sexe-age-quinquennal6814.xls", sheet = paste0("COM_", 1975))
      Error in sheets_fun(path) : 
        Failed to open pop-sexe-age-quinquennal6814.xls

But when I open the file in Excel and resave as .xlsx, it works !

       > bdd <- read_excel("pop-sexe-age-quinquennal6814.xlsx", sheet = paste0("COM_", 1975))

What should I do so that it works without opening the file in Excel ?

Thanks a lot !

      > sessionInfo()
      R version 3.4.1 (2017-06-30)
      Platform: i386-w64-mingw32/i386 (32-bit)
      Running under: Windows >= 8 x64 (build 9200)

      Matrix products: default

      locale:
      [1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252          LC_MONETARY=French_France.1252
      [4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

      attached base packages:
      [1] stats     graphics  grDevices utils     datasets  methods   base     

      other attached packages:
       [1] forcats_0.3.0      stringr_1.3.0      dplyr_0.7.4        purrr_0.2.4        readr_1.1.1       
       [6] tidyr_0.8.0        tibble_1.4.2       ggplot2_2.2.1.9000 tidyverse_1.2.1    readxl_1.1.0      

      loaded via a namespace (and not attached):
       [1] jsonlite_1.5      reshape2_1.4.3    rstudioapi_0.7    magrittr_1.5      gtable_0.2.0     
       [6] rmarkdown_1.9     hms_0.4.2         xml2_1.2.0        pillar_1.2.2      htmltools_0.3.6  
      [11] haven_1.1.1       broom_0.4.4       cellranger_1.1.0  lattice_0.20-35   xaringan_0.6     
      [16] plyr_1.8.4        lubridate_1.7.4   knitr_1.20        pkgconfig_2.0.1   R6_2.2.2         
      [21] digest_0.6.15     xfun_0.1          colorspace_1.3-2  bindrcpp_0.2.2    rprojroot_1.3-2  
      [26] stringi_1.1.7     yaml_2.1.19       lazyeval_0.2.1    evaluate_0.10.1   httr_1.3.1       
      [31] compiler_3.4.1    bindr_0.1.1       cli_1.0.0         withr_2.1.2       backports_1.1.2  
      [36] munsell_0.4.3     psych_1.8.3.3     modelr_0.1.1      Rcpp_0.12.16      parallel_3.4.1   
      [41] assertthat_0.2.0  tools_3.4.1       foreign_0.8-70    scales_0.5.0.9000 crayon_1.3.4     
      [46] glue_1.2.0.9000   rlang_0.2.0.9001  mnormt_1.5-5      nlme_3.1-131      rvest_0.3.2      
      [51] rsconnect_0.8.8   grid_3.4.1

**Comment by jennybc** [comment]
I'm unable to download the sheet you link to, so I can't tell what the problem is. If it is path related, then I predict b10a1a80fba57e1e7e515b78f64acf62fd75843a will have fixed it. If you can install the development version of readxl from GitHub and try again, please let me know what happens.

**Comment by antuki** [comment]
Thank you for your answer.

I tried with both devtools and cran versions and i obtain the same issue. 

But I tried to guess what is the problem with the file : It's a big file (100 Mo) with around 15 sheets. I've noticed that when I delete enough sheets (and the size is approximately 50 Mo) the function is working again. So I think it's a question of size of the xls file (bugging when the file is too big). 

But it is strange because I didn't have this issue with this same file with the last version of readxl I had on my computer (I cannot remember which one it was but I did not have the same issue before updating all my packages last week).

**Comment by jennybc** [comment]
Is it only this file that gives you problems?

I finally succeeded with the download and also fail to read it with readxl.

I get a more informative failure when I use a stand-alone tool built from libxls


```
jenny@2015-mbp libxls-evanmiller-github $ ./xls2csv ~/rrr/readxl/investigations/pop-sexe-age-quinquennal6814.xlsFILE: /Users/jenny/rrr/readxl/investigations/pop-sexe-age-quinquennal6814.xls
Error reading XLS file: Unable to allocate memory
```

I can ask over there if the maintainer is interested in acting on this, but yes it looks like the file size is part of the puzzle.

**Comment by antuki** [comment]
I've tried readxl for the first time recently so I didn't try ot with a lot of files but yes it is the only example that I have in mind.

And just for your information, this file is from the Insee (french national institute of statistics) and gives the age of the population for each french municipality. 

And yes I hope the maintainer will be interested in fixing this issue even if I can still use other packages dealing with xls file I'm interested in using this one  ! 

Thanks

**Comment by cderv** [comment]
FWIW @antuki,  if the file is converted to xlsx with Microsoft Excel, it is readable by {readxl}. The issue is just for xls format. 

``` r
readxl::excel_sheets("~/../Downloads/pop-sexe-age-quinquennal6814/pop-sexe-age-quinquennal6814.xlsx")
#>  [1] "Présentation"                "Documentation"              
#>  [3] "Modifications_territoriales" "DEP_1968"                   
#>  [5] "DEP_1975"                    "DEP_1982"                   
#>  [7] "DEP_1990"                    "DEP_1999"                   
#>  [9] "DEP_2009"                    "DEP_2014"                   
#> [11] "COM_1968"                    "COM_1975"                   
#> [13] "COM_1982"                    "COM_1990"                   
#> [15] "COM_1999"                    "COM_2009"                   
#> [17] "COM_2014"
readxl::read_excel("~/../Downloads/pop-sexe-age-quinquennal6814/pop-sexe-age-quinquennal6814.xlsx", sheet = paste0("COM_", 1975))
#> # A tibble: 38,227 x 46
#>    `Recensement de ~ X__1  X__2  X__3  X__4  X__5  X__6  X__7  X__8  X__9 
#>    <chr>             <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr>
#>  1 TABLEAU COMMUNAL~ <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  2 France métropoli~ <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  3 Découpage géogra~ <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  4 <NA>              <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  5 Note de lecture ~ <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  6 <NA>              <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  7 Documentation     <NA>  Modi~ <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  8 © Insee           Sour~ <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  9 <NA>              <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#> 10 <NA>              <NA>  <NA>  <NA>  <NA>  AGE   00    00    05    05   
#> # ... with 38,217 more rows, and 36 more variables: X__10 <chr>,
#> #   X__11 <chr>, X__12 <chr>, X__13 <chr>, X__14 <chr>, X__15 <chr>,
#> #   X__16 <chr>, X__17 <chr>, X__18 <chr>, X__19 <chr>, X__20 <chr>,
#> #   X__21 <chr>, X__22 <chr>, X__23 <chr>, X__24 <chr>, X__25 <chr>,
#> #   X__26 <chr>, X__27 <chr>, X__28 <chr>, X__29 <chr>, X__30 <chr>,
#> #   X__31 <chr>, X__32 <chr>, X__33 <chr>, X__34 <chr>, X__35 <chr>,
#> #   X__36 <chr>, X__37 <chr>, X__38 <chr>, X__39 <chr>, X__40 <chr>,
#> #   X__41 <chr>, X__42 <chr>, X__43 <chr>, X__44 <chr>, X__45 <chr>
```

Created on 2018-05-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

As this one won't change every often I think, it could be suitable for you to just download then convert manually before importing into R. 

However, the bugs remains with xls format.

**Comment by cturnerbridger** [comment]
Hi, I am also having this issue with large xls files. I know that you mentioned that it seems to be a libxls issue; however, the bug seemed to occur after the update of R version 3.5.0 (2018-04-23) as I was able to read the same files previously.

Hopefully that is useful information.

Christian

**Comment by jennybc** [comment]
@cturnerbridger Is the xls in question available?

**Comment by antuki** [comment]
The same as @cturnerbridger  : i was also able to read this file with a previous version

**Comment by antuki** [comment]
Yes it concerns the French xls file from the Insee.

**Comment by cturnerbridger** [comment]
@jennybc sorry I can't share the files exactly. I will try to set up a similar / reproducible example today (UK time). Thanks for your help

**Comment by KZARCA** [comment]
Hi, I have a similar problem, [here is the link](https://mega.nz/#!ybZyGAAZ!p56qIcnfYqsCns1R6XbrdjLFHtuwTmotlRhesohV4M0)

**Comment by courtiol** [comment]
Same issue here with the file MYE6PE3_mid-2001-mid-2012-unformatted-syoa-data-file.xls that is part of the following Zip file:

https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/populationestimatesforukenglandandwalesscotlandandnorthernireland/mid2001tomid2010/mid2001tomid2012ukpopulationestimatesv2.zip

In previous version, I used to be able to do:

```{r}
read_excel("MYE6PE3_mid-2001-mid-2012-unformatted-syoa-data-file.xls",
             sheet = "Mid-2001", col_names = TRUE, skip = 1)
```

and now it no longer works...
Again saving as *.xlsx is a workaround.

Best,

```{r}
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices
[4] utils     datasets  methods  
[7] base     

other attached packages:
[1] bindrcpp_0.2.2 stringr_1.3.1 
[3] purrr_0.2.4    ggplot2_2.2.1 
[5] dplyr_0.7.5    readxl_1.1.0  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17    
 [2] rstudioapi_0.7  
 [3] bindr_0.1.1     
 [4] magrittr_1.5    
 [5] tidyselect_0.2.4
 [6] munsell_0.4.3   
 [7] colorspace_1.3-2
 [8] R6_2.2.2        
 [9] rlang_0.2.0     
[10] rematch_1.0.1   
[11] plyr_1.8.4      
[12] tools_3.5.0     
[13] grid_3.5.0      
[14] gtable_0.2.0    
[15] utf8_1.1.3      
[16] cli_1.0.0       
[17] yaml_2.1.19     
[18] lazyeval_0.2.1  
[19] assertthat_0.2.0
[20] tibble_1.4.2    
[21] crayon_1.3.4    
[22] glue_1.2.0      
[23] stringi_1.2.2   
[24] compiler_3.5.0  
[25] pillar_1.2.2    
[26] cellranger_1.1.0
[27] scales_0.5.0    
[28] pkgconfig_2.0.1 
```

**Comment by jennybc** [comment]
The `.xls` that fail with with "Unable to allocate memory" may be readable now that https://github.com/evanmiller/libxls/issues/22 is closed. I'll pull libxls from upstream soon to find out.

**Comment by antuki** [comment]
Thank you @jennybc . I tried again with an "Insee" file today and the problem still remains.

**Comment by joelgombin** [comment]
FWIW, same problem here with [this file](https://insee.fr/fr/statistiques/fichier/3137409/base-ic-evol-struct-pop-2014.zip). Works with readxl 1.0, doesn't work with readxl 1.1.

**Comment by cderv** [comment]
FWIW, @antuki, @joelgombin , I believe the libxls upstream has not been pulled yet into `readxl` looking at the src folder last changed.
https://github.com/tidyverse/readxl/tree/master/src/libxls
those tests should wait until then to be sure the issue still remains.

**Comment by jennybc** [comment]
Having embedded the latest libxls in the **dev version** of readxl, I can read the original xls:

``` r
readxl::read_excel(
  "investigations/pop-sexe-age-quinquennal6814.xls",
  sheet = paste0("COM_", 1975)
)
#> New names:
#> * `` -> `..2`
#> * `` -> `..3`
#> * `` -> `..4`
#> * `` -> `..5`
#> * `` -> `..6`
#> * … and 40 more
#> # A tibble: 38,227 x 46
#>    `Recensement de… ..2   ..3   ..4   ..5   ..6   ..7   ..8   ..9   ..10 
#>    <chr>            <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr>
#>  1 TABLEAU COMMUNA… <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  2 France métropol… <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  3 Découpage géogr… <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  4 <NA>             <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  5 Note de lecture… <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  6 <NA>             <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  7 Documentation    <NA>  Modi… <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  8 © Insee          Sour… <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#>  9 <NA>             <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA> 
#> 10 <NA>             <NA>  <NA>  <NA>  <NA>  AGE   00    00    05    05   
#> # … with 38,217 more rows, and 36 more variables: ..11 <chr>, ..12 <chr>,
#> #   ..13 <chr>, ..14 <chr>, ..15 <chr>, ..16 <chr>, ..17 <chr>,
#> #   ..18 <chr>, ..19 <chr>, ..20 <chr>, ..21 <chr>, ..22 <chr>,
#> #   ..23 <chr>, ..24 <chr>, ..25 <chr>, ..26 <chr>, ..27 <chr>,
#> #   ..28 <chr>, ..29 <chr>, ..30 <chr>, ..31 <chr>, ..32 <chr>,
#> #   ..33 <chr>, ..34 <chr>, ..35 <chr>, ..36 <chr>, ..37 <chr>,
#> #   ..38 <chr>, ..39 <chr>, ..40 <chr>, ..41 <chr>, ..42 <chr>,
#> #   ..43 <chr>, ..44 <chr>, ..45 <chr>, ..46 <chr>
```

<sup>Created on 2018-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

There have been several "me too" comments. I invite those folks to install the dev version of readxl and see if it fixes things for their file too. If not, please open a new issue with a link to your xls or attach it in a zip archive.
