### ISSUE TITLE
read_excel() terminates the session when this file is read

### ISSUE THREAD

**Issue by doctsh** [tidyverse/readxl#485]
When I read some excel files (XLS) it terminates the session. Strangely if i open xls file using MS Excel and save it manually then it is read by read_excel. As i have 100s of file I am not able to do each file. Have anybody faced such issue? any alternatives? TIA

**Comment by jennybc** [comment]
What exactly does this look like? Is there an error message or can you capture a screenshot? Are any of the offending files available somewhere? Can you study the problem under different versions of readxl to determine if this is a regression?
