### ISSUE TITLE
Data Time format

### ISSUE THREAD

**Issue by KS2907** [tidyverse/readxl#487]
I am trying to read a simple excel file with number of mixed type columns including two date columns, where the date stamp is in the following format
```r
2012-01-01 00:00:00
```
However the call to read_excel(filename) only result in reading the date part of the stamp as seen by 

Inspecting the resulting data frame shows that it is being read in POSIXct format. 

Viewing a field generates the following output:
```r
> df$`Estimated Arrival Date`[1]
[1] "2012-01-01 UTC"
```
And when I write this data frame into another excel file using write_excel_csv(df, filename), I get the following weird format in the resulting excel file

```r
2013-01-01T00:00:00Z
```
How do I read the data/time stamps in the same format and print it likewise?

Regards
Kam

**Comment by jennybc** [comment]
It would be very helpful to see more of your code, with specific input and expected/desired output, and an indicative file. So far it looks like you need to seize control of date-time formats re printing/writing, i.e. I'm not convinced there's a problem at import.

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box. `.xlsx` is a supported file type. You'll need to zip or gzip `.xls` so it appears as `.zip` or `.gz`.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by KS2907** [comment]
Thanks Jenny and sorry for not providing a complete example of the problem. 
You are right, I believe the issue was with the formatting in the write function. Replacing 
```r
write_csv_excel() 
```
with 
```r
options(xlsx.datetime.format = "yyyy-mm-dd HH:mm:ss")
write.xlsx2()
```
solves the problem for me.

Kam
