### ISSUE TITLE
col_types = cols() argument works in read_csv but not read_excel

### ISSUE THREAD

**Issue by SebVen** [tidyverse/readxl#490]
The argument `col_types = cols()` doesn't work for read_excel, even though it works fine for read_csv. I'm unsure if this is intentional.
To reproduce:

`read_csv("../data.csv", col_names = TRUE, col_types = cols(.default = col_integer()))`

works fine.

`read_excel("../data.excel", sheet = 1, col_types = cols(.default = col_integer()))`
`#Error in check_col_types(col_types) : is.character(col_types) is not TRUE`

**Comment by cderv** [comment]
Also, I don't think that the specification of columns works the same in readr and readxl. 
Check the documentation:
https://readxl.tidyverse.org/articles/cell-and-column-types.html

You can't provide `col_types` using `cols` function. As stated in the error message, you need to provide a string. `col_types` expects one of "skip", "guess", "logical", "numeric", "date", "text" or "list". See also the [help](https://readxl.tidyverse.org/reference/read_excel.html#arguments) of the function. In your case, you should use `col_types =  "integer"` to use this column types for all column.

Can you try that ? Thanks!

**Comment by SebVen** [comment]
@batpigandme aplogies, that was a mistake, I meant `.xlsx`

@cderv I suspected as much. 
I find the method for readxl rather impractical when dealing with a lot of columns.

The `read_csv()` function does allow `cols` and which is a real advantage:

`read_csv("../data.csv", col_names = TRUE, col_types = cols(.default = col_integer(), Var1 = col_double(), Var3 = col_character()))`

As you probably already know, you can define variable type by variable name in `read_csv,` which is much more convenient. Adding this argument to the readxl package will also help standardise arguments across the `read_` family of functions in tidyverse

**Comment by batpigandme** [comment]
Yeah, this is an existing issue (see https://github.com/tidyverse/readxl/issues/198), and one that's being worked on actively.
Since we try to keep one issue open per topic, I'm closing this in favour of #198, but you can feel free to add anything you think is missing over there.
