### ISSUE TITLE
Multiple header rows mini-vignette?

### ISSUE THREAD

**Issue by apreshill** [tidyverse/readxl#492]
Hi Jenny,

I accept the challenge to contribute a mini-vignette 😄  Do you have a preference on dataset? Would you prefer a small toy example dataset as a demo (as opposed to the data I used in my [blog post](https://alison.rbind.io/post/read-multiple-header-rows/))?

Thanks!
Alison

**Comment by jennybc** [comment]
I just added a second sheet to the clippy.xls[x] example that already ships with readxl. I think it's sufficiently annoying? See what you think. I'm happy to get suggestions for change or if you want me to add a couple of rows.

<img width="288" alt="screen shot 2018-07-10 at 1 44 29 pm" src="https://user-images.githubusercontent.com/599454/42488141-7d362756-8447-11e8-8ad2-7c0788eba45f.png">

**Comment by jennybc** [comment]
I assume it will go something like this and here's how to access the example sheet:

``` r
library(magrittr)
library(readxl)

(cnames <- readxl_example("clippy.xlsx") %>% 
    read_excel(sheet = 2, n_max = 0) %>% 
    names())
#> [1] "name"    "species" "death"   "weight"

readxl_example("clippy.xlsx") %>% 
  read_excel(sheet = 2, skip = 2, col_names = cnames)
#> # A tibble: 1 x 4
#>   name   species   death               weight
#>   <chr>  <chr>     <dttm>               <dbl>
#> 1 Clippy paperclip 2007-01-01 00:00:00    0.9
```

Created on 2018-07-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by brianwdavis** [comment]
Thanks for taking this on @apreshill! 

If you look at the issue I opened (#486), I often have files where the first row isn't enough header to uniquely identify a variable, and we often need the data dictionary to be kept with the name. Following the `clippy.xls` example, I suppose I'd want to have the column `"death"/"(date is approximate)"` changed to `"date"/"of death"` and another column added `"date"/"of birth"` (with value 1/1/1997). However I can also see where this would add unnecessary complexity.

My suggestion if you want to add that as a use case is to move the metadata extraction up to Step 1, and then `full_cnames <- clippy_meta %>% lapply(paste, sep = "_") %>% unlist()` and use that as an alternative option for the names in Step 2.

**Comment by apreshill** [comment]
Hi @brianwdavis and @jennybc -

This sounds good, and a nice solution- although for my own use cases (I've had several), the simpler solution was what I needed. So I'm wondering if I could frame this solution using `paste` as still an alternative, after showing the basic two steps first. It feels like the first hurdle is understanding how you can change the default args to the function, and use the function twice with different args each time, then from there adding complexity for more specific use cases. But, I'm not totally set on this sequence- @jennybc ?

Thanks!
Alison

**Comment by jennybc** [comment]
I'm hoping this vignette could kick off with the simplest possible example of this phenomenon  + solution, then ramp up to some of the more complicated (and realistic) ones. Hopefully @brianwdavis will contribute his.

I'm at useR! right now and not in a position to review this at the moment. I think the main thing is to coordinate what needs to be true about, e.g., the clippy example sheet to support the vignette. It's always possible to add a 3rd sheet with even more pathological behaviour.

**Comment by brianwdavis** [comment]
I think the clippy.xlsx file and mini-vignette (vignette-ette?) look great as is for getting the concept out in the wild.

**Comment by jennybc** [comment]
@brianwdavis now that #494 is merged, you are welcome to make a PR adding your more complicated example.

**Comment by jennybc** [comment]
Closing this, since we have a useful basic article now. @brianwdavis (or anyone): I remain open to PRs that extend the article with common, but more complicated situations.
