### ISSUE TITLE
No vignettes appearing in dev version 1.1.0.9000

### ISSUE THREAD

**Issue by ddheart** [tidyverse/readxl#497]
Hi, I installed the dev version on my machine partially to patch the read error I see on some other issues 'Error in read_fun...', but also because I saw there's a new vignette on multi-header rows. For some reason I don't see the vignette on the help Index page under "Documentation for package ‘readxl’ version 1.1.0.9000", even though I called 'install_github('tidyverse/readxl')' and installed the right version.

I see the most recent commit here, am I doing something wrong?
https://github.com/tidyverse/readxl/commit/75cffbf7a66619f9b901aec5027f9d205a270021

**Comment by cderv** [comment]
When installing from github, I think you need to explicitly ask to build the vignette
`devtools::install_github("tidyverse/readxl", build_vignettes = TRUE)`
When I do that locally, the vignette is present.

**Comment by jennybc** [comment]
I endorse @cderv's answer.
