### ISSUE TITLE
Cannot read minimalistic XLSX file

### ISSUE THREAD

**Issue by j6t** [tidyverse/readxl#506]
`read_excel` fails to read the file [styles-sharedStrings-absent.xlsx](https://github.com/tidyverse/readxl/files/2378216/styles-sharedStrings-absent.xlsx). The file is accepted by Microsoft Excel and LibreOffice.

The error message is

```
Error in read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  :
  Evaluation error: Couldn't find '' in 'D:\Src\readxl\tests\testthat\sheets\styles-sharedStrings-absent.xlsx'.
```

```r
library(readxl)
x <- read_excel("styles-sharedStrings-absent.xlsx")
#> Error in read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  :
#>  Evaluation error: Couldn't find '' in 'D:\Src\readxl\tests\testthat\sheets\styles-sharedStrings-absent.xlsx'.

```

**Comment by jennybc** [comment]
Thanks for providing an example.

Since I like to keep track of this stuff when I can, how does one get such a file in the real world, i.e. without a styles part?

**Comment by j6t** [comment]
Viscovery SOMine generates these files. This is a predictive modeling software developed by the company for which I work.

**Comment by jennybc** [comment]
For posterity. My reading of [ECMA-376 5th edition Part 1](https://www.ecma-international.org/publications/standards/Ecma-376.htm) confirms that the Styles Part is not an absolute requirement.

12.2 Package Structure

A SpreadsheetML package shall contain a package-relationship item and a content-type item. The package- relationship item shall have implicit relationships with targets of the following type:

  * One Workbook part (12.3.23).

The package-relationship item is permitted to have implicit relationships with targets of the following type:

  * Digital Signature Origin (§15.2.7)
  * File Property parts (§15.2.12) (Application-Defined File Properties, Core File Properties, and Custom File
Properties), as appropriate.
  * Thumbnail (§15.2.16).

The required and optional relationships between parts are defined in §12.3 and its subordinate clauses.

*and eventually ...*

12.3.20 Styles Part

An instance of this part type contains all the characteristics for all the cells in the workbook. Such information includes numeric and text formatting, alignment, font, color, and border.

A package shall contain no more than one Styles part, and that part shall be the target of an implicit relationship from the Workbook (§12.3.23) part.
