### ISSUE TITLE
When import with col_types="text", text column value is converted with unwanted additional decimal points.

### ISSUE THREAD

**Issue by hidekoji** [tidyverse/readxl#510]
Brief description of the problem

I have a xlsx file which contains data like this. Value is text column.

![image](https://user-images.githubusercontent.com/230637/47332708-0036c400-d635-11e8-95c2-1e6ddfce35a8.png)

When I import this data with  readxl::read_excel using `col_types="text"` (since the Value column is text in Excel), it convert the value to something different (132834.3  vs 132834.29999999999)

```r
library(reprex)
reprex::reprex({
tmp <- tempfile(fileext = ".xlsx")
dir.create(tempdir(), showWarnings = FALSE)
download.file("https://www.dropbox.com/s/i79v7y548bixprj/testdata10880.xlsx?dl=1", destfile = tmp, mode = "wb")
df <- readxl::read_excel(tmp, col_types = "text")
head(df[df$ID == "B",])
})

#> # A tibble: 4 x 2
#>   ID    Value             
#>   <chr> <chr>             
#> 1 B     48275.3           
#> 2 B     495824.2          
#> 3 B     132834.29999999999
#> 4 B     348842
```

**Comment by hidekoji** [comment]
I found the similar issue:
Better guessing of desired precision when coercing double to character #360

Not sure if the root cause is the same..

**Comment by kei51e** [comment]
Thanks for the research and update. 

I don't see this issue if I turn on the column data type auto detection. I sent an email to Ramon with the updates.

**Comment by jennybc** [comment]
> since the Value column is text in Excel

That is not true. FWIW these cells have format "General" in the Excel sense and contain actual numbers. 

Here is what's on disk for row 11:

``` xml
<row r="11" spans="1:2">
<c r="A11" t="s">
<v>3</v>
</c>
<c r="B11">
<v>132834.29999999999</v>
</c>
</row>
```

Cell A11 is stored as text and holds the element 3 from the shared string table, which is "B".

Cell B11 is stored as a number and holds 132834.29999999999, even though it displays as 132834.3 in Excel.

You are exporting floating point numbers as character strings when you request `col_types = "text"`.

Yes I think there is content in #360 that might help you, until or unless readxl offers richer support for trying intuit the user's desired precision when turning floating point numbers into strings.

**Comment by hidekoji** [comment]
Apologies for the belated update, I changed cell format to text but still get the same result.

https://www.dropbox.com/s/9jdmatvz797p889/testdata10880-text.xlsx?dl=0

``` r
tmp <- tempfile(fileext = ".xlsx")
dir.create(tempdir(), showWarnings = FALSE)
download.file("https://www.dropbox.com/s/9jdmatvz797p889/testdata10880-text.xlsx?dl=1", destfile = tmp, mode = "wb")
df <- readxl::read_excel(tmp, col_types = "text")
head(df[df$ID == "B",])
#> # A tibble: 4 x 2
#>   ID    Value             
#>   <chr> <chr>             
#> 1 B     48275.3           
#> 2 B     495824.2          
#> 3 B     132834.29999999999
#> 4 B     348842
```

<sup>Created on 2019-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

If the root cause is still the same as #360, please close the issue but I just wanted to double check.

**Comment by jennybc** [comment]
I think changing the cell format to text *after the fact* doesn't change the data on disk. If it had lots of decimals places, then those remain. To have the result you want, the cell needs to really be declared as text *before* the data goes in.
