### ISSUE TITLE
"NA" in date-formatted column prevents read_excel from interpreting it as a date

### ISSUE THREAD

**Issue by rrohwer** [tidyverse/readxl#511]
If there are "na" values in a date-formatted excel column, as in "NA" was typed as opposed to the cell being left blank, then readxl cannot interpret the column as a date. Forcing date with the `col_types` argument works, but leaves a ton of error messages. This isn't a huge deal since a few error messages isn't that bad, but it was tricky to troubleshoot because to me "NA" is not an obvious data entry error, and in a large spreadsheet the "NA" was hidden and it was hard to figure out why some columns were importing properly and others were not. Also, the imported character NA's look very similar to the real NA's in the RStudio View window and in the console output.

make an example excel file that looks like this:

whatever | date column | bla | bla
-- | -- | -- | --
a | 10/22/87 | 1 | w
b | 6/18/99 | 2 | x
c | NA | 3 | y
d |   | 4 | z

and read in like this:
```r
> read_excel("~/Desktop/readxl_bug_repex.xlsx")
# A tibble: 4 x 4
  whatever `date column`   bla bla__1
  <chr>    <chr>         <dbl> <chr> 
1 a        32072             1 w     
2 b        36329             2 x     
3 c        NA                3 y     
4 d        NA                4 z     
```

Or figure out that those NA's are different colors and troubleshoot like this, but have a bunch of error messages:
```r
> read_excel("~/Desktop/readxl_bug_repex.xlsx", col_types = c("guess", "date","guess","guess"))
# A tibble: 4 x 4
  whatever `date column`         bla bla__1
  <chr>    <dttm>              <dbl> <chr> 
1 a        1987-10-22 00:00:00     1 w     
2 b        1999-06-18 00:00:00     2 x     
3 c        NA                      3 y     
4 d        NA                      4 z     
Warning message:
In read_fun(path = path, sheet_i = sheet, limits = limits, shim = shim,  :
  Expecting date in B4 / R4C2: got 'NA'
```

**Comment by jennybc** [comment]
I just switched machines and don't have Excel at the moment 😱 so I can't play with this at all.

But I think things are basically working as they should, except I know the message are overwhelming (https://github.com/tidyverse/readxl/issues/361).

An initial import results in a column you regard as date importing as character. This tips you off to some text entries.

So you force it to be date. The next warning tells you examples of exactly which cells are to blame.

You can either fix the data or continue with your import. Note also there is an `na` argument where you can specify the string `"NA"`, which should allow auto-discovery of column type to work for you.

**Comment by jennybc** [comment]
In the future, if you could attach the "readxl_bug_repex.xlsx" to the issue, that would be extremely helpful. I hand-typed one but it obviously doesn't have the same properties as your re: dates, so I can't walk through your code and see the same results.

I still think things are working as planned, except for the over-messaging already mentioned above (#361).

As for the difficulty seeing the difference between true `NA`s and the character string "NA", how do you run R? I attach a screenshot from RStudio and the terminal and in both cases, the colors offer visual distinction.

<img width="664" alt="screen shot 2018-12-13 at 3 29 17 pm" src="https://user-images.githubusercontent.com/599454/49974092-97f5b780-feec-11e8-839a-95dbed1428e3.png">
