### ISSUE TITLE
feature request: specify list of columns and rows

### ISSUE THREAD

**Issue by ptoche** [tidyverse/readxl#512]
Feature request: specify columns and rows as lists/vectors, e.g. to read the first row but skip rows 2-9 before reading rows 10-100, something like:

    read_excel(...,
                     range = cell_rows(c(1, 10:100)))  

which currently does nothing or, even simpler: 

    read_excel(...,
                     range = cell_rows(1, 10:100))  

    Error in cell_rows(1, 10:100) : unused argument (10:100)

which returns an error. 

If something like this is already possible, I have missed it: I suggest adding an example to the readme file.

The ``read.xlsx`` function from package ``xlsx`` has a ``colIndex`` and a ``rowIndex`` argument that does that, and I have found it convenient.

**Comment by ptoche** [comment]
Unless there are objections to this suggestion of course...

The part of the code that would need to be expanded is [here](https://github.com/tidyverse/readxl/blob/763ca6d42ade5b1ede77d57b41d596b3306ab8a1/R/read_excel.R#L219). 

For reference, the relevant portion of code from ``xlsx`` is [here](https://github.com/cran/xlsx/blob/43419d1e95bd484c538ce6d42cfa4c12fd91fdfe/R/Cell.R#L22).

**Comment by jennybc** [comment]
This is very incompatible with readxl's focus on reading a single rectangle and it would involve nontrivial change on the C/C++ side.

If I am correctly guessing what this is about, you might be interested in the two-pass solution described in this article:

https://readxl.tidyverse.org/articles/articles/multiple-header-rows.html

**Comment by ptoche** [comment]
Thanks for the feedback. I see. Oh well... I didn't realize it would be that tricky to code it in.  

Thanks for the link. Indeed I've had to read the data twice in a manner similar to that described in the link (except without the ``%>%`` bits).
