### ISSUE TITLE
read_xlsx doesn't honour `trim_ws`

### ISSUE THREAD

**Issue by hroptatyr** [tidyverse/readxl#514]
## works, i.e. whitespace is *not* trimmed.
    read_excel('.xlsx-file', trim_ws=F)

    ## doesn't work, whitespace is always trimmed
    read_xls('.xls-file', trim_ws=F)

    ## doesn't work, whitespace is trimmed regardless.
    read_xlsx('.xlsx-file', trim_ws=F)

It's obvious that the misbehaviour is either a documentation problem (are `read_xls` and `read_xlsx` meant to have a `trim_ws` parameter?) or a code problem when calling the `read_excel_` wrapper (the `trim_ws` parameter is not passed along at all).

**Comment by jennybc** [comment]
You are correct with this:

> a code problem when calling the read_excel_ wrapper (the trim_ws parameter is not passed along at all

I've fixed and will push soon, but also need to address something else first ...
