### ISSUE TITLE
Compact string representation for col_types (feature request)

### ISSUE THREAD

**Issue by pm321** [tidyverse/readxl#515]
readr has a nice method for parsing column types - compact string representation:
“Alternatively, you can use a compact string representation where each character represents one column: c = character, i = integer, n = number, d = double, l = logical, D = date, T = date time, t = time, ? = guess, or _/- to skip the column.”

I have tried this with readxl but get an error, for example:
Illegal column type: 'cciiiiccccclccc' [1]

Would it be possible to incorporate compact string representation for col_types in readxl?

**Comment by jennybc** [comment]
Yes this is #198
