### ISSUE TITLE
Feature Request: ability to read from HDFS

### ISSUE THREAD

**Issue by awwsmm** [tidyverse/readxl#518]
readxl is currently unable to connect to an HDFS installation and read files from the Hadoop Distributed File System. This would be a very nice feature to have.

**Comment by jennybc** [comment]
Can you elaborate more about this?

Are you really using Excel with Hadoop?

**Comment by awwsmm** [comment]
Yes?

**Comment by jennybc** [comment]
I think what you are asking for is a special flavour of https://github.com/tidyverse/readxl/issues/278, but, as you say, the missing piece seems to be something that exposes an hdfs file to R in a suitable way.

**Comment by cderv** [comment]
FWIW, we use the webhdfs api (also called httpfs) to get a file from hdfs into R. There is an old 📦  that help called [rwebhdfs](https://github.com/saurfang/rwebhdfs) that implements an R API using Rcurl. It is rather simple to use httr 📦 directly to query the api [httpfs](https://hadoop.apache.org/docs/current/hadoop-hdfs-httpfs/index.html). I don't know if the api is available by default on every hadoop cluster.

Acessing HDFS from HTTP is not suitable in every situation. For more advanced usecase, we use sparklyr from a gateway node and send jobs in the cluster.  

I thought it could help to share.

**Comment by awwsmm** [comment]
Thanks @cderv. I looked into this and ended up finding `curl`, which does the job. For posterity, I'll write out what I did below. From within the SparkR shell, you can do:

```R
  > install.packages("xlsx")
  > install.packages("curl")

  > library(xlsx)
  > library(curl)

  > curlfile <- curl_fetch_memory("http://localhost:9870/webhdfs/v1/example_data/example_xlsx.xlsx?op=OPEN")
  > tmpfile <- tempfile("name_of_temp_file")
  > tt <- file(tmpfile, "wb")
  > writeBin(curlfile$content, tt)
  > close(tt)
  > xlsx <- createDataFrame(read.xlsx(tmpfile, sheetIndex=1))

  > xlsx
  SparkDataFrame[Time:timestamp, dissolvedO2:double, pH:double, outletN2:doub...

  > head(xlsx)
                   Time dissolvedO2       pH outletN2 outletCO2 outletO2
  1 2018-01-01 15:00:00    49.56497 7.056501 60.14372  10.32145 28.80335
  2 2018-01-01 15:00:30    49.04355 7.056607 60.21205  10.38589 28.80089
  3 2018-01-01 15:01:00    49.78669 7.056591 60.24343  10.37360 28.84372
  ...
```

Where `http://localhost:9870/webhdfs/v1/` is the default for a standalone Spark installation. `9870` is the default HTTP port and any file path on `hdfs://` must be preceded by `webhdfs/v1`. The `?op=OPEN` is necessary at the end in order to open and read the file. So the file I accessed above is located at:

```
hdfs://localhost:9000/example_data/example_xlsx.xlsx
```

or

```
C:\Users\andrew>hadoop fs -ls /example_data
Found 5 items
-rw-r--r--   1 andrew supergroup       2848 2018-11-19 16:23 /example_data/example_csv.csv
-rw-r--r--   1 andrew supergroup       7882 2018-11-19 16:23 /example_data/example_sql_linux.txt
-rw-r--r--   1 andrew supergroup      13958 2018-11-19 16:23 /example_data/example_sql_windows.txt
-rw-r--r--   1 andrew supergroup       3809 2018-11-16 16:35 /example_data/example_text.md
-rw-r--r--   1 andrew supergroup      14381 2018-11-19 16:24 /example_data/example_xlsx.xlsx
```

**Comment by awwsmm** [comment]
Not ideal, because it downloads the file, writes to a temporary file, and then reads that temporary file, but it's good enough for me for now. And the Excel file can be packaged as a `SparkDataFrame` object.

**Comment by cderv** [comment]
Glad it works ! 

I think with `httr` it would look like that 
```r
library(httr)
tmpfile <- tempfile("name_of_temp_file")
res <- GET("http://localhost:9870/webhdfs/v1/example_data/example_xlsx.xlsx?op=OPEN", write_disk(tmpfile))
```

When ready to read from connection (#278), the downloading would still be required but writing to disk would not be necessary anymore as able to read from memory or raw content.

**Comment by jennybc** [comment]
I'm going to close this. It is now linked to and explicitly listed in #278 and will get revisited when we get there.
