### ISSUE TITLE
Option to Stop reading at first Empty Row

### ISSUE THREAD

**Issue by N1h1l1sT** [tidyverse/readxl#521]
As of now, I am not aware of any way to make `readxl::read_excel()` to stop reading rows when it meets a row that is empty (all cells at that particular row are empty)

This is, for instance, the default behaviour of `excel.link::xl.read.file()` and it helps a lot when people create different things on the same sheet, but you only want to capture the first one.

---

What happens now:

```r
readxl::read_excel("SpreadSheet.xlsx")
```
|Col1|Col2|
|-----|-----|
|1     |1     |
|2     |2     |
|       |       |
|f      |f      |
|g     |g     |

What I suggest as an option:
```r
readxl::read_excel(
  "SpreadSheet.xlsx",
  StopAtFirstEmptyLine = TRUE
)
```
|Col1|Col2|
|-----|-----|
|1     |1     |
|2     |2     |

What I do now is:
```r
  MyDF <- readxl::read_excel("SpreadSheet.xlsx")

  FirstEmptyRow <- NA
  tmpDFBool <- sapply(MyDF, function(x) is.na(x) | is.null(x))
  for (i in 1:NROW(tmpDFBool)) {
    if (all(tmpDFBool[i, ]) == TRUE) {
      FirstEmptyRow <- i - 1
      break
    }
  }

  if (!is.na(FirstEmptyRow)) MyDF <- MyDF[1:FirstEmptyRow,]
```

So instead of reading less than the whole excel sheet, now the whole excel sheet is returned, then I apply a function to the whole sheet again, and then I return a new object which is a subset of the original.
So complexity-wise it went from `<n` to something like `2n + c`

**Comment by jennybc** [comment]
Sheet geometry was heavily reworked in v1.0.0 and it is very intentional that we don't drop (or stop) for embedded empty rows. The readxl design principles re: Sheet Geometry are here:

https://readxl.tidyverse.org/articles/sheet-geometry.html

So within our paradigm, you'll either need to specify `n_max` or `range` for this scenario.

**Comment by N1h1l1sT** [comment]
Thank you for the quick reply!
I read this page but I'm unsure as to which is the best way to handle this.

Could you provide a snippet for this (perhaps adding it to that very page as an example?)
My approach is definitely bad.

That said, readxl is so much faster than the rest, that even when doing things the way I did it, it's still significantly faster. But I would like to use the optimal way nonetheless.

**Comment by jennybc** [comment]
I think your basic idea is sound, although I would not use a `for`/`while` approach. I'd probably do something more like the logic inside `janitor::remove_empties()` re: detecting empty rows (and therefore the location of the first):

https://github.com/sfirke/janitor/blob/3c7bdf07cb4cedb87c00e86260532ac308705114/R/remove_empties.R#L22-L24

Bigger picture solutions: if you have influence over the workbook, exert pressure to design it differently, i.e. to keep clean data on its own worksheet. readxl will also eventually gain the ability to read a rectangle from a named region, in which case someone can annotate data rectangles in the xlsx file for easier import.
