### ISSUE TITLE
bug (?)  with read_excel, adding characters to "numeric" character string

### ISSUE THREAD

**Issue by mcSamuelDataSci** [tidyverse/readxl#525]
read_excel adds characters when reading in certain character strings, as shown below.  The correct string "1.1" shows up as "1.1000000000000001" when reading in an Excel version of this file.   There is nothing special whatsoever about the Excel (or the .csv) file--for this example it was generated by saving the .csv file as .xlsx in Excel.  The .csv file looks like this:
```
MSSA_ID,COUNTY
1.1,Alameda
1.2,Alameda
2a,Alameda
2b,Alameda
2c,Alameda
2d,Alameda
2e,Alameda
1.1,Somewhere else
```
 

```
> read.csv(csvExample)
  MSSA_ID         COUNTY
1     1.1        Alameda
2     1.2        Alameda
3      2a        Alameda
4      2b        Alameda
5      2c        Alameda
6      2d        Alameda
7      2e        Alameda
8     1.1 Somewhere else


> read_excel("excelExample.xlsx")
# A tibble: 8 x 2
  MSSA_ID            COUNTY        
  <chr>              <chr>         
1 1.1000000000000001 Alameda       
2 1.2                Alameda       
3 2a                 Alameda       
4 2b                 Alameda       
5 2c                 Alameda       
6 2d                 Alameda       
7 2e                 Alameda       
8 1.1000000000000001 Somewhere else
```

Reproducible example: 

```r
csvExample <- "https://raw.githubusercontent.com/mcSamuelDataSci/CACommunityBurden/master/myUpstream/upData/caMSSAexample.csv"
read.csv(csvExample)            

library(readxl)
githubURL <- "https://raw.githubusercontent.com/mcSamuelDataSci/CACommunityBurden/master/myUpstream/upData/caMSSAexample.xlsx"
download.file(githubURL,"excelExample.xlsx", method="curl")
read_excel("excelExample.xlsx")
```

**Comment by mcSamuelDataSci** [comment]
Thanks so much for your super quick reply.  There is nothing I have be able to do to the excel file, including formatting the column as text, such that it reads in properly. And, if save it as .csv, and read that into R, it is just fine (i.e. that cell as 1,.1)--this seems weird since if that cell is stored as "1.1000000000000001" then it seems it would write it out as that in the .csv, but clearly beyond my limits. Can you tell me how I can see the excel file in terms of what is "on disk"?  Of course if i just try Wordpad or something, it is binary gibberish.   Thanks!

**Comment by batpigandme** [comment]
> Can you tell me how I can see the excel file in terms of what is "on disk"?

Change the xlsx file extension to zip (see [SO thread here](https://stackoverflow.com/a/8984319)), and then unzip it. You'll get a folder with contents that look like this:
![image](https://user-images.githubusercontent.com/831732/49797049-53abc100-fd0c-11e8-9679-a0dc96ee3f21.png)

The `sheet1.xml` file will show you the xml on disc.

**Comment by jennybc** [comment]
I have made an R package that I use to inspect the contents of Excel (or Word or PowerPoint):

https://github.com/jennybc/excelgesis

I unpack, hyperlink, and browse your workbook with `excelgesis::xg_inspect("~/Downloads/caMSSAexample.xlsx")`.

> There is nothing I have be able to do to the excel file, including formatting the column as text, such that it reads in properly

It is true that converting a cell with the number 1.1000000000000001 to text cannot not automatically turn it into "1.1". Now Excel makes the same mistake that readxl makes: it turns the number into 
1.1000000000000001". Indeed this explains exactly what is happening with readxl. None of us know that the 0.0000000000000001 is spurious. You need to revisit cells with this problem and re-enter, e.g., "1.1".

If a column is set up as text from the start, then this prevents the problem from ever occurring. I see this a lot with columns that are really, e.g. product codes that just happen to use digits.

> And, if save it as .csv ...

Yeah, here Excel uses the same logic that it is using in the GUI, where it decides to show/give you "1.1" even though the cell data holds 1.1000000000000001.
