### ISSUE TITLE
Community reviews

### ISSUE THREAD

**Issue by jennybc** [tidyverse/readxl#529]
Thanks @jmostipak @gdequeiroz for taking a look!

I'm interested in knowing that the package seems to work normally for you and that any new aspect is well-explained.

You need to install the dev version from GitHub, via an up-to-date devtools. You might need to re-install multiple times, if we iterate:

``` r
# install.packages("devtools")
devtools::install_github("tidyverse/readxl")
```

Examples of tasks that would be very useful & informative. I don't expect you to do them all, just pick a couple and report back!

  * Read the NEWS section about changes in this version. In NEWS.md.
  * Run an existing script of yours. Everything OK?
  * Explicitly use dev readxl with CRAN tibble (via `install.packages()`) vs with dev tibble (via `install_github("tidyverse/tibble")`. Everything OK?
  * Using your usual use of help, pkgdown site, README, whatever, do the docs get the job done or is there some gaping hole that frustrates you?
  * Do you have any scripts where you do post-import gymnastics around name repair? If so, can you modify one to do this more cleanly via `.name_repair` in `read_excel()`?

**Comment by gdequeiroz** [comment]
@jennybc Thank you for listing and specifying the tasks.

**Comment by jmostipak** [comment]
yes, thank you - I'll get some of these knocked out this weekend!

**Comment by jennybc** [comment]
Yes to try out `.name_repair`, you will need to install tibble from GitHub.

In the docs, I keep saying "tibble v2.0.0" because that is what it will be released as and I want to the docs to make sense then.

But in more practical terms, today, I really mean "install the development version of tibble from GitHub".

**Comment by jmostipak** [comment]
@jennybc - I got through the following:

* I ran several existing scripts that use the `readxl` package and they all ran without any issues
* I didn't come across anything in the documentation that felt lacking - in going through everything I found the information that I needed quickly and without any extensive searching. In other words, the documentation addressed all of my questions and I didn't need to use Google/SO/Community site for clarification
* so `.name-repair` is relatively new to me and now my new favorite thing to do in R! I have a series of scripts that are just awful in terms of naming (think full sentences as column headers) and this is a cleaner, more efficient solution that address the bulk of the issues on import 🙌

**Comment by jennybc** [comment]
Thanks @jmostipak! So that means you had success using the `.name_repair` argument?

**Comment by jmostipak** [comment]
@jennybc I did! Everything worked really well with `.name_repair`!

**Comment by jennybc** [comment]
Thanks @gdequeiroz and @jmostipak!
