### ISSUE TITLE
Address duplicate column names

### ISSUE THREAD

**Issue by donboyd5** [tidyverse/readxl#53]
Hi,

Currently, if the column names in the first row of a spreadsheet have duplicates, read_excel allows that. It would be nice to have an option (or default behavior), similar to gdata::read.xls,  whereby instead it appends a numeric suffix. For example, if the names in the first row include c("xvar", "xvar") the respective column names would become c("xvar", "xvar.1").

Don

**Comment by kcandrews** [comment]
Seconded. This default would help me tidy up a computer generated messy spreadsheet I don't control.

**Comment by hadley** [comment]
Hmmmm, I'm not a big fan of automatically changing column names. It's pretty easy to do yourself:

```R
names(df) <- make.unique(names(df))
```

**Comment by kcandrews** [comment]
And here I was about to write a for loop... Thanks for pointing out `make.unique`!

**Comment by donboyd5** [comment]
Ah. I should have known. Thanks.

**Comment by jennybc** [comment]
Issue renamed. Presumably readxl will follow readr re: duplicate column names.
