### ISSUE TITLE
better detection of xls(x) extension types

### ISSUE THREAD

**Issue by KyleHaynes** [tidyverse/readxl#537]
Could consideration be made for detection when a user has renamed an *.xls to an *.xlsx file (or vice-versa)?

It's rare that this happens, but I have experienced this in the past when an individual just assumes that by changing the extension of a file will magically create that file type. 

In Windows, you can change an *.xlsx to an *.xls and it still opens perfectly fine in Excel but not vice versa.

It's pretty edge case, but If it's easy to implement, some users might benefit?

```r
# install.packages("writexl")
writexl::write_xlsx(iris, "a_fake.xls")

readxl::read_excel("a_fake.xls")
# Error in read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  : 
#   Failed to open c:\Temp\a_fake.xls

readxl::read_xls("a_fake.xls")
# Error in read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  : 
#   Failed to open c:\Temp\a_fake.xls

readxl::read_xlsx("a_fake.xls")
# Yay, this works.
# # A tibble: 150 x 5
#    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#           <dbl>       <dbl>        <dbl>       <dbl> <chr>  
#  1          5.1         3.5          1.4         0.2 setosa 
#  2          4.9         3            1.4         0.2 setosa 
...
```

**Comment by jennybc** [comment]
readxl exports `format_from_signature()` which ignores file extension and looks at the file's Magic Number. In a troubleshooting situation, you can run this directly or recommend the user to run this. This is as far as we will go here, i.e. I'm not going to second guess or bypass extensions in the main functions.

``` r
library(readxl)

file.copy(readxl_example("datasets.xlsx"), "datasets.WTF")
#> [1] TRUE

format_from_signature("datasets.WTF")
#> [1] "xlsx"
```

<sup>Created on 2018-12-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
