### ISSUE TITLE
Ignore total lines

### ISSUE THREAD

**Issue by stephlocke** [tidyverse/readxl#54]
It's possible to add total lines to excel tables, and these can have aggregations that differ in type to the column it's aggregating. 

At the moment total lines are being read and cause errors on loading when the data types differ.

Ideally these should not be read at all (or optionally loaded).

**Comment by hadley** [comment]
How would you distinguish a total line from a data line?

**Comment by stephlocke** [comment]
In the underlying xml (for an .xlsx) it has a table relationship xml which
includes the attribute totalsRowCount.

```<table xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
id="1" name="Table1" displayName="Table1" ref="A1:B4" totalsRowCount="1">
...
</table>```

Not sure if that's helpful in terms of how you're interacting with the
 spreadsheets


Steph Locke

@SteffLocke <https://twitter.com/stefflocke> | LinkedIn
<http://uk.linkedin.com/in/stephanielocke/> | itsalocke.com | 07951 787 022
SQL Cardiff <http://www.meetup.com/Cardiff-SQL-Server-User-Group> | CaRdiff
R <http://www.meetup.com/Cardiff-R-User-Group/> | diff.NET
<http://www.meetup.com/diff-NET/> | SQLRelay <http://sqlrelay.co.uk>



On 9 April 2015 at 20:22, Hadley Wickham <notifications@github.com> wrote:

> How would you distinguish a total line from a data line?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/readxl/issues/54#issuecomment-91333069>.
>

**Comment by stephlocke** [comment]
In the underlying xml (for an .xlsx) it has a table relationship xml which
includes the attribute totalsRowCount.

```
<table xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
id="1" name="Table1" displayName="Table1" ref="A1:B4" totalsRowCount="1">
...
</table>
```

Not sure if that's helpful in terms of how you're interacting with the spreadsheets. [Example excel turned to it's zip](https://www.dropbox.com/s/gtdkuj6yi2ikrz6/test.zip?dl=0)

**Comment by hadley** [comment]
Does the ref A1:B4 include the totals row?

I'm not currently using the tables element at all, but it might make sense to expose this too - it might be nice to have a way to print out all the tables in each worksheet. Do you happen to know if tables happen automatically or do you create them manually?

**Comment by stephlocke** [comment]
Row 4 is the Total row, yes

Tables aren't automatic - you make them with the Format as Table option.
It's incredibly handy functionality. It takes care of formatting, adds
declarative syntax e.g. MyTable[Mycolum], and since it's all basically
dynamic named ranges under the hood, it greatly reduces risk of errors in
formulae.

Steph Locke

@SteffLocke <https://twitter.com/stefflocke> | LinkedIn
<http://uk.linkedin.com/in/stephanielocke/> | itsalocke.com | 07951 787 022
SQL Cardiff <http://www.meetup.com/Cardiff-SQL-Server-User-Group> | CaRdiff
R <http://www.meetup.com/Cardiff-R-User-Group/> | diff.NET
<http://www.meetup.com/diff-NET/> | SQLRelay <http://sqlrelay.co.uk>

**Comment by jennybc** [comment]
@stephlocke Will you share a good example?

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Preferably stripped down to the minimal size and complexity to demonstrate your point. And, obviously, stripped of any sensitive data.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained. *Currently GitHub-only, but going to CRAN soon.*
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide the xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by jennybc** [comment]
We're not going to implement this in readxl at this time. The focus is clearly on reading static data.

I think this functionality makes more sense to build into packages that target tricky spreadsheets and sheet logic, e.g. [tidyxl](https://github.com/nacnudus/tidyxl) and the [rsheets packages](https://github.com/rsheets).
