### ISSUE TITLE
Dates before `1899-12-30` are read as `NA`.

### ISSUE THREAD

**Issue by ramiromagno** [tidyverse/readxl#547]
Dates before `1899-12-30` are read as `NA`.

```r
library(readxl)
foo <- read_excel("foo.xlsx", col_types = c("text", "date"))
```
[foo.xlsx](https://github.com/tidyverse/readxl/files/2825640/foo.xlsx)

**Comment by cderv** [comment]
Hi, 

I am not sure date before 1900 are even supported in Excel (see [about date system in Excel](https://support.microsoft.com/en-us/help/214330/differences-between-the-1900-and-the-1904-date-system-in-excel)). I believe dates are stored in numeric with 1 being _01/01/1900_. Negative number means nothing in Excel. 
When I open your file in excel, i got negative number and it shows at `########` with a warning.
![image](https://user-images.githubusercontent.com/6791940/52180002-1e3dc400-27e1-11e9-8e62-e349e9f488b9.png)

I am not sure `readxl` could deal with that, and should, as excel does not.
I think for this kind of case where you want to deal with specific date system, you'll have to convert manually. 

``` r
url <- "https://github.com/tidyverse/readxl/files/2825640/foo.xlsx"
temp_xls <- tempfile(fileext = ".xlsx")
download.file(url, temp_xls, mode = "wb")

# we got negative value for the date 
readxl::read_xlsx(temp_xls, col_types = c("text", "text"))
#> # A tibble: 91 x 2
#>    id    date 
#>    <chr> <chr>
#>  1 1     -29  
#>  2 2     -28  
#>  3 3     -27  
#>  4 4     -26  
#>  5 5     -25  
#>  6 6     -24  
#>  7 7     -23  
#>  8 8     -22  
#>  9 9     -21  
#> 10 10    -20  
#> # ... with 81 more rows

# with warnings
readxl::read_xlsx(temp_xls, col_types = c("text", "numeric"))
#> # A tibble: 91 x 2
#>    id     date
#>    <chr> <dbl>
#>  1 1       -29
#>  2 2       -28
#>  3 3       -27
#>  4 4       -26
#>  5 5       -25
#>  6 6       -24
#>  7 7       -23
#>  8 8       -22
#>  9 9       -21
#> 10 10      -20
#> # ... with 81 more rows
```

You can read as numeric and convert in R

``` r
# from you file
origin_from_file <- as.Date("1899-12-31")
as.Date(1, origin = origin_from_file) # 1 should be 1900-01-01
#> [1] "1900-01-01"

# convertion happens in R
# read as numeric with warnings
```

``` r
tab <- readxl::read_xlsx(temp_xls, col_types = c("text", "numeric"))
tab$date <- as.Date(tab$date, origin_from_file)
tab
#> # A tibble: 91 x 2
#>    id    date      
#>    <chr> <date>    
#>  1 1     1899-12-02
#>  2 2     1899-12-03
#>  3 3     1899-12-04
#>  4 4     1899-12-05
#>  5 5     1899-12-06
#>  6 6     1899-12-07
#>  7 7     1899-12-08
#>  8 8     1899-12-09
#>  9 9     1899-12-10
#> 10 10    1899-12-11
#> # ... with 81 more rows
```

<sup>Created on 2019-02-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Hope it helps.

**Comment by ramiromagno** [comment]
hi @cderv 

Thank you for your quick reply!

In my case, I generated that `xlsx` in Libreoffice, not in Excel. Because I did not see any  `######` cells in Libreoffice I am guessing it handles it just okay. Anyhow, the motivation for this issue actually came from a question posted in stackoverflow: https://stackoverflow.com/questions/54502851/replace-na-with-date-in-r?noredirect=1#comment95812483_54502851.

But perhaps the warning (`"NA inserted for impossible 1900-02-29 datetime"`) could be changed to best reflect the problem here.

**Comment by cderv** [comment]
interesting. 🤔 
As I was wondering how `openxlsx` deals with that, I tried. At first it did not worked either but I saw that you excel file column _date_ is not of type `DATE` in excel but _personalized_. I converted manually to short DATE type, and it worked with `openxlsx` 📦 

``` r
url <- "https://github.com/tidyverse/readxl/files/2825640/foo.xlsx"
temp_xls <- tempfile(fileext = ".xlsx")
download.file(url, temp_xls, mode = "wb")
# Open file and change column date to DATE type
# shell.exec(temp_xls)
```

``` r
# openxlsx read it correcly
openxlsx::read.xlsx(temp_xls, detectDates = TRUE)
#>    id       date
#> 1   1 1899-12-01
#> 2   2 1899-12-02
#> 3   3 1899-12-03
#> 4   4 1899-12-04
#> 5   5 1899-12-05
#> 6   6 1899-12-06
#> 7   7 1899-12-07
#> 8   8 1899-12-08
#> 9   9 1899-12-09
#> 10 10 1899-12-10
#> 11 11 1899-12-11
#> 12 12 1899-12-12
#> 13 13 1899-12-13
#> 14 14 1899-12-14
#> 15 15 1899-12-15
#> 16 16 1899-12-16
#> 17 17 1899-12-17
#> 18 18 1899-12-18
#> 19 19 1899-12-19
#> 20 20 1899-12-20
#> 21 21 1899-12-21
#> 22 22 1899-12-22
#> 23 23 1899-12-23
#> 24 24 1899-12-24
#> 25 25 1899-12-25
#> 26 26 1899-12-26
#> 27 27 1899-12-27
#> 28 28 1899-12-28
#> 29 29 1899-12-29
#> 30 30 1899-12-30
#> 31 31 1899-12-31
#> 32 32 1900-01-01
#> 33 33 1900-01-02
#> 34 34 1900-01-03
#> 35 35 1900-01-04
#> 36 36 1900-01-05
#> 37 37 1900-01-06
#> 38 38 1900-01-07
#> 39 39 1900-01-08
#> 40 40 1900-01-09
#> 41 41 1900-01-10
#> 42 42 1900-01-11
#> 43 43 1900-01-12
#> 44 44 1900-01-13
#> 45 45 1900-01-14
#> 46 46 1900-01-15
#> 47 47 1900-01-16
#> 48 48 1900-01-17
#> 49 49 1900-01-18
#> 50 50 1900-01-19
#> 51 51 1900-01-20
#> 52 52 1900-01-21
#> 53 53 1900-01-22
#> 54 54 1900-01-23
#> 55 55 1900-01-24
#> 56 56 1900-01-25
#> 57 57 1900-01-26
#> 58 58 1900-01-27
#> 59 59 1900-01-28
#> 60 60 1900-01-29
#> 61 61 1900-01-30
#> 62 62 1900-01-31
#> 63 63 1900-02-01
#> 64 64 1900-02-02
#> 65 65 1900-02-03
#> 66 66 1900-02-04
#> 67 67 1900-02-05
#> 68 68 1900-02-06
#> 69 69 1900-02-07
#> 70 70 1900-02-08
#> 71 71 1900-02-09
#> 72 72 1900-02-10
#> 73 73 1900-02-11
#> 74 74 1900-02-12
#> 75 75 1900-02-13
#> 76 76 1900-02-14
#> 77 77 1900-02-15
#> 78 78 1900-02-16
#> 79 79 1900-02-17
#> 80 80 1900-02-18
#> 81 81 1900-02-19
#> 82 82 1900-02-20
#> 83 83 1900-02-21
#> 84 84 1900-02-22
#> 85 85 1900-02-23
#> 86 86 1900-02-24
#> 87 87 1900-02-25
#> 88 88 1900-02-26
#> 89 89 1900-02-27
#> 90 90 1900-02-28
#> 91 91 1900-03-01
# even with type changed, readxl do not read this date. 
readxl::read_xlsx(temp_xls, col_types = c("text", "date"))
#> # A tibble: 91 x 2
#>    id    date               
#>    <chr> <dttm>             
#>  1 1     NA                 
#>  2 2     NA                 
#>  3 3     NA                 
#>  4 4     NA                 
#>  5 5     NA                 
#>  6 6     NA                 
#>  7 7     NA                 
#>  8 8     NA                 
#>  9 9     NA                 
#> 10 10    NA                 
#> # ... with 81 more rows
```

<sup>Created on 2019-02-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I wonder if `readxl` should be able to pass the limitation of first date as 01/01/1900 or not 🤔 
However, for sure, the warning message is not the correct one in this case. 

So for now, `openxlsx` could work for you, until it is decided what to do in `readxl` 📦

**Comment by ramiromagno** [comment]
okay, great!

**Comment by ramiromagno** [comment]
Sure!

**Comment by cderv** [comment]
Thanks.
And take care at `openxlsx` I don't know if they handle correctly the date conversion. There is a reason this don't work in readxl for now : Dates before 1900 does not exist in excel. Also, 29/02/1900 exist in excel but not in [non-existent in real](https://support.microsoft.com/en-us/help/214326/excel-incorrectly-assumes-that-the-year-1900-is-a-leap-year)

**Comment by jennybc** [comment]
I had a quick look through this thread.

Yes, there is no such thing as a date before ~1900 as far as Excel is concerned.

Obviously there are many workarounds that people can and do use for this (lots of google hits) and that is my main advice. To be completely honest, I don't see this ever rising to top of the to do list here, i.e. supporting something that the underlying format does not.

**Comment by ramiromagno** [comment]
@jennybc: okay!

But don't you think the warning: `"NA inserted for impossible 1900-02-29 datetime"` [1] should be reserved for the 1900-02-29 issue? Right now we get that warning too for the dates before ~1900.

[1] The warning *in situ*: https://github.com/tidyverse/readxl/blob/5fbe9975d3afb97224332489f05d6688974e79a8/src/utils.h#L67

**Comment by jennybc** [comment]
@ramiromagno Yeah, that's definitely a bad message. Would you be willing to open a new issue just about that? That would be helpful.

**Comment by ramiromagno** [comment]
@jennybc: Sure!
