### ISSUE TITLE
New .name_repair and col_name = FALSE creates unusable names

### ISSUE THREAD

**Issue by estern95** [tidyverse/readxl#548]
When setting the parameter col_names to FALSE in read_excel, the names created are nearly unusable with other tidyverse verbs since ..1, ..2, etc. are not valid R field names. 

```r
read_excel(readxl_example("clippy.xlsx"), col_names = F) %>%
  select(..1)

read_excel(readxl_example("clippy.xlsx"), col_names = F) %>%
  select(`..1`) # this doesn't work either
```

**Comment by jennybc** [comment]
If you want to use dplyr, especially the scoped verbs, with a data frame, I strongly recommend that you make sure it has syntactic names. If you use `col_name = FALSE` in readxl, you are asking that all column names be fabricated from nothing.

You can request syntactic names via `.name_repair = "universal"`, which guarantees the column names are unique and syntactic.

``` r
library(readxl)
library(tidyverse)

read_excel(readxl_example("clippy.xlsx"), col_names = FALSE, .name_repair = "universal") %>%
  select(...1)
#> New names:
#> * `` -> ...1
#> * `` -> ...2
#> # A tibble: 5 x 1
#>   ...1                
#>   <chr>               
#> 1 name                
#> 2 Name                
#> 3 Species             
#> 4 Approx date of death
#> 5 Weight in grams
```

<sup>Created on 2019-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

If you are curious about the motivation for tibble's (and therefore readxl's) naming strategy, it's written up here: <https://principles.tidyverse.org/names-attribute.html>.

`.name_repair` also supports user-defined functions and constants, so you can provide the exact naming strategy that you want. More can be found in the Column Names vignette: <https://readxl.tidyverse.org/articles/articles/column-names.html>
