### ISSUE TITLE
Failure to read key ID column

### ISSUE THREAD

**Issue by rsbivand** [tidyverse/readxl#565]
---

Brief description of the problem: the data are six character IDs (OK to read as integer or numeric, but not OK to read as "0" (when column type set) or 0. Image from Libre Office Calc.
![image](https://user-images.githubusercontent.com/10198404/55541096-91ba5f80-56c4-11e9-8532-b24acbbbaf14.png)

```r
download.file("https://prezydent2015.pkw.gov.pl/wyniki_tura2.zip", file.path(td, "wyniki_tura2.zip"))
unzip(file.path(td, "wyniki_tura2.zip"), files="wyniki_tura2.xls", exdir=td)
wyn2 <- readxl::read_excel(file.path(td, "wyniki_tura2.xls"))
head(wyn2[,3])
```

**Comment by nacnudus** [comment]
I was able to read the correct values by opening the file in Excel and saving it.

The cells in column C contain formulas `="020101"` rather than literal values `"020101"`.  The file doesn't contain the values of those cells, because they haven't been calculated.  Opening and saving the file will evaluate the formulas and save the values to the file.

**Comment by rsbivand** [comment]
Could/should `readxl::read_excel()` detect this and fail safe? I only have LibreOffice Calc, but had presumed that `readxl::read_excel()` would not be this permissive. Could/does an argument control whether such cells (arguably so rendered to preserve the leading "0") are trashed or cause an error or warning?

**Comment by jennybc** [comment]
This is a libxls matter. I can ask that maintainer if it is feasible to check whether formulas have been evaluated. I suppose this happens when some 3rd party tool writes xls, containing formulas, and then ships it out to people "as is". In some sense, it's a file that can only be read after it has been opened in Excel.

**Comment by rsbivand** [comment]
Thanks, yes, it is the same issue. It is acknowledged that Excel has issues with data of this kind: https://support.office.com/en-us/article/Keeping-leading-zeros-and-large-numbers-1bf7b935-36e1-4985-842f-5dfa51f85fe7. The trick used above may well have come from third party software writing the file. So libxls would need to check for unevaluated formulae and flag them when say reading from a file download without visual inspection. I'll have to bear this in mind and mention it specifically in teaching.

**Comment by jennybc** [comment]
A better way to preserve the leading zeros is to format the cells explicitly as text. But now we're talking about things well beyond our control and, for that matter, we would ask why this data is being written as xls in the first place!

**Comment by rsbivand** [comment]
Thanks, I'll close, as https://github.com/libxls/libxls/issues/57 covers the case.

**Comment by jennybc** [comment]
This weekend's plethora of screencasts/blog posts about lldb inspired me. I inspected one of the cells in the debugger. It **is** being picked up as a formula, but as a numeric formula, not string. 

This conversation reminds me of one from a couple of years ago:

https://github.com/tidyverse/readxl/issues/362

where xls files were being written by a custom sed script. I suspect that this xls file is being written in a very unusual way (*maybe* it technically complies with the spec? or not?) that only Excel itself is able to cope with. And opening / saving in Excel write the same data to xls in a much more conventional way, that tools like libxls and therefore readxl can handle.

**Comment by rsbivand** [comment]
Jenny, yes, I raised that issue too, the file is the same one I was using teaching two years ago, but now I was trying to document it again without remembering the resolution. Thanks for looking again, I apologise for not checking carefully enough myself and simply referring to the previous analysis. I trust that the election data this year will be generated in a less error-prone way.
