### ISSUE TITLE
read excel with signature NA

### ISSUE THREAD

**Issue by elephann** [tidyverse/readxl#573]
I have data downloaded from here http://www.swsindex.com/downloadfiles.aspx?swindexcode=SwClass&type=530&columnid=8892

Which can't be read into r, 
read_excel("SwClass.xls")
Error: 
  filepath: D:\SwClass.xls
  libxls error: Unable to open file

When check extention and signature, which shows:
readxl::excel_format("SwClass.xls")
[1] "xls"

readxl::format_from_signature("SwClass.xls")
[1] NA

How can this be fixed? Thanks!!

**Comment by batpigandme** [comment]
Nothing opened when I went to the link you provided, so I tried to download and open a different file from the same source: http://www.swsindex.com/downloadfiles.aspx?swindexcode=801001&type=510&columnid=8890

It comes up as invalid both when I try to open it using the GUI in RStudio (click on it in the File pane >> Import Dataset), _and_ trying to open it in Excel itself, with `Alert: The file format and extensions don't match!`:

![Is this a valid Excel file? in RStudio](https://user-images.githubusercontent.com/831732/59146759-1628a780-89c0-11e9-957a-6c2b341ba4b4.png)

![Alert the file format doesn't match in Excel](https://user-images.githubusercontent.com/831732/59146762-250f5a00-89c0-11e9-845f-456c7b830e27.png)

I even get a `File format error` if I run exiftool on it:
```zsh
$ exiftool 801001_hq.xls
ExifTool Version Number         : 11.49
File Name                       : 801001_hq.xls
Directory                       : .
File Size                       : 1351 kB
File Modification Date/Time     : 2019:06:08 07:32:24-04:00
File Access Date/Time           : 2019:06:08 07:36:00-04:00
File Inode Change Date/Time     : 2019:06:08 07:33:06-04:00
File Permissions                : rw-r--r--
Error                           : File format error
```

Are you able to open the xls in another program?

**Comment by jennybc** [comment]
Thanks @batpigandme for the investigation. Looks like this file is not actually an Excel workbook.

**Comment by elephann** [comment]
Thanks @batpigandme.
If I downloaded the file locally and open on windows system, then a warning occur "SwClass.xls's format and its extention not consistent," If I further push Yes, then this file can be opened.  Previously, I just save it as xlsx(from xls), then read it into R with readxl.
The data updates regularly(daily), that's why I want to download it directly online.
Anyway, Thanks!

**Comment by elephann** [comment]
If I download the data locally, I pushed the button
![捕获](https://user-images.githubusercontent.com/6313472/59157794-8714b000-8ae3-11e9-8231-74c467ed0dd7.PNG)
 
then the file indicate the following address
http://www.swsindex.com/downloadfiles.aspx?swindexcode=SwClass&type=530&columnid=8892

**Comment by batpigandme** [comment]
The file still has a formatting error outside of R. So, it makes sense that your workflow might have to include some file-repair outside the scope of readxl.

**Comment by jennybc** [comment]
There is a long tradition of people giving files an extension that *suggests* it is an Excel workbook, when it is not, knowing that when someone tries to open it, Excel will import it or somehow kick off a sequence of events that leads to Excel importing the file. People do this with csv, for example. I guess I understand why, because some people won't click on a csv but they will click on xls[x].

But the fact remains that readxl will only import a file that truly is an Excel workbook.
