### ISSUE TITLE
Error reading data in copy-made sheet with a graph

### ISSUE THREAD

**Issue by Rindrics** [tidyverse/readxl#576]
I found a problem when I read `.xls` data.

I wrote a test on [my folked repo](https://github.com/tidyverse/readxl/commit/871b679d5c5be298dc68e11056645645ec8c370e), but could not fix it because I can't read & write cpp.
```
context("Disturbing graph")
test_that("column A of copied sheet with graph is read correctly", {
  data <- read_excel(path = "sheets/disturbing-graph.xls", sheet = "Copied",
                                   col_names = FALSE, col_types = "text") %>%
	          data.frame()
  expect_equal(data[6:55, 1], as.character(seq(1, 50, 1)))
})
````

I think these two factors may be the causes of the problem.
- the sheet 'Copied' is created by copying the sheet 'Original'
- the sheet 'Copied' contains a graph

I simplified the sheet 'Copied' for easy understanding.
But I could not do that on sheet 'Original' because the problem will not be reproduced after modification (Sorry for non-ascii characters on sheet 'Original').

**Comment by jennybc** [comment]
So the example and test that you are adding in your fork demonstrates the *problem*? As opposed to providing a fix? I just want to understand.

I'm not working on readxl now, but this smells like something that will ultimately lead back to the library we embed, libxls, not readxl itself. There have certainly been issues in the past with chartsheets and complicated worksheets, so it's believable. It sounds like there could also be an encoding aspect to this. Does the problematic sheet come from a public source?

**Comment by kikirinrin** [comment]
Yes, it just demonstrates the problem (sorry for my incapability).
The problematic sheet came not from public source, but from my laboratory.
Should I have to read & write cpp if the issue came from libxls?

**Comment by jennybc** [comment]
If I can replicate the problem and it comes from libxls, I usually report it upstream.

**Comment by jennybc** [comment]
I see the problem using the standalone tool xls2csv tool built from <https://github.com/libxls/libxls/releases/tag/v1.6.2>.

```
~/rrr/libxls % xls2csv ~/rrr/readxl/investigations/iss576.xls -l
FILE: /Users/jenny/rrr/readxl/investigations/iss576.xls
Copied
Original
~/rrr/libxls % xls2csv ~/rrr/readxl/investigations/iss576.xls -t Copied
FILE: /Users/jenny/rrr/readxl/investigations/iss576.xls
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
0;"";"";"";"";"";"";"";"";"";"";""
26;"";"";"";"";"";"";"";"";"";"";""
27;"";"";"";"";"";"";"";"";"";"";""
28;"";"";"";"";"";"";"";"";"";"";""
29;"";"";"";"";"";"";"";"";"";"";""
30;"";"";"";"";"";"";"";"";"";"";""
31;"";"";"";"";"";"";"";"";"";"";""
32;"";"";"";"";"";"";"";"";"";"";""
33;"";"";"";"";"";"";"";"";"";"";""
34;"";"";"";"";"";"";"";"";"";"";""
35;"";"";"";"";"";"";"";"";"";"";""
36;"";"";"";"";"";"";"";"";"";"";""
37;"";"";"";"";"";"";"";"";"";"";""
38;"";"";"";"";"";"";"";"";"";"";""
39;"";"";"";"";"";"";"";"";"";"";""
40;"";"";"";"";"";"";"";"";"";"";""
41;"";"";"";"";"";"";"";"";"";"";""
42;"";"";"";"";"";"";"";"";"";"";""
43;"";"";"";"";"";"";"";"";"";"";""
44;"";"";"";"";"";"";"";"";"";"";""
45;"";"";"";"";"";"";"";"";"";"";""
46;"";"";"";"";"";"";"";"";"";"";""
47;"";"";"";"";"";"";"";"";"";"";""
48;"";"";"";"";"";"";"";"";"";"";""
49;"";"";"";"";"";"";"";"";"";"";""
50;"";"";"";"";"";"";"";"";"";"";""%
```

which means this is a problem in the embedded libxls library.

If you wish to report this upstream @Rindrics, you could open an issue at <https://github.com/libxls/libxls/issues>, referring back to this issue and, again, providing an example of a a troublesome file.

Here is a link to the example file you put in your fork:

https://github.com/tidyverse/readxl/blob/871b679d5c5be298dc68e11056645645ec8c370e/tests/testthat/sheets/copied-sheet.xls

from which anyone can then download it.
