### ISSUE TITLE
Range with Skip

### ISSUE THREAD

**Issue by bhive01** [tidyverse/readxl#577]
I'm working more with funky excel sheets and hitting my head up on something small, but could be a Quality of Life improvement. I'd like to be able to supply column range, but also use skip. 
[reprex.xlsx](https://github.com/tidyverse/readxl/files/3322556/reprex.xlsx)

```r
library(readxl)

read_xlsx("~/Downloads/reprex.xlsx", sheet = 1, range = cell_cols("J:M"), skip = 1)


# A tibble: 8 x 4
  ...1  ...2  junk    ...4 
  <chr> <chr> <chr>   <chr>
1 Col1  Col2  Col3    Col4 
2 1     A     2019-06 A    
3 2     B     2019-05 B    
4 3     C     2019-07 C    
5 4     D     2018-06 D    
6 5     E     2018-05 E    
7 6     F     2018-04 F    
8 7     G     2017-09 G    

```

In the docs it says that range takes precedence over skip and others, but I think it's flat out ignoring skip. 
Unless there is another way to specify the upper left, but only the column of the right side of the rectangle so it can get as many lines as there are?

**Comment by bhive01** [comment]
To sort of answer my own question partially the limits can be set like so:
`read_xlsx("~/Downloads/reprex.xlsx", sheet = 1, range = cell_limits(c(2, 10), c(NA, NA)))`

Despite that, sure would be nice to use columns and then specify a skip value.

**Comment by jennybc** [comment]
Yeah, I'm afraid you discovered the answer. If you specify range, we don't consult `skip`.

For the type of open rectangle you want, your `cell_limits()` expression is as good as it gets. Google Sheets supports slightly more range-y expressions and, last time I was working on googlesheets4, I took a crack at accepting some of them via `range`. So maybe that will make its way back into cellranger, for use in readxl and googlesheets4. But I think what you're doing with `cell_limits()` is necessary now.
