### ISSUE TITLE
Unable open xls file and format_from_signature() return NA

### ISSUE THREAD

**Issue by nqkhanh2209** [tidyverse/readxl#579]
Hello,
I tried to open historic price information in this file by **readxl** but it shows :"libxls error: Unable to open file".
I tried many ways and search on many topic and I find that :function format_from_signature() return NA , I disclose the link file below:
Thank and best regard

https://drive.google.com/file/d/1Am5m8QjQX6kwcK02vwmPO3e1irnypH07/view?usp=sharing

**Comment by cderv** [comment]
This is like #573 
The file is not an excel workbook. 

When you open it with excel you get a message that the extension is not correct. 

Like in #573, if you change the extension to html, you get a table in your browser. 

readxl can only read true excel workbook.

**Comment by jennybc** [comment]
Thanks @cderv for the detective work and linking.
