### ISSUE TITLE
Include tibble < 1.4.2 message in package startup

### ISSUE THREAD

**Issue by nlneas1** [tidyverse/readxl#582]
It would be much better to include [the message](https://github.com/tidyverse/readxl/blob/9d665bbb46923281911eddd4531617a461bad645/R/read_excel.R#L357) about the installed version `tibble` being < 1.4.2 in the package startup messages rather than where it is. If my package depends on `readxl`, I cannot remove this message easily. I don't want to `suppressMessages()` as I may suppress something which may in fact be useful. But I do not want to see this message all the time, for example in CI/CD pipeline logs. At least then I could `suppressPackageStartupMessages()`.

**Comment by jennybc** [comment]
FWIW the next change to that code in a readxl release is likely to be removal and a bump to the minimum version of tibble. The message only appears once per session. I think it's more appropriate to issue a message at the moment an affected call is made versus at startup. Lots of people find startup messages annoying as well, so it's hard to please everyone whenever there is a change.

**Comment by nlneas1** [comment]
Thanks for your quick response Jenny. I take your point on board about timing of the prompt. I guess I was coming more from the side of suppressing messages in startup vs. suppressing all messages in the use of the function when calling it.

**Comment by nlneas1** [comment]
Another option would be to use `getOption()` and allow people to turn messages such as this off by default? i.e. use a parameter within the function which determines whether the message should be returned or not.

**Comment by nlneas1** [comment]
I managed to suppress the message with using

```
.onLoad <- function(libname, pkgname) {
  assign("first_call", FALSE, environment(fun = readxl:::tibble_message))
}
```

:)
