### ISSUE TITLE
col_types and col_names

### ISSUE THREAD

**Issue by zerogetsamgow** [tidyverse/readxl#590]
I get an error message "Error: Element 1 has length 2, not 1 or 12" when specifying col_types and col_names for read_excel, even though my specified types are length 12.

I am using publicly available data. The following code downloads the data, though you will need to change the destination (tourism.path).

```r
library(tidyverse)
library(rvest)
library(readxl)

tourism.path <- "T:/TIGR_EFP/REVENUE AND TAXATION/DATABASES/Tourism"
domestic.url <- "https://www.business.vic.gov.au/tourism-industry-resources/research/domestic-and-regional-research"
international.url <- "https://www.business.vic.gov.au/tourism-industry-resources/research/international-research"

# Get xls data from tourism victoria
xls.tbl <- # Read urls from vcglr.url
             bind_rows(domestic.url %>% 
                       read_html()  %>%
                       rvest::html_nodes(., xpath=".//a[contains(@href, 'xls')]") %>% 
                       rvest::html_attr("href") %>%
                       # Add prefix and convet to a tibble
                       enframe(name=NULL, value = "urls"),
                       international.url %>% 
                       read_html()  %>%
                       rvest::html_nodes(., xpath=".//a[contains(@href, 'xls')]") %>% 
                       rvest::html_attr("href") %>%
                       # Add prefix and convet to a tibble
                       enframe(name=NULL, value = "urls")) %>%
             # Extract workbook name as variable downloads
             mutate(downloads=file.path(tourism.path,gsub(".*/","",urls))) %>%
             # Download files
             mutate(df=map2(urls, downloads, function(u,d) if(!file.exists(d)) download.file(u,d,mode="wb"))) %>%
             select(-df) %>%
             # Exract sheet names and unnest into tibble with all sheets to be dowloaded
             mutate(sheets=map(downloads, excel_sheets)) %>% 
             unnest() %>%
             filter(grepl("Domestic visitors to regions|Visitors & Nights Regional Vic",sheets))

tourism.names <- c("variable",2009:2019 %>% paste0("year_",.))
tourism.cols <- c("text",rep("numeric",11))

# Create tbl of visitor data based on xls.tbl above.
tourism.tbl <-  pmap_df(list(xls.tbl$downloads,
                            xls.tbl$sheets,
                            col_types=tourism.cols,
                            #col_names=tourism.names,
                            range="a4:l100"),
                       read_excel)
```

**Comment by jennybc** [comment]
Can you simplify this to a single readxl call? I.e. get rid of the extraneous tidyverse and rvest stuff. Preferably using the reprex package. Boilerplate advice on that is below. It's great that we're already talking about a publicly available file, so it shouldn't be too hard to make this cleaner.

---

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box. `.xlsx` is a supported file type. You'll need to zip or gzip `.xls` so it appears as `.zip` or `.gz`.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by zerogetsamgow** [comment]
I don't encounter a problem with a single read_excel call. So, the issue might be with pmab_df.
