### ISSUE TITLE
Issue when using col_names, col_types, skip and missing values

### ISSUE THREAD

**Issue by jwhendy** [tidyverse/readxl#593]
Update: other search incantations turned up #157, which is actually what I think this is most closely related to.

---

#81 and #137 are similar, but I don't think they are the same as this.

---

I'm reading in a large excel file in wide format and ran into an issue. I have recreated an example which I *think* boils down to these characteristics.

- the final columns are in the form `var_1`, `var_2`, ..., `var_50`, many of which are empty. In my example, I figured out that if you don't have a value in a column until row 1002, `read_excel` will treat them as logical. Thus, without specifying `col_types`, you get:

```
1: In read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  ... :
  Expecting logical in AS1969 / R1969C45: got 'foo'
```

- while not stated in [the documentation](https://www.rdocumentation.org/packages/readxl/versions/0.1.1/topics/read_excel), unless I'm missing it, `col_names` should require `skip=1` if you want to specify your own header even though the data has it's own.

- now, to the issue: if you have a big data set and use `n_max` *and* you have a column with missing data in rows `>n` *and* use `skip=1` *and* specify your own `col_types`, you'll get an error like this:

```
Error: Sheet 1 has 49 columns, but `col_types` has length 70.
```

Here is [an excel file](https://github.com/tidyverse/readxl/files/3786815/col_name_col_type.xlsx) that reproduces this.
```
library(readxl)
data <- read_excel("~/Desktop/col_name_col_type.xlsx",
                   skip=1,
                   col_names=c("foo", "bar", paste0("x", 1:3)),
                   col_types=rep("text", 5), n_max=50)
Error: Sheet 1 has 4 columns, but `col_types` has length 5.
```

In my case, this resolved once I removed my troubleshooting `n_max` option. I *think* the issue happens because `skip=1` removes the first row, which was the only row containing any text in these far out columns. In addition, in rows `<n_max`, these values were also missing. Something about specifying `col_types` for these columns in which it can't find any values seems to cause the issue.

Possible proposal: for columns in which `col_names` or `col_types` are specified... populate `NA` and perhaps issue a simple warning? In many cases, this is probably a mismatch of lengths (warnings/errors already occur when we find more columns than provided names/types), but in other cases, it might be that the user wants to specify names/types and the columns are empty, or empty in current rows, but not all of them.

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS:   /usr/lib/libopenblasp-r0.3.7.so
LAPACK: /usr/lib/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readxl_1.3.1

loaded via a namespace (and not attached):
 [1] compiler_3.6.1   backports_1.1.4  assertthat_0.2.1 cli_1.1.0       
 [5] tools_3.6.1      pillar_1.4.2     tibble_2.1.3     crayon_1.3.4    
 [9] Rcpp_1.0.2       utf8_1.1.4       fansi_0.4.0      cellranger_1.1.0
[13] vctrs_0.2.0      zeallot_0.1.0    pkgconfig_2.0.2  rlang_0.4.0
```

**Comment by jennybc** [comment]
You seem to be hoping that, by specifying 5 column names and 5 column types, you have also specified to read 5 columns. But that's not true. If you don't specify the `range`, `read_excel()` determines the column extent of the "minimal data rectangle" based on nonempty cells.

That's why we report that the sheet has 4 columns:

```
Error: Sheet 1 has 4 columns, but `col_types` has length 5.
```

I'd approach this differently:

  * Use `range` to specify that you want 5 columns.
  * Let the default names happen and fix them in a separate step. You could use `dplyr::rename()` to only change those that need it, etc.
  * If all column types are the same (e.g. `"text"`), you don't need to replicate that once per column. A single value is recycled.

``` r
library(readxl)

data <- read_excel("investigations/col_name_col_type.xlsx",
                   range = cell_cols(1:5), col_types = "text", n_max = 50)
names(data) <- c("foo", "bar", paste0("x", 1:3))
data
#> # A tibble: 1,001 x 5
#>    foo   bar   x1    x2    x3   
#>    <chr> <chr> <chr> <chr> <chr>
#>  1 Q     <NA>  Q     Q     <NA> 
#>  2 J     V     B     N     <NA> 
#>  3 U     E     B     X     <NA> 
#>  4 Q     Y     Y     U     <NA> 
#>  5 V     P     K     Q     <NA> 
#>  6 X     W     H     I     <NA> 
#>  7 N     I     Z     G     <NA> 
#>  8 G     P     E     J     <NA> 
#>  9 P     X     N     I     <NA> 
#> 10 M     W     K     E     <NA> 
#> # … with 991 more rows
```

<sup>Created on 2019-10-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by jwhendy** [comment]
> But that's not true. If you don't specify the range, read_excel() determines the column extent of the "minimal data rectangle" based on nonempty cells.

This does help clear up what's going on, and I didn't think of the `range` option (which seems obvious now that I re-read it in light of this.

That said, I still think the behavior is inconsistent. For example, this works fine (take the in-data header):
```
data <- read_excel("~/Downloads/col_name_col_type.xlsx", col_types="text", n_max=50)
```
As is this, which is nonsense since the original header is treated as data:
```
data <- read_excel("~/Downloads/col_name_col_type.xlsx", col_types="text", n_max=50, col_names=letters[1:5])
```
In my opinion, using `skip=1` + `col_names` should behave the same as using neither. In other words, either take the in-data header let the user skip that one and provide their own.

To play devil's advocate, why is the row 1 header text in a file trusted to indicate the shape of the data more than a user specifying a header for that column manually via `col_names`?

**Comment by jwhendy** [comment]
One more thought from re-reading your comment. I view code (and python in particular given the zen) as aiming toward being the best/right approach, not the approach we can work around.

I do appreciate the alternate path, though my point in bringing it here was more to ask "Was this intended/planned? If not, how could it be better?"

**Comment by jennybc** [comment]
> To play devil's advocate, why is the row 1 header text in a file trusted to indicate the shape of the data more than a user specifying a header for that column manually via col_names?

It's not. The shape of the data is determined by the smallest rectangle that covers all non-empty cells, unless the user specifies the `range`.

There is a full vignette on sheet geometry if you'd like to read more about how this works:

https://readxl.tidyverse.org/articles/sheet-geometry.html

**Comment by jwhendy** [comment]
I guess agree to disagree. I view `col_names` as the user inserting non-empty cells in what is effectively row 1. It seems an artifact of having to specify `skip=1` because there is no option to take the header as-is and provide your own names.
