### ISSUE TITLE
read_excel not working in r markdown

### ISSUE THREAD

**Issue by benwatsoncpa** [tidyverse/readxl#594]
Hi, 

read_excel is not working in r markdown. Not sure why. It just hangs.

library(readxl)
df <- read_excel("New Microsoft Excel Worksheet.xlsx")

```{r setup,include=F}
library(readxl)
df <- read_excel("New Microsoft Excel Worksheet.xlsx")
```

**Comment by jennybc** [comment]
I just made an `.Rmd` with this content:

````
---
title: "Hello, readxl, are you there?"
output: github_document
---

I will read from one of the example workbooks that ship with readxl.

```{r}
library(readxl)

read_excel(readxl_example("clippy.xlsx"))
```
````

and got this result:

---

Hello, readxl, are you there?
================

I will read from one of the example workbooks that ship with readxl.

``` r
library(readxl)

read_excel(readxl_example("clippy.xlsx"))
```

    ## # A tibble: 4 x 2
    ##   name                 value    
    ##   <chr>                <chr>    
    ## 1 Name                 Clippy   
    ## 2 Species              paperclip
    ## 3 Approx date of death 39083    
    ## 4 Weight in grams      0.9

---

I think this is not a readxl problem but some problem specific to your setup or a path problem or ...
