### ISSUE TITLE
Read_excel only accepts/read the first 9 workbook in a folder no matter how hard you try 

### ISSUE THREAD

**Issue by hammao** [tidyverse/readxl#604]
---

I'm reading multiple .xls from a folder "test_dir". Each time, only the first 9 dataset are read into r i.e Book1-Book9

Kindly note that i've tried to resolve this problem before raising the issue here  and i believe its a bug....
https://stackoverflow.com/questions/60246002/why-is-r-reading-only-the-first-nine-files?noredirect=1#comment106565146_60246002.

```r
files <- list.files(path = "./test_dir", pattern = "Book\\d+\\.xls$", full.names = TRUE)  

tbl <- lapply(files, read_excel,  skip=7) %>% bind_rows(.id = "id")
```

**Comment by jennybc** [comment]
## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box. `.xlsx` is a supported file type. You'll need to zip or gzip `.xls` so it appears as `.zip` or `.gz`.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.
