### ISSUE TITLE
readxl changes numeric data into characters when col_names = FALSE

### ISSUE THREAD

**Issue by lucifersFall1n1** [tidyverse/readxl#605]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

When importing data from and xlsx spreadsheet, numbers are turned into characters whenever col_names = FALSE.

Sample dataset that resulted in the above happening when imported
[reprex.xlsx](https://github.com/tidyverse/readxl/files/4259054/reprex.xlsx)

```
library(readxl)
reprex <- read_excel("~/Desktop/reprex.xlsx")
str(reprex)
```
will show the data to be num. However,

```
library(readxl)
reprex <- read_excel("~/Desktop/reprex.xlsx", 
     col_names = FALSE)
str(reprex)
```
will have the data be chr, despite the file being the exact same and the only difference being the column names being present or not.

**Comment by jennybc** [comment]
If we aren't using the column names as column names, but they are still present in the spreadsheet, use `skip = 1` so they are not read.
