### ISSUE TITLE
path does not exist when importing data with url

### ISSUE THREAD

**Issue by gbganalyst** [tidyverse/readxl#609]
---

I tried to use `readxl` package to open an Excel file that lives in google drive. `read_xlsx(url)` threw an error that the `path does not exist`.

But when I tried to do the same thing with `openxlsx` package, the data was imported successfully.

```r with readxl pkg
url <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vQH8DfJhj4-fiEw91FkcQXB47cCNSPMJo6AnehnGinq1pALxuQXqVwnZQcKtN0Ulw/pub?output=xlsx"

data <- read_xlsx(url)

```
![Error message](https://user-images.githubusercontent.com/34424271/76352863-0b64bf80-6310-11ea-8ae7-4f464995378c.png)

```r with openxlsx pkg
library(openxlsx)

url <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vQH8DfJhj4-fiEw91FkcQXB47cCNSPMJo6AnehnGinq1pALxuQXqVwnZQcKtN0Ulw/pub?output=xlsx"

data <- read.xlsx(url)

# Everything works well!
```

**Comment by jennybc** [comment]
readxl does not support reading from a URL. The `path` argument is documented to be "Path to the xls/xlsx file".

This feature request is already being tracked at #278, where you can also find some lightweight workarounds.
