### ISSUE TITLE
Bug reading an excel file

### ISSUE THREAD

**Issue by ben1787** [tidyverse/readxl#612]
Hi Jenny! Amazing package thank you so much for creating and maintaining.

Unfortunately I have an excel file that is not being read and I do not know why.

When I use the package 'xlsx' it works fine using read.xlsx.

Here is my error:

a = read_xlsx(path = "C:/Users/ben/Downloads/test.xlsx")
Error in read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  : 
  invalid Unicode point 56328

And here is the file:
[test.xlsx](https://github.com/tidyverse/readxl/files/4513155/test.xlsx)

Thanks for your help!!

Best,
Ben

**Comment by jennybc** [comment]
I can read from the workbook without error.

That has vague "path problem" smell. Are you omitting some details? Are you still having such troubles?

**Comment by jennybc** [comment]
I can still read this file.
