### ISSUE TITLE
Read xlsx from an online source

### ISSUE THREAD

**Issue by hddao** [tidyverse/readxl#613]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem
Hi all,
I tried to import xlsx file from https://www.cdc.gov/nchs/data/data_acces_files/NCHSURCodes2013.xlsx into R but I got the error below. 

> df <- read_excel('https://www.cdc.gov/nchs/data/data_acces_files/NCHSURCodes2013.xlsx', 'NCHSURCodes2013')
Error: `path` does not exist: ‘https://www.cdc.gov/nchs/data/data_acces_files/NCHSURCodes2013.xlsx’

When I downloaded the file to my computer, it did not have that problem; I was able to import the xlsx ok.

Do you know if there's a way I can read it directly from the link, instead of having to download it to my computer? Thank you!

**Comment by jennybc** [comment]
This general request (and more) is already tracked in #278
