### ISSUE TITLE
Change the default value of `sheet` to `1` instead of `NULL`

### ISSUE THREAD

**Issue by jmcurran** [tidyverse/readxl#615]
Can the default value of the `sheet` argument in `read_excel_` (and derived functions) be `1` not `NULL`? Looking at the code for standardise_sheet, there is a line that says

```
if (is.null(sheet)) {
    sheet <- 1L
  }
```

It seems to me that having `sheet = 1L` in the function args would do the same thing. 

Obviously it works, so why change? Without going into great depth, if `sheet` is conditionally set, then I can't see a sensible way to set it to `NULL`. I can set it conditionally to `1` of course, but then given this is really the default behaviour why not just set it to that in the first place?

**Comment by jennybc** [comment]
The first answer that comes to mind is that `sheet = 1` sort of sends the signal that `sheet` should be a number, whereas it can also be a string. Now, I'm not saying that's a slam dunk, but my mind is firmly elsewhere and I wanted to react since I might not be back here very soon.

**Comment by jennybc** [comment]
I still feel like `NULL` is the most appropriate default, given that `sheet` could be either a number or a string, and the `NULL` default is a convention used heavily throughout the tidyverse.
