### ISSUE TITLE
Error: std::bad_alloc

### ISSUE THREAD

**Issue by sureshvigneshbe** [tidyverse/readxl#620]
I am using R 3.6.0 version and having RAM memory 16 GB.
While using read excel for reading two excel (xlsx files) got the error "Error: std::bad_alloc".

The two file sizes are respectively 166 MB (10 columns) and 130 MB (60 columns).

As found one of thread , need to close and open R studio , will resolve this issue.
Tried it and working now. But we have schedule (Automation) this R script to load the excel files .

Could any one suggest any other work around on this issue. Also having sufficient ram memory.

Thanks,
N Suresh

**Comment by jennybc** [comment]
I got some advice from @jimhester:

> Generally even if you exhaust all available RAM there will still be virtual memory, so getting `std::bad_alloc()` from high memory usage is pretty rare in practice ...
> I think running out of memory is unlikely to be the root cause for that issue, more likely there is a bug that is causing an invalid allocation, like an integer overflow or similar. I would try to get more info and hopefully a reprex

Can you give me access to these two files? Or any other publicly available xlsx that triggers the same behaviour? I am not very hopeful we can identify the cause without being able to replicate it.

**Comment by sureshvigneshbe** [comment]
Sure will check and provide those sheets.

**Comment by sureshvigneshbe** [comment]
Really Sorry Also want to add one more point.This error wont be occurred on the first time of execution. after run twice or thrice with the files. Whatever the data frames , we are assigning in the process, same will be cleared in the end of script. Kindly assist whether this would make any issues.

**Comment by jennybc** [comment]
## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box. `.xlsx` is a supported file type. You'll need to zip or gzip `.xls` so it appears as `.zip` or `.gz`.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by sureshvigneshbe** [comment]
Let me have a word with my supervisor about the sensitivity of the excels.

**Comment by jennybc** [comment]
Without access to files that trigger this problem, there's nothing to be done here.

**Comment by W4gs** [comment]
**r.py:**
def foo():
    print("hello world")

foo()

**RStudio:**
library(reticulate)
source_python("r.py")

This code results in a STD:BAD_ALLOC
Aborted(Core dumped)
