### ISSUE TITLE
Asking help for local installation of the package in R

### ISSUE THREAD

**Issue by zhangbs92** [tidyverse/readxl#623]
Hello everyone, 

I am a student of Biostatistics. I received a package from our collaborator, however, following errors keep showing when I tried to install it. I have no knowledge of C or C++, and just few of package structure. So could anyone guide me how to fix the problem? What I need is just successfully install the package to my R.

Best Regards,
Bill

*Note: the package is called lme4, I know there exists a package in CRAN called lme4, but this is one we modify somehow, it is different.
---

> devtools::load_all(".")
Loading lme4
Re-compiling lme4
─  installing *source* package ‘lme4’ ...
   ** using staged installation
   ** libs
   clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Matrix/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/stats/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c init.c -o init.o
   clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Matrix/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/stats/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c lmer.c -o lmer.o
   lmer.c:327:9: warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]
       if (!(ll = LENGTH(GET_SLOT(x, sym))) == len && zerok && !ll)
           ^                                ~~
   lmer.c:327:9: note: add parentheses after the '!' to evaluate the comparison first
       if (!(ll = LENGTH(GET_SLOT(x, sym))) == len && zerok && !ll)
           ^
            (                                     )
   lmer.c:327:9: note: add parentheses around left hand side expression to silence this warning
       if (!(ll = LENGTH(GET_SLOT(x, sym))) == len && zerok && !ll)
           ^
           (                               )
   lmer.c:1758:10: warning: unused variable 'asgn' [-Wunused-variable]
       int *asgn = INTEGER(getAttrib(flistP, install("assign")));
            ^
   2 warnings generated.
   clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Matrix/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/stats/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c local_stubs.c -o local_stubs.o
   clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o lme4.so init.o lmer.o local_stubs.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
   ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
   ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
   ld: library not found for -lgfortran
   clang: error: linker command failed with exit code 1 (use -v to see invocation)
   make: *** [lme4.so] Error 1
   ERROR: compilation failed for package ‘lme4’
─  removing ‘/private/var/folders/m_/0j0s4gln6y7603j240c5122h0000gn/T/RtmpyK60b7/devtools_install_8f24eb45a71/lme4’
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> 2 warnings generated.
E> clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Matrix/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/stats/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c local_stubs.c -o local_stubs.o
E> clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o lme4.so init.o lmer.o local_stubs.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath
[...]
Type .Last.error.trace to see where the error occured

--------------------------------------

When I type .Last.error.trace, then following showed

---------------------------------------

> .Last.error.trace

 Stack trace:

 1. devtools::load_all(".")
 2. pkgload::load_all(path = path, reset = reset, recompile = recompile,  ...
 3. pkgbuild::compile_dll(path, quiet = quiet)
 4. pkgbuild:::install_min(path, dest = install_dir, components = "libs",  ...
 5. pkgbuild:::rcmd_build_tools("INSTALL", c(path, paste("--library=",  ...
 6. pkgbuild:::with_build_tools(callr::rcmd_safe(..., env = env,  ...
 7. callr::rcmd_safe(..., env = env, spinner = FALSE, show = FALSE,  ...
 8. callr:::run_r(options)
 9. base:::with(options, with_envvar(env, do.call(processx::run,  ...
 10. base:::with.default(options, with_envvar(env, do.call(processx::run,  ...
 11. base:::eval(substitute(expr), data, enclos = parent.frame())
 12. base:::eval(substitute(expr), data, enclos = parent.frame())
 13. callr:::with_envvar(env, do.call(processx::run, c(list(bin, args = real_cmdargs,  ...
 14. base:::force(code)
 15. base:::do.call(processx::run, c(list(bin, args = real_cmdargs,  ...
 16. (function (command = NULL, args = character(), error_on_status = TRUE,  ...
 17. throw(new_process_error(res, call = sys.call(), echo = echo,  ...

 x System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> 2 warnings generated.
E> clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Matrix/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/stats/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c local_stubs.c -o local_stubs.o
E> clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o lme4.so init.o lmer.o local_stubs.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
E> ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
E> ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
E> ld: library not found for -lgfortran
E> clang: error: linker command failed with exit code 1 (use -v to see invocation)
E> make: *** [lme4.so] Error 1
E> ERROR: compilation failed for package ‘lme4’
E> * removing ‘/private/var/folders/m_/0j0s4gln6y7603j240c5122h0000gn/T/RtmpyK60b7/devtools_install_8f24eb45a71/lme4’

----------------------------------------------
Still chaos to me, hope any of you could kindly help.

**Comment by cderv** [comment]
Hi, 

This is a question you should ask on http://community.rstudio.com. 
The issue board in Github is more suited for bugs and feature requests regarding the specific project, here `readxl`. 
Here your question does not seem to aim at `readxl` also.

It is advice in the [issue template](https://github.com/tidyverse/readxl/blob/master/.github/ISSUE_TEMPLATE.md) you should have seen before posting the issue. 

See you on the community website !

**Comment by batpigandme** [comment]
Thanks, @cderv!
