### ISSUE TITLE
Enable reading directly from OneDrive/Sharepoint

### ISSUE THREAD

**Issue by acvelozo** [tidyverse/readxl#626]
Would it be possible to enable to read directly from Excel files stored in **OneDrive/Sharepoint** in a **similar way** to what is possible with Google Sheets using **googlesheets4**?

Basically allowing the `path` argument in `read_excel()` to be the link to a OneDrive file, just like the `ss` argument of `read_sheet()` from googlesheets4. 

Example use case:
```r
df <- read_excel("https://my-sharepoint-site/documents/my-file.xlsx", sheet="sheet1")
```
I think this would make workflows involving OneDrive/Sharepoint easier to manage.

**Comment by jennybc** [comment]
I think this is #278 but with the added complication of auth (?).

**Comment by acvelozo** [comment]
I hadn't seen that thread, but yes, I think you are right, it's related and has the added complexity of auth to a Microsoft account. I used the comparison to googlesheets4 because I think currently there is a high similarity between Google Sheets and Excel Online. Excel lagged behind for some time in terms of online spreadsheets, but in my opinion it seems to have catched up with Google Sheets in that area. So I think a similar approach for handling data with R would make sense. What do you think?

**Comment by jennybc** [comment]
It feels like there are two scenarios, neither of which are solved and each of which has some hard parts:

  * Read it like an `.xlsx` that lives online.But you need auth. The low-tech way would still be to bring the file into a local temp file, then read it, which is probably what the first move on #278 would be.
  * Read is like a Google Sheet, using an API (does that exist?). This means writing a whole API wrapper.

**Comment by jennybc** [comment]
If #278 is enough, then that will solve this. I.e. if a file can be made readable in a simple way (e.g. publicly readable). But anything else (requiring auth or wrapping an actual API) is definitely beyond the scope of readxl.
