### ISSUE TITLE
Can't download xlsx file from the internet

### ISSUE THREAD

**Issue by dkgaraujo** [tidyverse/readxl#629]
Dear developers,
I tried using readxl::read_excel to download an Excel file that is updated from time to time - so I wanted to make the code automatically fetch the latest version instead of me having to manually download it. However, if I try the following line, it gives an error, whereas if I download the Excel file and point to that folder, read_excel will read it normally.

Not a mission critical error, but still, would be nice to know a solution if possible. Thanks in advance!

```r
library(readxl)

# error:
ESRB_CCyB <- read_excel("https://www.esrb.europa.eu/national_policy/ccb/shared/data/esrb.ccybd_CCyB_data.xlsx")
# >
# > Error: `path` does not exist: ‘https://www.esrb.europa.eu/national_policy/ccb/shared/data/esrb.ccybd_CCyB_data.xlsx’

# works out fine: (assumes the same file as above is downloaded into folder "/Downloads/"
ESRB_CCyB <- read_excel("~/Downloads/esrb.ccybd_CCyB_data.xlsx")
```

**Comment by jennybc** [comment]
readxl does not work from URLs. The `path` argument is: `Path to the xls/xlsx file`.

Making it do so is tracked in #278.
