### ISSUE TITLE
Computer freezing when trying to read xslx file with readxl_xlsx()

### ISSUE THREAD

**Issue by fndemarqui** [tidyverse/readxl#630]
I am trying to import a xlsx file using the readxl::read_xlsx() function. However, my computer completely freezes when I run the code below. 

```r
library(tidyverse)
library(readxl)
library(httr)

url <- "https://xx9p7hp1p7.execute-api.us-east-1.amazonaws.com/prod/PortalGeral"
covid <- GET(url, add_headers("x-parse-application-id" = "unAFkcaNDeXajurGB7LChj8SgQYS2ptm"))
results <- covid %>% content()
url_data <- results$results[[1]]$arquivo$url

tmp_filename <- tempfile()
download.file(url = url, destfile = tmp_filename)
covid19 <- read_xlsx(tmp_filename, col_types = "text")
file.remove(tmp_filename)
```

**Comment by jennybc** [comment]
It looks like this is somehow not a valid xlsx file:

```
> covid19 <- read_xlsx(tmp_filename, col_types = "text")
Error: Evaluation error: zip file '/private/var/folders/pv/l2mbh7j90y5_vslh_1wyqxj00000gn/T/RtmpOzLxFO/file32c32b8dbad2' cannot be opened.
```

I've also attempted to determine its file type by looking at its "magic number" or file signature and it also does not look like an xlsx file.

At this point I seriously doubt it's a readxl issue. Can you open it with Excel? I can't.

![Screen Shot 2020-09-11 at 3 11 40 PM](https://user-images.githubusercontent.com/599454/92977174-23dda000-f441-11ea-9c64-2ec41d4aef37.png)

**Comment by fndemarqui** [comment]
Thanks for answering.
I am not sure it is a file problem.  I manually downloaded the file from the repository https://covid.saude.gov.br/ ( green top-right button Arquivo CSV - which indeed gives a xlsx file). Although I was able to open the file on LibreOffice without problems, I could not read it into R. I managed to open the file with the openxlsx::read.xlsx() function:

```{r}
library(tidyverse)
library(httr)

url <- "https://xx9p7hp1p7.execute-api.us-east-1.amazonaws.com/prod/PortalGeral"
covid <- GET(url, add_headers("x-parse-application-id" = "unAFkcaNDeXajurGB7LChj8SgQYS2ptm"))
results <- covid %>% content()
url_data <- results$results[[1]]$arquivo$url

covid19 <- openxlsx::read.xlsx(url_data)
```

**Comment by fndemarqui** [comment]
> Thanks for answering.
> I am not sure it is a file problem. I manually downloaded the file from the repository https://covid.saude.gov.br/ ( green top-right button Arquivo CSV - which indeed gives a xlsx file). Although I was able to open the file on LibreOffice without problems, I could not read it into R. I managed to open the file with the openxlsx::read.xlsx() function:
> 
> ```
> library(tidyverse)
> library(httr)
> 
> url <- "https://xx9p7hp1p7.execute-api.us-east-1.amazonaws.com/prod/PortalGeral"
> covid <- GET(url, add_headers("x-parse-application-id" = "unAFkcaNDeXajurGB7LChj8SgQYS2ptm"))
> results <- covid %>% content()
> url_data <- results$results[[1]]$arquivo$url
> 
> covid19 <- openxlsx::read.xlsx(url_data)
> ```

**Comment by jennybc** [comment]
When I click on that button, nothing happens, i.e. nothing downloads. I tried Safari and Chrome.

**Comment by fndemarqui** [comment]
I made the file available on my website: 

http://www.est.ufmg.br/~fndemarqui/HIST_PAINEL_COVIDBR_11set2020.xlsx
