### ISSUE TITLE
any sample which using this library with C++?

### ISSUE THREAD

**Issue by abcdef123ghi** [tidyverse/readxl#634]
any idea how to using this library with C++?thank you so much

**Comment by jennybc** [comment]
readxl is an R package.

When you say "using this library", do you perhaps means the underlying libraries we are using, such as libxls or RapidXML?

**Comment by abcdef123ghi** [comment]
> readxl is an R package.
> 
> 
> 
> When you say "using this library", do you perhaps means the underlying libraries we are using, such as libxls or RapidXML?

Ok,cool,ty

**Comment by abcdef123ghi** [comment]
> readxl is an R package.
> 
> When you say "using this library", do you perhaps means the underlying libraries we are using, such as libxls or RapidXML?

I really apperciated you answered this question,I was overwhelming
