### ISSUE TITLE
can't read xls

### ISSUE THREAD

**Issue by ramiromagno** [tidyverse/readxl#635]
[datasets.zip](https://github.com/tidyverse/readxl/files/5505852/datasets.zip)

Can't read the attached xls (compressed into zip so that it is uploadable).

readxl version is: 1.3.1.

```r
readxl::read_xls('datasets.xls')
```
generates:

```
Error: 
  filepath: (...)/datasets.xls
  libxls error: Unable to open file
```

(path is abbreviated)

The `datasets.xls` opens fine in Libreoffice 7.0.2.2.

**Comment by jennybc** [comment]
I'm not working on readxl right now, but this can mean that the file is in a format that is too old to be readable by libxls.

**Comment by nacnudus** [comment]
The file isn't actually a `.xls` file.  It is a single XML file using the SpreadsheetML schema, which was briefly used between 2003 and 2006, before being superseded by the Office Open XML standard (confusing, I know).  You can confirm this by renaming the file to `datasets.xml` and opening it in a text editor.

Unfortunately hardly any software supports these files.  Your best bet is to open it in Libreoffice, and save it as `.xlsx` or `.csv`.  If you prefer to do this at the command line, you can use the command `libreoffice --convert xlsx datasets.xml` or `libreoffice --convert csv datasets.xml`.

Alternatively, you could try importing it with the xml2 package, following this [stackoverflow answer](https://stackoverflow.com/questions/41943939/read-excel-xml-file-into-r), but after fiddling with that script for a while I gave up on it.

**Comment by ramiromagno** [comment]
Thank you for the clarification.
