### ISSUE TITLE
merging different sheet and In read_fun error

### ISSUE THREAD

**Issue by fary90** [tidyverse/readxl#638]
I have an excel file with 13 sheets and I want to merge and join them by "PID". 
( I'll use this cod to merge by PID >>> all <- left_join(sh1,sh2[,], by="PID") and then I want to save them I one file by using this code >>> save(all, file= "all.RData"))
i am using this code 
sh1 <- read_excel("Dr.Mee.xlsx",  sheet = "Maininfo")
sh2 <- read_excel("Dr.Mee.xlsx",  sheet = "Anthropometric")
.
.
.
but for some of my sheet, it doesn't work and return this error   >>>> There were 18 warnings (use warnings() to see them)
when I use this it returns two different codes. sometimes it returns this warning 
1)

Warning messages:
1: In read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  ... :
  Coercing text to numeric in H6129 / R6129C8: '90'
2: In read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  ... :
  Coercing text to numeric in F7400 / R7400C6: '15'
3: In read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  ... :
  Coercing text to numeric in C10818 / R10818C3: '84.5'
4: In read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  ... :
  Coercing text to numeric in C13106 / R13106C3: '109'
5: In read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  ... :
  Coercing text to numeric in F14855 / R14855C6: '15'
6: In read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  ... :
  Coercing text to numeric in F14896 / R14896C6: '15'
7: In read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  ... :
  Coercing text to numeric in F15258 / R15258C6: '16'
.
.
.
 2)
and for some sheet, it returns this error >>>
Warning message:
In read_fun(path = enc2native(normalizePath(path)), sheet_i = sheet,  :
  Expecting numeric in F6889 / R6889C6: got 'NULL'

why I get this error?
how should I solve it?

**Comment by jennybc** [comment]
I would interpret these warnings at face value.

For example, in the first case, a numeric column is being constructed, yet some text cells are found in it. Their locations are given specifically. Those text cells are being coerced to numeric.

In general, we can't really help without access to spreadsheets that show puzzling behaviour (which this doesn't seem to be).

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box. `.xlsx` is a supported file type. You'll need to zip or gzip `.xls` so it appears as `.zip` or `.gz`.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.
