### ISSUE TITLE
(Feature request) Support for Excel Named Cells, Ranges, and Tables 

### ISSUE THREAD

**Issue by ajit555** [tidyverse/readxl#643]
Support for Excel Named Cells, Ranges, and Tables #377
https://github.com/tidyverse/readxl/issues/377

Excel's recommended best practice is to use tables for storing tabular data. It would be useful if we can import the excel table in R.

**Comment by jennybc** [comment]
Semi-duplicate of #317 (morally the same wishes)

**Comment by jennybc** [comment]
I'm going to close this because #317 captures the basic goal.
