### ISSUE TITLE
How does readxl know how many rows there are?

### ISSUE THREAD

**Issue by idontgetoutmuch** [tidyverse/readxl#644]
Possibly I should ask this on stackoverflow but it is a very specific question. I've read through the docs and also searched for "discover" in this repo and looked in **jennybc/cellranger** but to no avail.

**Comment by jennybc** [comment]
Have you read this article?

https://readxl.tidyverse.org/articles/sheet-geometry.html

Specifically:

> The stream of cell items describes the existing cells, going from upper left to lower right, travelling by row. Blank cells simply do not exist in it.
> ...
> readxl only reads cell items that have content. It ignores cell items that exist strictly to convey formatting.
> 
> The tibble returned by readxl will often cover cells that are empty in the spreadsheet, filled with NA. But only because there was some other reason for the associated row or column to exist: actual data or user-specified geometry.

Basically, ignoring the user's geometry-related requests, we just read the stream of content-containing cells out of the xls[x] file.

**Comment by idontgetoutmuch** [comment]
Thank you very much for your reply. Yes I have read that article and found it very helpful. Perhaps I didn't ask my question clearly enough

> we just read the stream of content-containing cells out of the xls[x] file.

How do you know what the content-containing cells are? Until I discovered your package, I had been reading each row until I got a blank value for what is effectively the primary key. Clearly that's not very robust; somehow could easily have added a blank row to add readability.

I did check readxl by adding an extra cell many rows below the existing rows and readxl returned the right answer :-)

**Comment by idontgetoutmuch** [comment]
After a bit more poking, I can see that readxml uses rapidxml and .xlsx files are a collection of .xml files and I see in one of them things like:

```
<row r="383">
```

So it seems this sheet has 383 rows. I am guessing similarly for columns. So I think I have now answered my own question which is that readxml uses a C library to return the a stream of content-containing cells. And these can be determined by looking at the xml itself.

I will now close this ticket and thank you once again for taking the time :-)
