### ISSUE TITLE
Documentation: "readxl Workflows" vignette

### ISSUE THREAD

**Issue by donnekgit** [tidyverse/readxl#645]
Just a note re clarification of the [readxl Workflows vignette](https://readxl.tidyverse.org/articles/articles/readxl-workflows.html), section "Iterate over multiple worksheets in a workbook".

set_names() occurs in both {magrittr} and in {rlang}.  It is only the latter of these that works with the example:
```r
path <- readxl_example("datasets.xlsx")
path %>%
  excel_sheets() %>%
  set_names() %>%
  map(read_excel, path = path)
```

`rlang::set_names()` will give the expected output, but `magrittr::set_names()` gives the error:
```r
Error in magrittr::set_names(.) : 
  1 argument passed to 'names<-' which requires 2
```

So if {magrittr} is loaded, but not {rlang}, the example as given will not work.

Using R 4.1.0, tidyverse 1.3.1, rlang 0.4.11, magrittr 2.0.1.

**Comment by jennybc** [comment]
The vignette starts with `library(tidyverse)`, which actually means that `set_names()` is going to come from purrr, which is re-exporting `rlang::set_names()`.

It sounds like you are inserting some extra `library()` calls and are, therefore, getting different results. I think once you start remixing the code, you have to accept that you could get different results. In general, we don't attach magrittr and this sort of name collisions are part of the reason.
