### ISSUE TITLE
Consider increasing type guessing length of column when all initially scanned data is NA

### ISSUE THREAD

**Issue by jeromyanglim** [tidyverse/readxl#647]
I sometimes have excel spread sheets with sparse character data in some columns. For instance, the dataset might have a few thousand cases and there is a character variable that has some information at row 2000 or 5000, etc..

Perhaps this is a simple example. 

    x <- data.frame(x = seq(1:10000), y = c(rep(NA, 9000), rep("test", 1000)))

I'm not quite sure on the current default behavior of `read_excel`, but at least in one instance it has treated the variable as a logical. As a result, the character data is deleted.

I think that more effective behaviour would be to scan the variable for longer when the scanned data based on `guess_max` is `NA`.

I.e., if guess_max = 1000, and the first 1000 values of a variable are NA, then scan the remainder of the variable.

This would result in better variable typing and reduce data loss.

**Comment by jennybc** [comment]
I totally understand where this is coming from but this is not very easy / clean to implement.

My current "solution" to this is that better problem reporting #307 is going to help people detect this and reconsider `guess_max` or `col_types`.

That doesn't rule out other solutions in the more distant future, but the first move here will be better reporting on how parsing went.
