### ISSUE TITLE
Interplay between readxl spinner and cli progress bar

### ISSUE THREAD

**Issue by ramiromagno** [tidyverse/readxl#664]
Let  me apologise first because I am not including a reprex to showcase the problem but given that the issue has to do with dynamic output in R console I would not know how to make a static reprex to include here.

My case is that I am reading various XLSX files with `readxl::read_xlsx` and I am trying to track the progress with a progress bar from the R package `{cli}`. Note that I am trying to track the progress over these files, not the progress of reading one file --- as `readxl` does. I am basically setting a progress bar with `cli::cli_progress_bar`, then updating the bar with `cli::cli_progress_update`. The loop is being performed by `purrr::map_dfr`.

Essentially, the problem I am finding is that even when I turn off readxl spinner with the option `progress = FALSE` when calling `readxl::read_xlsx`, I still get the progress bar generated by `cli::cli_progress_bar` flushed (i.e. it disappears) between reads of the files.

The reason I think this has to do with `{readxl}` somehow interfering with console output is the fact that if I comment the `readxl::read_xlsx` call altogether and replace it with a simple `Sys.sleep(1)` call then I see the cli progress bar as intended.

**Comment by jennybc** [comment]
Without some code that lets me experience the problem, I can't really engage with this.
