### ISSUE TITLE
read_xlsx evaluates 1000 rows of a column and if "NA" for the first 1000, makes the rest "NA" whether "NA" or not 

### ISSUE THREAD

**Issue by loureynolds** [tidyverse/readxl#667]
I needed to import .XLS files, but could not so I saved them as .XLSX After importing and binding, I found out too much later that in the original import - an important field - that was mostly blank but had important information - was imported as all "NA" (The original datasets had many more columns and rows. I figured out, through trial and error, that read_xlsx evaluates about 1000 rows and if all of these are NA, then it writes the rest of the import as NA for that field.

I resolved this by saving the files as .csv and trying read_csv, which did not behave this way and correctly imported the data.

ma7 <- read_xlsx("https://github.com/tidyverse/readxl/files/7009850/file_f.xlsx")
ma8 <- read_xlsx("https://github.com/tidyverse/readxl/files/7009851/file_e.xlsx")

**Comment by batpigandme** [comment]
This is the `guess_max` argument, which defaults to 1000. From [docs here](https://readxl.tidyverse.org/reference/read_excel.html):


**`guess_max`** Maximum number of data rows to use for guessing column types.


```r
read_xlsx(
  path,
  sheet = NULL,
  range = NULL,
  col_names = TRUE,
  col_types = NULL,
  na = "",
  trim_ws = TRUE,
  skip = 0,
  n_max = Inf,
  guess_max = min(1000, n_max),
  progress = readxl_progress(),
  .name_repair = "unique"
)
```

**Comment by jennybc** [comment]
Yes @batpigandme has pointed out the argument you need to adjust (or, alternatively, you need to specify column types).

**Comment by loureynolds** [comment]
OK - to keep from guessing, I set guess_max=Inf and it worked.  I should read the fine print more often.
