### ISSUE TITLE
Cells with #N/A are read as NA

### ISSUE THREAD

**Issue by kwebihaf-github** [tidyverse/readxl#669]
I am trying to read an excel file that contains #N/A values in the cells using read_excel function. 

But after reading the file the #N/A cells instead are read as NA.

Is there any additional parameter to add on top of what I have used below?

For reproducibility, the file I used can be found [here](https://github.com/kwebihaf-github/data/raw/master/file.xlsx)

---

The way read_excel function is used

```r
orgunits_to_add <- readxl::read_excel("file.xlsx", 
                                      sheet =1,
                                      na=""
)
```

**Comment by jennybc** [comment]
I'm not really working on readxl right now but wanted to make a quick stop. The `na` argument is for specifying strings that we should convert to `NA`s in the R object. Perhaps these cells are true `NA`s *on the Excel side* (or, in Excel-speak, `#N/A`s), i.e. they represent missing data, not presenting character data. Therefore probably never get compared against the entries of the `na` argument.

I have not yet dug around in the source (or in your example file) to confirm, but that is my guess. I will be working on readxl later this fall. In the meantime, you'll need to devise some way to achieve what you want on the R side, by post-processing the result.

**Comment by jennybc** [comment]
As I suspected, these cells are true `#N/A`s in Excel. Here's XML for E2:

``` xml
<c r="E2" t="e">
  <v>#N/A</v>
</c>
```

Here is a good, official description of the meaning of `#N/A`:

https://support.microsoft.com/en-us/office/na-function-5469c2d1-a90c-4fb5-9bbc-64bd9bb6b47c

> ... #N/A is the error value that means "no value is available." Use NA to mark empty cells.

The rule where readxl regards this as a blank cell (no importable info, so ultimately becomes `NA` in R) is baked in at a very low level. I think this is working correctly.
