### ISSUE TITLE
suggestion - File Info

### ISSUE THREAD

**Issue by msgoussi** [tidyverse/readxl#686]
I am wondering if there is a function retrieves the following information of xls and xlsx files

![image](https://user-images.githubusercontent.com/18138496/156976915-8355a688-0185-4c2c-999a-f4ef745d40eb.png)

**Comment by jennybc** [comment]
No.

Most of what I see above has nothing to do with this being an Excel file or the data within. It's general info one can get from the filesystem. So you might enjoy having a look at the [fs package](https://fs.r-lib.org).
