### ISSUE TITLE
Error: std::bad_alloc

### ISSUE THREAD

**Issue by Knutchanat** [tidyverse/readxl#699]
I try to use CSF function from LiDAR  package and I getting Error in RCSF:::R_CSF(cloud, sloop_smooth, class_threshold, cloth_resolution,  : std::bad_alloc

this is my code  :
mycsf = csf(sloop_smooth = FALSE,
            class_threshold = 1.0,
            cloth_resolution = 2.0,
            rigidness = 2L,
            iterations = 500L,
            time_step = 0.65)

las_classify = classify_ground(las,mycsf)

please help

**Comment by batpigandme** [comment]
It's not clear to me how this is an issue with readxl. 

This sort of question might be a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

**Comment by Knutchanat** [comment]
thank you for your help. I realized that I posted in the wrong place. sorry
