### ISSUE TITLE
How to find how many `skip` if there are empty leading rows?

### ISSUE THREAD

**Issue by tentacles-from-outer-space** [tidyverse/readxl#703]
How can I combine skipping rows when empty ones are present?

I have excel files with messed headers (in two or more rows, e.g. naming group of columns) and sometimes there are leading empty rows.

Example: 

```
x <- data.frame(
	x = c("a","a1","0","1","2")
	,y = c("a","a2","0","1","2")
)
openxlsx::write.xlsx(x, file = "test.xlsx", colNames = TRUE, startRow = 3)
```

I want to skip first two rows (x,y and a,a) so final data will have three rows with names a1, a2. So `skip = 2`.  But when there are empty leading rows it won't work. And I can't find how many empty rows are there without opening Excel, cause readxl always drop them.

Is there any metadata containing true range or number of empty rows? Can I turn off skipping empty rows?

Without empty rows my current workflow was:

1. read file (as `coltypes="text"`) and show user (in markdown/shiny),
2. user provide parameter how many rows to skip
3. read again with one row header and guess types

With empty leading rows I need to read range (A1:A...) and check when it match data witout range to find out how many empty rows are there and the modify skip to include them...

**Comment by jennybc** [comment]
I'm afraid I can't think of anything dramatically better for you to do with current readxl and it seems like an obscure enough problem that I won't attack it directly. It's possible some future improvement, where readxl reveals more about the underlying data, would help you, but that's not imminent. But yeah I think you're stuck with a two-pass solution.

Small tweaks that seem possible: do you really need to read the entire `A` column? You can probably guess some sort of upper bound on how many rows are affected by these shenanigans. Do you really need a human to look at it and specific `skip`? Could you do it programmatically?
