### ISSUE TITLE
Reading xls file with a variable that has strings and integers

### ISSUE THREAD

**Issue by quietlyanalysing** [tidyverse/readxl#75]
I found a small issue when reading in an xls file when there is a variable that contains a mixture of characters and strings -- the numbers get filled up with zeros after a decimal point. It seems to work fine for xlsx files but the raw data file I was sent was in the old Excel format and I wanted to read it in directly (whilst testing out the readxl package at the same time!). For example, if I have a dataset looking like:

```
var1
-------
chicken
123
```

The read_excel() function gives the following:

```
library(readxl)
read_excel("Book1.xls")
        var1
1    chicken
2 123.000000

read_excel("Book1.xlsx")
     var1
1 chicken
2     123
```

**Comment by patidarr** [comment]
I encountered the same error when I am importing a xlsx file where 1st column contain underscores, by default they are not imported as NA.
