### ISSUE TITLE
Feature request: password for protected workbooks

### ISSUE THREAD

**Issue by metanoid** [tidyverse/readxl#84]
If you try to use excel_sheets on a password protected excel workbook, you get the following message:
Error: zip file 'C:/test.xlsx' cannot be opened.  I have tested and it seems to only occur when the file is password protected, which makes sense.

It would be nice if the user could specify a password to use to unprotect the workbook.

**Comment by sfirke** [comment]
I'm looking at reading 100 workbooks that all have the same password on them, and agree this would be handy.  FYI that this has been implemented in the [excel.link](https://github.com/gdemin/excel.link) package.

**Comment by jennybc** [comment]
Can either of you provide more info on how `excel.link` exposes this and ... poking around excel.link's README a little ... does it require a "running instance of Excel"? I suspect this is out of scope of readxl.

**Comment by metanoid** [comment]
@jennybc 
I did a bit of poking around.  When you save an unprotected workbook using Excel 2013, the `xlsx` file generated is actually a `zip` file containing a bunch of `xml` files.  However, when you save a protected workbook, this is not longer true - the xlsx file is actually a `MS-CFB` (Compound File Binary) format file.  Which seems similiar, but is not quite the same as `zip`.  

[See here for a discussion](https://social.msdn.microsoft.com/Forums/en-US/7021768e-4562-43dd-9d5e-89c10970bf33/create-password-protected-excel-sheet-with-ooxml?forum=os_specifications)

I renamed a protected workbook to `test.zip` and unzipped it, and it produced a text file called `EncryptionInfo` - It looks like this file has all the encryption details we might need to decrypt the file (assuming we have the password), but I have no idea where to go from here.

**Comment by jennybc** [comment]
We're not going to implement this in readxl at this point.

But if someone was motivated to make a PR, I'd consider it. In that case, it would be worth discussing the implementation in advance, to make sure it's likely to be accepted. For example, I don't think we'd ever merge a solution that requires a running instance of Excel. It's possible such a thing should be a separate helper package that converts a password-protected workbook into a tempfile that readxl can read normally.

**Comment by baderstine** [comment]
possibly helpful related links:
https://stackoverflow.com/questions/35852722/how-do-you-read-a-password-protected-excel-file-into-r

**Comment by AshesITR** [comment]
Microsoft has a C++ implementation for reading from a CFB. Maybe it can be linked?

https://github.com/Microsoft/compoundfilereader

**Comment by jennybc** [comment]
That seems to require c++11 whereas readxl currently does not. Fitting that into place is a nontrivial amount of work. I don't think I am likely to tackle it, i.e. I have other projects on the compiled code side that are much higher priority. I guess if someone was *super keen*, we could discuss them making a PR for consideration.
