### ISSUE TITLE
Add option to specify file format to support Shiny fileInput()

### ISSUE THREAD

**Issue by pofigster** [tidyverse/readxl#85]
When a file is loaded through a fileInput() widget in a Shiny app, it appears that read_excel scans the file name to determine the file type (at least when input$file[,4] - the file path) is used.  Shiny uploads an extension-less temporary file so read_excel can't open the file.

**Comment by Nihasa** [comment]
Hi, I ran into this problem as well and my current workaround is as follows:

               file.copy(inFile$datapath,
                          paste(inFile$datapath, ".xlsx", sep=""))
                read_excel(
                        paste(inFile$datapath, ".xlsx", sep=""), 1)

it's not the cleanest but it works.

**Comment by andrewcstewart** [comment]
thanks for the workaround @Nihasa

**Comment by faidherbard** [comment]
Hello,
This is not specific to `readxl`, I ran into the same issue with `readr` when I wanted to `read_csv` a zipped CSV file. `readr` does it right in my R scripts when it has the extension, but it fails with the extension-less temporary file uploaded by Shiny.

**Comment by 0tertra** [comment]
to ensure that the user does upload an .xlsx file, or you need to check the extension you're self to switch between read functions. You can  extract the extension as following:   

    ext <- tools::file_ext(inFile$name)
     file.copy(inFile$datapath,
                       paste(inFile$datapath, ext, sep="."))
     read_excel(paste(inFile$datapath, ext, sep="."), 1)

**Comment by zross** [comment]
I agree that adding the ability to feed `read_excel()` the extension would be useful, particularly in Shiny where the filename from fileInput drops the extension.
