### ISSUE TITLE
Can't read excel files on network drive

### ISSUE THREAD

**Issue by grandtiger** [tidyverse/readxl#95]
The following failed.

```
data <- read_excel("//ntdisk01/data/common/reports/mydata.xls")
```

However, after mapping //ntdisk01/data/common to a local drive letter X, then the following works

```
data <- read_excel("X:/reports/mydata.xls")
```

Did I miss something here, or UNC path is not supported in the library?

**Comment by hadley** [comment]
What error message do you get?

**Comment by jiunsiew** [comment]
Hi there,

I got a similar problem but working with OS X and using VPN to connect to a windows network drive (via samba).  

I get the following error:
Error: Failed to open /Volumes/<dir1>/<dir2>/<dir3>/<dir4>/<dir5>/<dir6>/20150526/201406-201408_dailyData.xls

It's a company network so having to be careful with drive names--but the character string is quite long.  Is there a limit for this?

I can read csv and txt files fine so I know R can read off this network drive.  And I've also used 'list.files' with 'full.names = TRUE' to avoid getting typo mistakes.  

Would appreciate any suggestions..thanks.

**Comment by datalove** [comment]
Are you sure that UNC path will work in R in general? 

Have you tried something like this?
```
list.files("//ntdisk01/data/common/reports/mydata.xls")
```
In order to get UNC paths to work in R for, I've had to refer to them like this (under Windows).
```
data <- read_excel("\\\\ntdisk01/data/common/reports/mydata.xls")
```
